import type { GridLayout, Region } from './types.ts';
import { VERSION } from './version.ts';

/**
 * Emit the header comment block — the user's "source map" back to their
 * configuration. Format is part of the public contract of the emitter
 * (see vault `notes/engineering-kickoff.md` Project-specific addenda).
 */
export function emitHeader(layout: GridLayout): string {
  const totalRegions = layout.pages.flatMap((p) => p.regions).length;
  const pageWord = layout.pages.length === 1 ? 'page' : 'pages';
  const regionWord = totalRegions === 1 ? 'region' : 'regions';

  const lines: string[] = [
    '-- =========================================================',
    `-- Generated by monome-iii-studio v${VERSION}`,
    `-- Layout: ${layout.width}x${layout.height}, ${layout.pages.length} ${pageWord}, ${totalRegions} ${regionWord}`,
  ];

  layout.pages.forEach((page, i) => {
    lines.push(`--   page ${i + 1} "${page.name}":`);
    for (const region of page.regions) {
      lines.push(`--     - ${describeRegion(region)}`);
    }
  });

  lines.push(`-- Upload: diii  →  first("${layout.name}.lua")`);
  lines.push('-- =========================================================');

  return lines.join('\n');
}

function describeRegion(region: Region): string {
  const cellWord = region.cells.length === 1 ? 'cell' : 'cells';
  const cellsDesc = `${region.cells.length} ${cellWord}`;
  return `"${region.name}" (${cellsDesc}, ${describeBehavior(region)})`;
}

function describeBehavior(region: Region): string {
  if (region.behavior.kind === 'momentary') {
    const p = region.behavior.params;
    if (p.output_type === 'note') {
      const noun = region.mode === 'per_cell' ? 'note from' : 'note';
      return `momentary ${region.mode}, ch${p.channel} ${noun} MIDI ${p.note}`;
    }
    const noun = region.mode === 'per_cell' ? 'cc from' : 'cc';
    return `momentary ${region.mode}, ch${p.channel} ${noun} ${p.cc}`;
  }
  if (region.behavior.kind === 'toggle') {
    const p = region.behavior.params;
    const noun = region.mode === 'per_cell' ? 'cc from' : 'cc';
    return `toggle ${region.mode}, ch${p.channel} ${noun} ${p.cc}`;
  }
  if (region.behavior.kind === 'radio') {
    const p = region.behavior.params;
    return `radio group, ch${p.channel} cc ${p.cc} → 0..127`;
  }
  if (region.behavior.kind === 'range') {
    const p = region.behavior.params;
    return `range group, ch${p.channel} cc ${p.cc_low}/${p.cc_high} → 0..127`;
  }
  if (region.behavior.kind === 'meter') {
    const p = region.behavior.params;
    const numCols = new Set(region.cells.map((c) => c.x)).size;
    return `meter group, ch${p.channel} cc from ${p.base_cc}, ${numCols} cols → 0..127`;
  }
  if (region.behavior.kind === 'note_keyboard') {
    const p = region.behavior.params;
    return `note keyboard per_cell, ch${p.channel} root MIDI ${p.root_note} (row=${p.row_interval}, col=${p.column_interval})`;
  }
  if (region.behavior.kind === 'step_sequencer') {
    const p = region.behavior.params;
    const xs = region.cells.map((c) => c.x);
    const ys = region.cells.map((c) => c.y);
    const numCols = Math.max(...xs) - Math.min(...xs) + 1;
    const numRows = Math.max(...ys) - Math.min(...ys) + 1;
    if (p.output_mode === 'note_per_row') {
      return `step seq group, ${numRows}×${numCols}, ch${p.channel} note from ${p.base_note}, ${p.bpm} BPM @ 1/${p.steps_per_beat}`;
    }
    return `step seq group, ${numRows}×${numCols}, ch${p.channel} cc from ${p.base_cc}, ${p.bpm} BPM @ 1/${p.steps_per_beat}`;
  }
  // Exhaustive: every behavior kind handled above.
  return '';
}
