-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "lfo" (8 cells, lfo group, sine ch1 cc50 16..112 @ 1s)
-- Upload: diii  →  first("test-lfo-sine.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  lfo_phase = 0,
  lfo_lastv = -1,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: lfo (lfo, sine) ----
local function _lfo_tick()
  state.lfo_phase = (state.lfo_phase + 0.02) % 1
  local p = state.lfo_phase
  local w = math.sin(2 * math.pi * p)
  local v = math.floor(64 + 48 * w + 0.5)
  if v < 0 then v = 0 end
  if v > 127 then v = 127 end
  if v ~= state.lfo_lastv then
    midi_cc(50, v, 1)
    state.lfo_lastv = v
    redraw()
  end
end

local _lfo_metro = metro.init(_lfo_tick, 0.02)
_lfo_metro:start()

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: lfo
  grid_led(1, 1, state.lfo_lastv >= 28 and 12 or 3)
  grid_led(2, 1, state.lfo_lastv >= 40 and 12 or 3)
  grid_led(3, 1, state.lfo_lastv >= 52 and 12 or 3)
  grid_led(4, 1, state.lfo_lastv >= 64 and 12 or 3)
  grid_led(5, 1, state.lfo_lastv >= 76 and 12 or 3)
  grid_led(6, 1, state.lfo_lastv >= 88 and 12 or 3)
  grid_led(7, 1, state.lfo_lastv >= 100 and 12 or 3)
  grid_led(8, 1, state.lfo_lastv >= 112 and 12 or 3)
end

-- ---- master redraw ----
redraw = function()
  _draw_p0()
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}

local _route_p0 = {}

local _routes = {[0]=_route_p0}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- init ----
grid_led_all(0)
state.lfo_lastv = 64
midi_cc(50, 64, 1)
redraw()
