-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "faders" (32 cells, meter group, ch1 cc from 16, 4 cols → 0..127)
-- Upload: diii  →  first("test-meter-4cols.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  faders_h = {[0]=0, [1]=0, [2]=0, [3]=0},
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- region: faders ----
local _faders_col = {}
_faders_col[1 + 1*W] = 0
_faders_col[1 + 2*W] = 0
_faders_col[1 + 3*W] = 0
_faders_col[1 + 4*W] = 0
_faders_col[1 + 5*W] = 0
_faders_col[1 + 6*W] = 0
_faders_col[1 + 7*W] = 0
_faders_col[1 + 8*W] = 0
_faders_col[2 + 1*W] = 1
_faders_col[2 + 2*W] = 1
_faders_col[2 + 3*W] = 1
_faders_col[2 + 4*W] = 1
_faders_col[2 + 5*W] = 1
_faders_col[2 + 6*W] = 1
_faders_col[2 + 7*W] = 1
_faders_col[2 + 8*W] = 1
_faders_col[3 + 1*W] = 2
_faders_col[3 + 2*W] = 2
_faders_col[3 + 3*W] = 2
_faders_col[3 + 4*W] = 2
_faders_col[3 + 5*W] = 2
_faders_col[3 + 6*W] = 2
_faders_col[3 + 7*W] = 2
_faders_col[3 + 8*W] = 2
_faders_col[4 + 1*W] = 3
_faders_col[4 + 2*W] = 3
_faders_col[4 + 3*W] = 3
_faders_col[4 + 4*W] = 3
_faders_col[4 + 5*W] = 3
_faders_col[4 + 6*W] = 3
_faders_col[4 + 7*W] = 3
_faders_col[4 + 8*W] = 3
local _faders_values = {[0]=0, [1]=15, [2]=31, [3]=47, [4]=63, [5]=79, [6]=95, [7]=111, [8]=127}

local function handle_faders(x, y, z)
  if z ~= 1 then return end
  local col = _faders_col[x + y*W]
  local h = 8 - (y - 1)
  state.faders_h[col] = h
  midi_cc(16 + col, _faders_values[h], 1)
end

-- ---- LED draw ----
local function redraw()
  -- region: faders
  grid_led(1, 1, state.faders_h[0] > 7 and 12 or 3)
  grid_led(1, 2, state.faders_h[0] > 6 and 12 or 3)
  grid_led(1, 3, state.faders_h[0] > 5 and 12 or 3)
  grid_led(1, 4, state.faders_h[0] > 4 and 12 or 3)
  grid_led(1, 5, state.faders_h[0] > 3 and 12 or 3)
  grid_led(1, 6, state.faders_h[0] > 2 and 12 or 3)
  grid_led(1, 7, state.faders_h[0] > 1 and 12 or 3)
  grid_led(1, 8, state.faders_h[0] > 0 and 12 or 3)
  grid_led(2, 1, state.faders_h[1] > 7 and 12 or 3)
  grid_led(2, 2, state.faders_h[1] > 6 and 12 or 3)
  grid_led(2, 3, state.faders_h[1] > 5 and 12 or 3)
  grid_led(2, 4, state.faders_h[1] > 4 and 12 or 3)
  grid_led(2, 5, state.faders_h[1] > 3 and 12 or 3)
  grid_led(2, 6, state.faders_h[1] > 2 and 12 or 3)
  grid_led(2, 7, state.faders_h[1] > 1 and 12 or 3)
  grid_led(2, 8, state.faders_h[1] > 0 and 12 or 3)
  grid_led(3, 1, state.faders_h[2] > 7 and 12 or 3)
  grid_led(3, 2, state.faders_h[2] > 6 and 12 or 3)
  grid_led(3, 3, state.faders_h[2] > 5 and 12 or 3)
  grid_led(3, 4, state.faders_h[2] > 4 and 12 or 3)
  grid_led(3, 5, state.faders_h[2] > 3 and 12 or 3)
  grid_led(3, 6, state.faders_h[2] > 2 and 12 or 3)
  grid_led(3, 7, state.faders_h[2] > 1 and 12 or 3)
  grid_led(3, 8, state.faders_h[2] > 0 and 12 or 3)
  grid_led(4, 1, state.faders_h[3] > 7 and 12 or 3)
  grid_led(4, 2, state.faders_h[3] > 6 and 12 or 3)
  grid_led(4, 3, state.faders_h[3] > 5 and 12 or 3)
  grid_led(4, 4, state.faders_h[3] > 4 and 12 or 3)
  grid_led(4, 5, state.faders_h[3] > 3 and 12 or 3)
  grid_led(4, 6, state.faders_h[3] > 2 and 12 or 3)
  grid_led(4, 7, state.faders_h[3] > 1 and 12 or 3)
  grid_led(4, 8, state.faders_h[3] > 0 and 12 or 3)
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 1*W] = handle_faders
_route[2 + 1*W] = handle_faders
_route[3 + 1*W] = handle_faders
_route[4 + 1*W] = handle_faders
_route[1 + 2*W] = handle_faders
_route[2 + 2*W] = handle_faders
_route[3 + 2*W] = handle_faders
_route[4 + 2*W] = handle_faders
_route[1 + 3*W] = handle_faders
_route[2 + 3*W] = handle_faders
_route[3 + 3*W] = handle_faders
_route[4 + 3*W] = handle_faders
_route[1 + 4*W] = handle_faders
_route[2 + 4*W] = handle_faders
_route[3 + 4*W] = handle_faders
_route[4 + 4*W] = handle_faders
_route[1 + 5*W] = handle_faders
_route[2 + 5*W] = handle_faders
_route[3 + 5*W] = handle_faders
_route[4 + 5*W] = handle_faders
_route[1 + 6*W] = handle_faders
_route[2 + 6*W] = handle_faders
_route[3 + 6*W] = handle_faders
_route[4 + 6*W] = handle_faders
_route[1 + 7*W] = handle_faders
_route[2 + 7*W] = handle_faders
_route[3 + 7*W] = handle_faders
_route[4 + 7*W] = handle_faders
_route[1 + 8*W] = handle_faders
_route[2 + 8*W] = handle_faders
_route[3 + 8*W] = handle_faders
_route[4 + 8*W] = handle_faders

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
