-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 1 region
--   page 1 "main":
--     - "mutes" (8 cells, momentary group, ch1 cc 100)
-- Upload: diii  →  first("test-group-cc.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  mutes_count = 0,
}

-- ---- region: mutes ----
local function handle_mutes(x, y, z)
  if z == 1 then
    state.mutes_count = state.mutes_count + 1
    if state.mutes_count == 1 then
      midi_cc(100, 127, 1)
    end
  else
    state.mutes_count = state.mutes_count - 1
    if state.mutes_count == 0 then
      midi_cc(100, 0, 1)
    end
  end
end

-- ---- LED draw ----
local function redraw()
  grid_led_all(0)
  -- region: mutes
  do
    local lit = state.mutes_count > 0 and 12 or 3
    grid_led(1, 1, lit)
    grid_led(2, 1, lit)
    grid_led(3, 1, lit)
    grid_led(4, 1, lit)
    grid_led(5, 1, lit)
    grid_led(6, 1, lit)
    grid_led(7, 1, lit)
    grid_led(8, 1, lit)
  end
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 1*W] = handle_mutes
_route[2 + 1*W] = handle_mutes
_route[3 + 1*W] = handle_mutes
_route[4 + 1*W] = handle_mutes
_route[5 + 1*W] = handle_mutes
_route[6 + 1*W] = handle_mutes
_route[7 + 1*W] = handle_mutes
_route[8 + 1*W] = handle_mutes

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
redraw()
