-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 2 regions
--   page 1 "main":
--     - "notes" (8 cells, momentary per_cell, ch1 note from MIDI 36)
--     - "mutes" (8 cells, momentary group, ch1 cc 100)
-- Upload: diii  →  first("test-mixed.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  notes_held = {},
  mutes_count = 0,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- region: notes ----
local _notes_idx = {}
_notes_idx[1 + 8*W] = 0
_notes_idx[2 + 8*W] = 1
_notes_idx[3 + 8*W] = 2
_notes_idx[4 + 8*W] = 3
_notes_idx[5 + 8*W] = 4
_notes_idx[6 + 8*W] = 5
_notes_idx[7 + 8*W] = 6
_notes_idx[8 + 8*W] = 7

local function handle_notes(x, y, z)
  local idx = _notes_idx[x + y*W]
  if z == 1 then
    midi_note_on(36 + idx, 100, 1)
    state.notes_held[x + y*W] = true
  else
    midi_note_off(36 + idx, 0, 1)
    state.notes_held[x + y*W] = nil
  end
end

-- ---- region: mutes ----
local function handle_mutes(x, y, z)
  if z == 1 then
    state.mutes_count = state.mutes_count + 1
    if state.mutes_count == 1 then
      midi_cc(100, 127, 1)
    end
  else
    state.mutes_count = state.mutes_count - 1
    if state.mutes_count == 0 then
      midi_cc(100, 0, 1)
    end
  end
end

-- ---- LED draw ----
local function redraw()
  -- region: notes
  grid_led(1, 8, state.notes_held[1 + 8*W] and 12 or 3)
  grid_led(2, 8, state.notes_held[2 + 8*W] and 12 or 3)
  grid_led(3, 8, state.notes_held[3 + 8*W] and 12 or 3)
  grid_led(4, 8, state.notes_held[4 + 8*W] and 12 or 3)
  grid_led(5, 8, state.notes_held[5 + 8*W] and 12 or 3)
  grid_led(6, 8, state.notes_held[6 + 8*W] and 12 or 3)
  grid_led(7, 8, state.notes_held[7 + 8*W] and 12 or 3)
  grid_led(8, 8, state.notes_held[8 + 8*W] and 12 or 3)
  -- region: mutes
  do
    local lit = state.mutes_count > 0 and 12 or 3
    grid_led(1, 1, lit)
    grid_led(2, 1, lit)
    grid_led(3, 1, lit)
    grid_led(4, 1, lit)
    grid_led(5, 1, lit)
    grid_led(6, 1, lit)
    grid_led(7, 1, lit)
    grid_led(8, 1, lit)
  end
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 8*W] = handle_notes
_route[2 + 8*W] = handle_notes
_route[3 + 8*W] = handle_notes
_route[4 + 8*W] = handle_notes
_route[5 + 8*W] = handle_notes
_route[6 + 8*W] = handle_notes
_route[7 + 8*W] = handle_notes
_route[8 + 8*W] = handle_notes
_route[1 + 1*W] = handle_mutes
_route[2 + 1*W] = handle_mutes
_route[3 + 1*W] = handle_mutes
_route[4 + 1*W] = handle_mutes
_route[5 + 1*W] = handle_mutes
_route[6 + 1*W] = handle_mutes
_route[7 + 1*W] = handle_mutes
_route[8 + 1*W] = handle_mutes

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
