-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 1 region
--   page 1 "main":
--     - "mutes" (8 cells, momentary group, ch1 cc 100)
-- Upload: diii  →  first("test-group-cc.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  mutes_count = 0,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: mutes ----
local function handle_mutes(x, y, z)
  if z == 1 then
    state.mutes_count = state.mutes_count + 1
    if state.mutes_count == 1 then
      midi_cc(100, 127, 1)
    end
  else
    state.mutes_count = state.mutes_count - 1
    if state.mutes_count == 0 then
      midi_cc(100, 0, 1)
    end
  end
end

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: mutes
  do
    local lit = state.mutes_count > 0 and 12 or 3
    grid_led(1, 1, lit)
    grid_led(2, 1, lit)
    grid_led(3, 1, lit)
    grid_led(4, 1, lit)
    grid_led(5, 1, lit)
    grid_led(6, 1, lit)
    grid_led(7, 1, lit)
    grid_led(8, 1, lit)
  end
end

-- ---- master redraw ----
redraw = function()
  _draw_p0()
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}

local _route_p0 = {}
_route_p0[1 + 1*W] = handle_mutes
_route_p0[2 + 1*W] = handle_mutes
_route_p0[3 + 1*W] = handle_mutes
_route_p0[4 + 1*W] = handle_mutes
_route_p0[5 + 1*W] = handle_mutes
_route_p0[6 + 1*W] = handle_mutes
_route_p0[7 + 1*W] = handle_mutes
_route_p0[8 + 1*W] = handle_mutes

local _routes = {[0]=_route_p0}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
