-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 1 region
--   page 1 "main":
--     - "notes" (8 cells, momentary per_cell, ch1 note from MIDI 36)
-- Upload: diii  →  first("test-per-cell-notes.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  notes_held = {},
}

-- ---- region: notes ----
local _notes_idx = {}
_notes_idx[0 + 7*W] = 0
_notes_idx[1 + 7*W] = 1
_notes_idx[2 + 7*W] = 2
_notes_idx[3 + 7*W] = 3
_notes_idx[4 + 7*W] = 4
_notes_idx[5 + 7*W] = 5
_notes_idx[6 + 7*W] = 6
_notes_idx[7 + 7*W] = 7

local function handle_notes(x, y, z)
  local idx = _notes_idx[x + y*W]
  if z == 1 then
    midi_note_on(36 + idx, 100, 1)
    state.notes_held[x + y*W] = true
  else
    midi_note_off(36 + idx, 0, 1)
    state.notes_held[x + y*W] = nil
  end
end

-- ---- LED draw ----
local function redraw()
  grid_led_all(0)
  -- region: notes
  grid_led(0, 7, state.notes_held[0 + 7*W] and 12 or 3)
  grid_led(1, 7, state.notes_held[1 + 7*W] and 12 or 3)
  grid_led(2, 7, state.notes_held[2 + 7*W] and 12 or 3)
  grid_led(3, 7, state.notes_held[3 + 7*W] and 12 or 3)
  grid_led(4, 7, state.notes_held[4 + 7*W] and 12 or 3)
  grid_led(5, 7, state.notes_held[5 + 7*W] and 12 or 3)
  grid_led(6, 7, state.notes_held[6 + 7*W] and 12 or 3)
  grid_led(7, 7, state.notes_held[7 + 7*W] and 12 or 3)
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[0 + 7*W] = handle_notes
_route[1 + 7*W] = handle_notes
_route[2 + 7*W] = handle_notes
_route[3 + 7*W] = handle_notes
_route[4 + 7*W] = handle_notes
_route[5 + 7*W] = handle_notes
_route[6 + 7*W] = handle_notes
_route[7 + 7*W] = handle_notes

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
redraw()
