-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 2 pages, 3 regions
--   page 1 "drums":
--     - "pages" (2 cells, page select global, 2 cells)
--     - "pads" (4 cells, momentary per_cell, ch1 note from MIDI 36)
--   page 2 "keys":
--     - "keys" (8 cells, momentary per_cell, ch1 note from MIDI 60)
-- Upload: diii  →  first("test-multipage.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  pads_held = {},
  keys_held = {},
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: pages (page_select) ----
local _pages_target = {}
_pages_target[15 + 1*W] = 0
_pages_target[16 + 1*W] = 1

local function handle_pages(x, y, z)
  if z ~= 1 then return end
  local target = _pages_target[x + y*W]
  if target == nil or target >= 2 then return end
  if target == state.page then return end
  state.page = target
  -- Force a full repaint on the new page: clear the LED delta
  -- cache and blank the hardware before drawing, otherwise cells
  -- that the new page doesn't write to keep their stale value.
  for k in pairs(_prev_led) do _prev_led[k] = nil end
  grid_led_all(0)
  redraw()
end

-- ---- region: pads ----
local _pads_idx = {}
_pads_idx[1 + 8*W] = 0
_pads_idx[2 + 8*W] = 1
_pads_idx[3 + 8*W] = 2
_pads_idx[4 + 8*W] = 3

local function handle_pads(x, y, z)
  local idx = _pads_idx[x + y*W]
  if z == 1 then
    midi_note_on(36 + idx, 100, 1)
    state.pads_held[x + y*W] = true
  else
    midi_note_off(36 + idx, 0, 1)
    state.pads_held[x + y*W] = nil
  end
end

-- ---- region: keys ----
local _keys_idx = {}
_keys_idx[1 + 8*W] = 0
_keys_idx[2 + 8*W] = 1
_keys_idx[3 + 8*W] = 2
_keys_idx[4 + 8*W] = 3
_keys_idx[5 + 8*W] = 4
_keys_idx[6 + 8*W] = 5
_keys_idx[7 + 8*W] = 6
_keys_idx[8 + 8*W] = 7

local function handle_keys(x, y, z)
  local idx = _keys_idx[x + y*W]
  if z == 1 then
    midi_note_on(60 + idx, 100, 1)
    state.keys_held[x + y*W] = true
  else
    midi_note_off(60 + idx, 0, 1)
    state.keys_held[x + y*W] = nil
  end
end

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: pads
  grid_led(1, 8, state.pads_held[1 + 8*W] and 12 or 3)
  grid_led(2, 8, state.pads_held[2 + 8*W] and 12 or 3)
  grid_led(3, 8, state.pads_held[3 + 8*W] and 12 or 3)
  grid_led(4, 8, state.pads_held[4 + 8*W] and 12 or 3)
end

local function _draw_p1()
  -- region: keys
  grid_led(1, 8, state.keys_held[1 + 8*W] and 12 or 3)
  grid_led(2, 8, state.keys_held[2 + 8*W] and 12 or 3)
  grid_led(3, 8, state.keys_held[3 + 8*W] and 12 or 3)
  grid_led(4, 8, state.keys_held[4 + 8*W] and 12 or 3)
  grid_led(5, 8, state.keys_held[5 + 8*W] and 12 or 3)
  grid_led(6, 8, state.keys_held[6 + 8*W] and 12 or 3)
  grid_led(7, 8, state.keys_held[7 + 8*W] and 12 or 3)
  grid_led(8, 8, state.keys_held[8 + 8*W] and 12 or 3)
end

-- ---- master redraw ----
redraw = function()
  -- region: pages
  grid_led(15, 1, state.page == 0 and 12 or 4)
  grid_led(16, 1, state.page == 1 and 12 or 4)
  if state.page == 0 then _draw_p0()
  elseif state.page == 1 then _draw_p1()
  end
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}
_route_global[15 + 1*W] = handle_pages
_route_global[16 + 1*W] = handle_pages

local _route_p0 = {}
_route_p0[1 + 8*W] = handle_pads
_route_p0[2 + 8*W] = handle_pads
_route_p0[3 + 8*W] = handle_pads
_route_p0[4 + 8*W] = handle_pads
local _route_p1 = {}
_route_p1[1 + 8*W] = handle_keys
_route_p1[2 + 8*W] = handle_keys
_route_p1[3 + 8*W] = handle_keys
_route_p1[4 + 8*W] = handle_keys
_route_p1[5 + 8*W] = handle_keys
_route_p1[6 + 8*W] = handle_keys
_route_p1[7 + 8*W] = handle_keys
_route_p1[8 + 8*W] = handle_keys

local _routes = {[0]=_route_p0, [1]=_route_p1}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
