-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "keys" (40 cells, note keyboard per_cell, ch1 root MIDI 60 (row=5, col=1, major))
-- Upload: diii  →  first("test-nk-live-scale.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  keys_held = {},
  keys_scale_idx = 2,
  keys_coach_chord = 1,
  keys_coach_blink = 0,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: keys ----
local _keys_note = {}
_keys_note[1 + 1*W] = 95
_keys_note[2 + 1*W] = 96
_keys_note[3 + 1*W] = 97
_keys_note[4 + 1*W] = 98
_keys_note[1 + 2*W] = 90
_keys_note[2 + 2*W] = 91
_keys_note[3 + 2*W] = 92
_keys_note[4 + 2*W] = 93
_keys_note[1 + 3*W] = 85
_keys_note[2 + 3*W] = 86
_keys_note[3 + 3*W] = 87
_keys_note[4 + 3*W] = 88
_keys_note[1 + 4*W] = 80
_keys_note[2 + 4*W] = 81
_keys_note[3 + 4*W] = 82
_keys_note[4 + 4*W] = 83
_keys_note[1 + 5*W] = 75
_keys_note[2 + 5*W] = 76
_keys_note[3 + 5*W] = 77
_keys_note[4 + 5*W] = 78
_keys_note[1 + 6*W] = 70
_keys_note[2 + 6*W] = 71
_keys_note[3 + 6*W] = 72
_keys_note[4 + 6*W] = 73
_keys_note[1 + 7*W] = 65
_keys_note[2 + 7*W] = 66
_keys_note[3 + 7*W] = 67
_keys_note[4 + 7*W] = 68
_keys_note[1 + 8*W] = 60
_keys_note[2 + 8*W] = 61
_keys_note[3 + 8*W] = 62
_keys_note[4 + 8*W] = 63
local _keys_scale_member = {}
_keys_scale_member[1] = {[0]=true, [1]=true, [2]=true, [3]=true, [4]=true, [5]=true, [6]=true, [7]=true, [8]=true, [9]=true, [10]=true, [11]=true}
_keys_scale_member[2] = {[0]=true, [2]=true, [4]=true, [5]=true, [7]=true, [9]=true, [11]=true}
_keys_scale_member[3] = {[0]=true, [2]=true, [3]=true, [5]=true, [7]=true, [8]=true, [10]=true}
_keys_scale_member[4] = {[0]=true, [2]=true, [3]=true, [5]=true, [7]=true, [9]=true, [10]=true}
_keys_scale_member[5] = {[0]=true, [1]=true, [3]=true, [5]=true, [7]=true, [8]=true, [10]=true}
_keys_scale_member[6] = {[0]=true, [2]=true, [4]=true, [6]=true, [7]=true, [9]=true, [11]=true}
_keys_scale_member[7] = {[0]=true, [2]=true, [4]=true, [5]=true, [7]=true, [9]=true, [10]=true}
_keys_scale_member[8] = {[0]=true, [1]=true, [3]=true, [5]=true, [6]=true, [8]=true, [10]=true}
local _keys_picker = {}
_keys_picker[5 + 1*W] = 1
_keys_picker[5 + 2*W] = 2
_keys_picker[5 + 3*W] = 3
_keys_picker[5 + 4*W] = 4
_keys_picker[5 + 5*W] = 5
_keys_picker[5 + 6*W] = 6
_keys_picker[5 + 7*W] = 7
_keys_picker[5 + 8*W] = 8
local _keys_chord_voicing = {}
_keys_chord_voicing[1] = {}
_keys_chord_voicing[2] = {}
_keys_chord_voicing[3] = {}
_keys_chord_voicing[4] = {}
_keys_chord_voicing[5] = {}
_keys_chord_voicing[6] = {}
_keys_chord_voicing[7] = {}
_keys_chord_voicing[8] = {}
_keys_chord_voicing[2][1] = {{18, 52, 34}, {99, 82, 115}}
_keys_chord_voicing[2][2] = {{50, 83, 66}}
_keys_chord_voicing[2][3] = {{52, 34, 17}, {82, 115, 98}, {52, 34, 68}}
_keys_chord_voicing[2][4] = {{83, 66, 99}}
_keys_chord_voicing[2][5] = {{34, 17, 20}, {34, 68, 50}, {34, 17, 50}}
_keys_chord_voicing[2][6] = {{66, 99, 82}, {36, 18, 52}}
_keys_chord_voicing[2][7] = {{98, 131, 113}, {68, 50, 83}}
_keys_chord_voicing[3][1] = {{129, 132, 115}, {18, 51, 34}, {99, 81, 115}}
_keys_chord_voicing[3][2] = {{131, 113, 116}, {50, 83, 65}}
_keys_chord_voicing[3][3] = {{132, 115, 97}, {81, 115, 97}, {51, 34, 67}}
_keys_chord_voicing[3][4] = {{113, 116, 99}, {83, 116, 99}, {83, 65, 99}}
_keys_chord_voicing[3][5] = {{34, 67, 50}, {115, 97, 131}}
_keys_chord_voicing[3][6] = {{116, 99, 81}, {65, 99, 81}, {35, 18, 51}}
_keys_chord_voicing[3][7] = {{97, 131, 113}, {67, 50, 83}}
_keys_chord_voicing[4][1] = {{129, 132, 115}, {18, 51, 34}, {99, 81, 115}}
_keys_chord_voicing[4][2] = {{50, 83, 66}}
_keys_chord_voicing[4][3] = {{132, 115, 97}, {81, 115, 97}, {51, 34, 67}}
_keys_chord_voicing[4][4] = {{83, 66, 99}}
_keys_chord_voicing[4][5] = {{34, 67, 50}, {115, 97, 131}}
_keys_chord_voicing[4][6] = {{66, 99, 81}, {36, 18, 51}}
_keys_chord_voicing[4][7] = {{97, 131, 113}, {67, 50, 83}}
_keys_chord_voicing[5][1] = {{129, 132, 115}, {18, 51, 34}, {99, 81, 115}}
_keys_chord_voicing[5][2] = {{130, 113, 116}, {49, 83, 65}, {100, 83, 116}}
_keys_chord_voicing[5][3] = {{132, 115, 97}, {81, 115, 97}, {51, 34, 67}}
_keys_chord_voicing[5][4] = {{113, 116, 99}, {83, 116, 99}, {83, 65, 99}}
_keys_chord_voicing[5][5] = {{115, 97, 100}, {34, 67, 49}, {115, 97, 130}}
_keys_chord_voicing[5][6] = {{116, 99, 81}, {65, 99, 81}, {35, 18, 51}}
_keys_chord_voicing[5][7] = {{97, 100, 83}, {67, 100, 83}, {67, 49, 83}}
_keys_chord_voicing[6][1] = {{18, 52, 34}, {99, 82, 115}}
_keys_chord_voicing[6][2] = {{50, 33, 36}, {20, 33, 36}, {50, 33, 66}}
_keys_chord_voicing[6][3] = {{52, 34, 17}, {82, 115, 98}, {52, 34, 68}}
_keys_chord_voicing[6][4] = {{33, 36, 18}, {84, 66, 99}}
_keys_chord_voicing[6][5] = {{34, 17, 20}, {34, 68, 50}, {34, 17, 50}}
_keys_chord_voicing[6][6] = {{66, 99, 82}, {36, 18, 52}}
_keys_chord_voicing[6][7] = {{68, 50, 33}, {17, 50, 33}, {17, 20, 33}}
_keys_chord_voicing[7][1] = {{18, 52, 34}, {99, 82, 115}}
_keys_chord_voicing[7][2] = {{50, 83, 66}}
_keys_chord_voicing[7][3] = {{82, 115, 97}, {52, 34, 67}}
_keys_chord_voicing[7][4] = {{83, 66, 99}}
_keys_chord_voicing[7][5] = {{34, 67, 50}, {115, 97, 131}}
_keys_chord_voicing[7][6] = {{66, 99, 82}, {36, 18, 52}}
_keys_chord_voicing[7][7] = {{97, 131, 113}, {67, 50, 83}}
_keys_chord_voicing[8][1] = {{99, 81, 84}, {18, 51, 33}, {99, 81, 114}}
_keys_chord_voicing[8][2] = {{130, 113, 116}, {49, 83, 65}, {100, 83, 116}}
_keys_chord_voicing[8][3] = {{81, 84, 67}, {51, 84, 67}, {51, 33, 67}}
_keys_chord_voicing[8][4] = {{113, 116, 99}, {83, 116, 99}, {83, 65, 99}}
_keys_chord_voicing[8][5] = {{114, 97, 100}, {33, 67, 49}, {84, 67, 100}}
_keys_chord_voicing[8][6] = {{116, 99, 81}, {65, 99, 81}, {35, 18, 51}}
_keys_chord_voicing[8][7] = {{97, 100, 83}, {67, 100, 83}, {67, 49, 83}}
local _keys_next_chord = {[1]={2, 3, 4, 5, 6, 7}, [2]={5, 7}, [3]={4, 6}, [4]={1, 5, 7}, [5]={1, 6}, [6]={2, 4, 5}, [7]={1, 3}}
local function _keys_revoice()
  local vs = _keys_chord_voicing[state.keys_scale_idx][state.keys_coach_chord]
  if not vs or #vs == 0 then state.keys_coach_voicing = nil; return end
  local base = vs[math.random(1, #vs)]
  local prev = state.keys_coach_voicing
  local n = #base
  local nv = {}
  for i = 1, n do nv[i] = base[i] end
  if prev then
    for i = 1, n do
      local nn = _keys_note[nv[i]]
      if nn then
        local npc = (nn - 60) % 12
        for j = 1, #prev do
          local pc = prev[j]
          local pn = _keys_note[pc]
          if pn and (pn - 60) % 12 == npc then
            nv[i] = pc
            break
          end
        end
      end
    end
  end
  state.keys_coach_voicing = nv
end
local function handle_keys(x, y, z)
  local note = _keys_note[x + y*W]
  if not note then return end
  if z == 1 then
    midi_note_on(note, 100, 1)
    state.keys_held[x + y*W] = true
  else
    midi_note_off(note, 0, 1)
    state.keys_held[x + y*W] = nil
    if next(state.keys_held) == nil then
      -- All keys released — user has finished this chord. Walk.
      if state.keys_scale_idx ~= 1 then
        local opts = _keys_next_chord[state.keys_coach_chord]
        if opts then
          state.keys_coach_chord = opts[math.random(1, #opts)]
        end
        _keys_revoice()
      end
    end
  end
end
local function handle_keys_picker(x, y, z)
  if z ~= 1 then return end
  local target = _keys_picker[x + y*W]
  if not target then return end
  if target == state.keys_scale_idx then return end
  state.keys_scale_idx = target
  state.keys_coach_chord = 1
  state.keys_coach_voicing = nil
  _keys_revoice()
end
local function _keys_pixel(k)
  if state.keys_held[k] then return 12 end
  local cv = state.keys_coach_voicing
  if cv and (cv[1] == k or cv[2] == k or cv[3] == k) then
    return state.keys_coach_blink == 0 and 13 or 6
  end
  local note = _keys_note[k]
  if not note then return 0 end
  local pc = (note - 60) % 12
  if pc == 0 then return 9 end
  if state.keys_scale_idx == 1 then return 4 end
  local member = _keys_scale_member[state.keys_scale_idx]
  return (member and member[pc]) and 4 or 0
end

local function _keys_blink_tick()
  state.keys_coach_blink = 1 - state.keys_coach_blink
  redraw()
end
local _keys_blink_metro = metro.init(_keys_blink_tick, 0.25)
_keys_blink_metro:start()

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: keys
  grid_led(1, 1, _keys_pixel(1 + 1*W))
  grid_led(2, 1, _keys_pixel(2 + 1*W))
  grid_led(3, 1, _keys_pixel(3 + 1*W))
  grid_led(4, 1, _keys_pixel(4 + 1*W))
  grid_led(1, 2, _keys_pixel(1 + 2*W))
  grid_led(2, 2, _keys_pixel(2 + 2*W))
  grid_led(3, 2, _keys_pixel(3 + 2*W))
  grid_led(4, 2, _keys_pixel(4 + 2*W))
  grid_led(1, 3, _keys_pixel(1 + 3*W))
  grid_led(2, 3, _keys_pixel(2 + 3*W))
  grid_led(3, 3, _keys_pixel(3 + 3*W))
  grid_led(4, 3, _keys_pixel(4 + 3*W))
  grid_led(1, 4, _keys_pixel(1 + 4*W))
  grid_led(2, 4, _keys_pixel(2 + 4*W))
  grid_led(3, 4, _keys_pixel(3 + 4*W))
  grid_led(4, 4, _keys_pixel(4 + 4*W))
  grid_led(1, 5, _keys_pixel(1 + 5*W))
  grid_led(2, 5, _keys_pixel(2 + 5*W))
  grid_led(3, 5, _keys_pixel(3 + 5*W))
  grid_led(4, 5, _keys_pixel(4 + 5*W))
  grid_led(1, 6, _keys_pixel(1 + 6*W))
  grid_led(2, 6, _keys_pixel(2 + 6*W))
  grid_led(3, 6, _keys_pixel(3 + 6*W))
  grid_led(4, 6, _keys_pixel(4 + 6*W))
  grid_led(1, 7, _keys_pixel(1 + 7*W))
  grid_led(2, 7, _keys_pixel(2 + 7*W))
  grid_led(3, 7, _keys_pixel(3 + 7*W))
  grid_led(4, 7, _keys_pixel(4 + 7*W))
  grid_led(1, 8, _keys_pixel(1 + 8*W))
  grid_led(2, 8, _keys_pixel(2 + 8*W))
  grid_led(3, 8, _keys_pixel(3 + 8*W))
  grid_led(4, 8, _keys_pixel(4 + 8*W))
  grid_led(5, 1, state.keys_scale_idx == 1 and 12 or 4)
  grid_led(5, 2, state.keys_scale_idx == 2 and 12 or 4)
  grid_led(5, 3, state.keys_scale_idx == 3 and 12 or 4)
  grid_led(5, 4, state.keys_scale_idx == 4 and 12 or 4)
  grid_led(5, 5, state.keys_scale_idx == 5 and 12 or 4)
  grid_led(5, 6, state.keys_scale_idx == 6 and 12 or 4)
  grid_led(5, 7, state.keys_scale_idx == 7 and 12 or 4)
  grid_led(5, 8, state.keys_scale_idx == 8 and 12 or 4)
end

-- ---- master redraw ----
redraw = function()
  _draw_p0()
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}

local _route_p0 = {}
_route_p0[1 + 1*W] = handle_keys
_route_p0[2 + 1*W] = handle_keys
_route_p0[3 + 1*W] = handle_keys
_route_p0[4 + 1*W] = handle_keys
_route_p0[1 + 2*W] = handle_keys
_route_p0[2 + 2*W] = handle_keys
_route_p0[3 + 2*W] = handle_keys
_route_p0[4 + 2*W] = handle_keys
_route_p0[1 + 3*W] = handle_keys
_route_p0[2 + 3*W] = handle_keys
_route_p0[3 + 3*W] = handle_keys
_route_p0[4 + 3*W] = handle_keys
_route_p0[1 + 4*W] = handle_keys
_route_p0[2 + 4*W] = handle_keys
_route_p0[3 + 4*W] = handle_keys
_route_p0[4 + 4*W] = handle_keys
_route_p0[1 + 5*W] = handle_keys
_route_p0[2 + 5*W] = handle_keys
_route_p0[3 + 5*W] = handle_keys
_route_p0[4 + 5*W] = handle_keys
_route_p0[1 + 6*W] = handle_keys
_route_p0[2 + 6*W] = handle_keys
_route_p0[3 + 6*W] = handle_keys
_route_p0[4 + 6*W] = handle_keys
_route_p0[1 + 7*W] = handle_keys
_route_p0[2 + 7*W] = handle_keys
_route_p0[3 + 7*W] = handle_keys
_route_p0[4 + 7*W] = handle_keys
_route_p0[1 + 8*W] = handle_keys
_route_p0[2 + 8*W] = handle_keys
_route_p0[3 + 8*W] = handle_keys
_route_p0[4 + 8*W] = handle_keys
_route_p0[5 + 1*W] = handle_keys_picker
_route_p0[5 + 2*W] = handle_keys_picker
_route_p0[5 + 3*W] = handle_keys_picker
_route_p0[5 + 4*W] = handle_keys_picker
_route_p0[5 + 5*W] = handle_keys_picker
_route_p0[5 + 6*W] = handle_keys_picker
_route_p0[5 + 7*W] = handle_keys_picker
_route_p0[5 + 8*W] = handle_keys_picker

local _routes = {[0]=_route_p0}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- init ----
grid_led_all(0)
math.randomseed(math.floor(get_time() * 1000))
_keys_revoice()
redraw()
