-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "keys" (128 cells, note keyboard per_cell, ch1 root MIDI 36 (row=5, col=1, major))
-- Upload: diii  →  first("test-nk-full16x8.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  keys_held = {},
  keys_scale_idx = 2,
  keys_coach_chord = 1,
  keys_coach_blink = 0,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: keys ----
local _keys_note = {}
for y = 1, 8 do
  for x = 1, 15 do
    _keys_note[x + y*W] = 36 + (8-y)*5 + (x-1)
  end
end
local _keys_scale_member = {
  {[0]=true,[1]=true,[2]=true,[3]=true,[4]=true,[5]=true,[6]=true,[7]=true,[8]=true,[9]=true,[10]=true,[11]=true},
  {[0]=true,[2]=true,[4]=true,[5]=true,[7]=true,[9]=true,[11]=true},
  {[0]=true,[2]=true,[3]=true,[5]=true,[7]=true,[8]=true,[10]=true},
  {[0]=true,[2]=true,[3]=true,[5]=true,[7]=true,[9]=true,[10]=true},
  {[0]=true,[1]=true,[3]=true,[5]=true,[7]=true,[8]=true,[10]=true},
  {[0]=true,[2]=true,[4]=true,[6]=true,[7]=true,[9]=true,[11]=true},
  {[0]=true,[2]=true,[4]=true,[5]=true,[7]=true,[9]=true,[10]=true},
  {[0]=true,[1]=true,[3]=true,[5]=true,[6]=true,[8]=true,[10]=true},
}
local _keys_picker = {}
for y = 1, 8 do
  _keys_picker[16 + y*W] = y
end
local _keys_chord_voicing = {
  {{},{},{},{},{},{},{}},
  {
    {{120,133,136,119},{99,82,85,68},{69,52,55,68},{39,22,55,38},{30,43,46,29}},
    {{131,113,117,129},{101,83,117,99},{50,83,66,69},{50,53,36,18},{62,44,27,30}},
    {{133,115,98,131},{82,85,98,101},{52,85,68,50},{52,34,17,20},{43,25,29,41}},
    {{113,117,129,133},{104,117,120,103},{83,66,69,52},{53,36,39,52},{44,27,30,43}},
    {{115,98,131,113},{85,98,101,83},{85,68,50,53},{55,38,20,53},{46,29,62,44}},
    {{117,129,133,115},{117,99,82,85},{66,69,52,85},{36,18,52,34},{27,30,43,46}},
    {{119,131,134,117},{98,101,83,66},{68,50,53,66},{38,20,53,36},{29,41,44,27}},
  },
  {
    {{129,132,115,97},{99,81,85,97},{69,51,85,67},{18,51,34,37},{30,42,46,28}},
    {{131,113,116,129},{101,83,116,99},{71,83,86,69},{50,53,35,18},{62,44,47,30}},
    {{132,115,118,131},{102,85,118,101},{72,85,88,71},{51,34,37,20},{42,25,28,41}},
    {{113,116,129,132},{83,116,99,81},{83,86,69,51},{53,35,18,51},{44,26,30,42}},
    {{115,97,131,113},{85,97,101,83},{85,67,50,53},{34,37,20,53},{25,28,41,44}},
    {{116,129,132,115},{116,99,102,85},{86,69,72,85},{35,18,51,34},{47,30,63,46}},
    {{118,131,134,116},{118,101,83,86},{67,50,53,65},{37,20,53,35},{28,41,44,26}},
  },
  {
    {{129,132,115,97},{99,81,85,97},{69,51,85,67},{18,51,34,37},{30,42,46,28}},
    {{131,113,117,129},{101,83,117,99},{50,83,66,69},{50,53,36,18},{62,44,27,30}},
    {{132,115,118,131},{102,85,118,101},{72,85,88,71},{51,34,37,20},{42,25,28,41}},
    {{113,117,129,132},{104,117,120,102},{83,66,69,51},{53,36,18,51},{44,27,30,42}},
    {{115,97,131,113},{85,97,101,83},{85,67,50,53},{34,37,20,53},{25,28,41,44}},
    {{117,129,132,115},{117,99,102,85},{87,69,72,85},{36,18,51,34},{27,30,42,46}},
    {{118,131,134,117},{118,101,104,87},{67,50,53,66},{37,20,53,36},{28,41,44,27}},
  },
  {
    {{129,132,115,97},{99,81,85,97},{69,51,85,67},{18,51,34,37},{30,42,46,28}},
    {{130,113,116,129},{100,83,116,99},{70,53,86,69},{40,53,56,39},{31,44,47,30}},
    {{132,115,97,130},{102,85,118,100},{72,85,88,70},{51,34,37,19},{63,46,28,31}},
    {{113,116,129,132},{83,116,99,81},{83,86,69,51},{53,35,18,51},{44,26,30,42}},
    {{115,97,130,113},{85,97,100,83},{85,67,70,53},{55,37,40,53},{46,28,31,44}},
    {{116,129,132,115},{116,99,102,85},{86,69,72,85},{35,18,51,34},{47,30,63,46}},
    {{97,130,113,116},{97,100,83,65},{67,49,53,65},{37,19,53,35},{28,31,44,47}},
  },
  {
    {{120,133,136,119},{99,82,85,68},{69,52,55,68},{39,22,55,38},{30,43,46,29}},
    {{131,114,117,129},{101,84,117,99},{71,84,87,69},{50,33,36,18},{62,45,27,30}},
    {{133,115,98,131},{82,85,98,101},{52,85,68,50},{52,34,17,20},{43,25,29,41}},
    {{114,117,129,133},{84,117,99,82},{84,66,69,52},{54,36,39,52},{45,27,30,43}},
    {{115,98,131,114},{85,98,101,84},{85,68,71,54},{34,17,20,33},{46,29,62,45}},
    {{117,129,133,115},{117,99,82,85},{66,69,52,85},{36,18,52,34},{27,30,43,46}},
    {{98,131,114,117},{98,101,84,66},{68,50,33,66},{17,20,33,36},{29,41,45,27}},
  },
  {
    {{129,133,115,97},{99,82,85,97},{69,52,85,67},{39,52,55,37},{30,43,46,28}},
    {{131,113,117,129},{101,83,117,99},{50,83,66,69},{50,53,36,18},{62,44,27,30}},
    {{133,115,118,131},{103,85,118,101},{52,85,67,50},{52,34,37,20},{43,25,28,41}},
    {{113,117,129,133},{104,117,120,103},{83,66,69,52},{53,36,39,52},{44,27,30,43}},
    {{115,97,131,113},{85,97,101,83},{85,67,50,53},{34,37,20,53},{25,28,41,44}},
    {{117,129,133,115},{117,99,82,85},{66,69,52,85},{36,18,52,34},{27,30,43,46}},
    {{118,131,134,117},{118,101,104,87},{67,50,53,66},{37,20,53,36},{28,41,44,27}},
  },
  {
    {{129,132,114,97},{99,81,84,97},{69,51,84,67},{39,51,54,37},{30,42,45,28}},
    {{130,113,116,129},{100,83,116,99},{70,53,86,69},{40,53,56,39},{31,44,47,30}},
    {{132,114,97,130},{81,84,97,100},{51,84,67,49},{51,54,37,19},{63,45,28,31}},
    {{113,116,129,132},{83,116,99,81},{83,86,69,51},{53,35,18,51},{44,26,30,42}},
    {{114,97,130,113},{84,97,100,83},{84,67,70,53},{54,37,40,53},{45,28,31,44}},
    {{116,129,132,114},{116,99,81,84},{86,69,51,84},{35,18,51,33},{47,30,63,45}},
    {{97,130,113,116},{97,100,83,65},{67,49,53,65},{37,19,53,35},{28,31,44,47}},
  },
}
local _keys_next_chord = {[1]={4,4,5,5,6,6,2,2,3},[2]={5,5,5,7},[3]={6,6,4,1},[4]={5,5,5,1,1,2,7},[5]={1,1,1,1,1,6},[6]={2,2,4,4,5},[7]={1,1,1,1,3}}
local function _keys_revoice()
  local vs = _keys_chord_voicing[state.keys_scale_idx][state.keys_coach_chord]
  if not vs or #vs == 0 then state.keys_coach_voicing = nil; return end
  local base = vs[math.random(1, #vs)]
  local prev = state.keys_coach_voicing
  local n = #base
  local nv = {}
  for i = 1, n do nv[i] = base[i] end
  if prev then
    for i = 1, n do
      local nn = _keys_note[nv[i]]
      if nn then
        local npc = (nn - 36) % 12
        for j = 1, #prev do
          local pc = prev[j]
          local pn = _keys_note[pc]
          if pn and (pn - 36) % 12 == npc then
            nv[i] = pc
            break
          end
        end
      end
    end
  end
  state.keys_coach_voicing = nv
end
local function handle_keys(x, y, z)
  local note = _keys_note[x + y*W]
  if not note then return end
  if z == 1 then
    midi_note_on(note, 100, 1)
    state.keys_held[x + y*W] = true
  else
    midi_note_off(note, 0, 1)
    state.keys_held[x + y*W] = nil
    if next(state.keys_held) == nil then
      -- All keys released — user has finished this chord. Walk.
      if state.keys_scale_idx ~= 1 then
        local opts = _keys_next_chord[state.keys_coach_chord]
        if opts then
          state.keys_coach_chord = opts[math.random(1, #opts)]
        end
        _keys_revoice()
      end
    end
  end
end
local function handle_keys_picker(x, y, z)
  if z ~= 1 then return end
  local target = _keys_picker[x + y*W]
  if not target then return end
  if target == state.keys_scale_idx then return end
  state.keys_scale_idx = target
  state.keys_coach_chord = 1
  state.keys_coach_voicing = nil
  _keys_revoice()
end
local function _keys_pixel(k)
  if state.keys_held[k] then return 12 end
  local cv = state.keys_coach_voicing
  if cv and (cv[1] == k or cv[2] == k or cv[3] == k or cv[4] == k) then
    return state.keys_coach_blink == 0 and 13 or 6
  end
  local note = _keys_note[k]
  if not note then return 0 end
  local pc = (note - 36) % 12
  if pc == 0 then return 9 end
  if state.keys_scale_idx == 1 then return 4 end
  local member = _keys_scale_member[state.keys_scale_idx]
  return (member and member[pc]) and 4 or 0
end

local function _keys_blink_tick()
  state.keys_coach_blink = 1 - state.keys_coach_blink
  redraw()
end
local _keys_blink_metro = metro.init(_keys_blink_tick, 0.25)
_keys_blink_metro:start()

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: keys
  for y = 1, 8 do
    for x = 1, 15 do
      grid_led(x, y, _keys_pixel(x + y*W))
    end
  end
  for y = 1, 8 do
    grid_led(16, y, state.keys_scale_idx == y and 12 or 4)
  end
end

-- ---- master redraw ----
redraw = function()
  _draw_p0()
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}

local _route_p0 = {}
for y = 1, 8 do
  for x = 1, 15 do
    _route_p0[x + y*W] = handle_keys
  end
end
for y = 1, 8 do
  _route_p0[16 + y*W] = handle_keys_picker
end

local _routes = {[0]=_route_p0}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- init ----
grid_led_all(0)
math.randomseed(math.floor(get_time() * 1000))
_keys_revoice()
redraw()
