-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "keys" (12 cells, note keyboard per_cell, ch1 root MIDI 60 (row=5, col=1))
-- Upload: diii  →  first("test-nk-highlight.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  keys_held = {},
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: keys ----
local _keys_note = {}
_keys_note[2 + 1*W] = 60
_keys_note[3 + 1*W] = 61
_keys_note[4 + 1*W] = 62
_keys_note[5 + 1*W] = 63
_keys_note[6 + 1*W] = 64
_keys_note[7 + 1*W] = 65
_keys_note[8 + 1*W] = 66
_keys_note[9 + 1*W] = 67
_keys_note[10 + 1*W] = 68
_keys_note[11 + 1*W] = 69
_keys_note[12 + 1*W] = 70
_keys_note[13 + 1*W] = 71
local function handle_keys(x, y, z)
  local note = _keys_note[x + y*W]
  if not note then return end
  if z == 1 then
    midi_note_on(note, 100, 1)
    state.keys_held[x + y*W] = true
  else
    midi_note_off(note, 0, 1)
    state.keys_held[x + y*W] = nil
  end
end

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: keys
  grid_led(2, 1, state.keys_held[2 + 1*W] and 15 or 9)
  grid_led(3, 1, state.keys_held[3 + 1*W] and 15 or 0)
  grid_led(4, 1, state.keys_held[4 + 1*W] and 15 or 4)
  grid_led(5, 1, state.keys_held[5 + 1*W] and 15 or 0)
  grid_led(6, 1, state.keys_held[6 + 1*W] and 15 or 4)
  grid_led(7, 1, state.keys_held[7 + 1*W] and 15 or 4)
  grid_led(8, 1, state.keys_held[8 + 1*W] and 15 or 0)
  grid_led(9, 1, state.keys_held[9 + 1*W] and 15 or 4)
  grid_led(10, 1, state.keys_held[10 + 1*W] and 15 or 0)
  grid_led(11, 1, state.keys_held[11 + 1*W] and 15 or 4)
  grid_led(12, 1, state.keys_held[12 + 1*W] and 15 or 0)
  grid_led(13, 1, state.keys_held[13 + 1*W] and 15 or 4)
end

-- ---- master redraw ----
redraw = function()
  _draw_p0()
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}

local _route_p0 = {}
_route_p0[2 + 1*W] = handle_keys
_route_p0[3 + 1*W] = handle_keys
_route_p0[4 + 1*W] = handle_keys
_route_p0[5 + 1*W] = handle_keys
_route_p0[6 + 1*W] = handle_keys
_route_p0[7 + 1*W] = handle_keys
_route_p0[8 + 1*W] = handle_keys
_route_p0[9 + 1*W] = handle_keys
_route_p0[10 + 1*W] = handle_keys
_route_p0[11 + 1*W] = handle_keys
_route_p0[12 + 1*W] = handle_keys
_route_p0[13 + 1*W] = handle_keys

local _routes = {[0]=_route_p0}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
