-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "keys" (16 cells, note keyboard per_cell, ch1 root MIDI 60 (row=5, col=1, major))
-- Upload: diii  →  first("test-nk-coach.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  keys_held = {},
  keys_coach_chord = 1,
  keys_coach_blink = 0,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: keys ----
local _keys_note = {}
_keys_note[1 + 5*W] = 75
_keys_note[2 + 5*W] = 76
_keys_note[3 + 5*W] = 77
_keys_note[4 + 5*W] = 78
_keys_note[1 + 6*W] = 70
_keys_note[2 + 6*W] = 71
_keys_note[3 + 6*W] = 72
_keys_note[4 + 6*W] = 73
_keys_note[1 + 7*W] = 65
_keys_note[2 + 7*W] = 66
_keys_note[3 + 7*W] = 67
_keys_note[4 + 7*W] = 68
_keys_note[1 + 8*W] = 60
_keys_note[2 + 8*W] = 61
_keys_note[3 + 8*W] = 62
_keys_note[4 + 8*W] = 63
local _keys_chord_voicing = {}
_keys_chord_voicing[1] = {{99, 82, 115}}
_keys_chord_voicing[2] = {{131, 113}}
_keys_chord_voicing[3] = {{82, 115, 98}}
_keys_chord_voicing[4] = {{113, 99}, {83, 99}, {113, 129}}
_keys_chord_voicing[5] = {{115, 98, 131}}
_keys_chord_voicing[6] = {{99, 82}}
_keys_chord_voicing[7] = {{98, 131, 113}}
local _keys_next_chord = {[1]={2, 3, 4, 5, 6, 7}, [2]={5, 7}, [3]={4, 6}, [4]={1, 5, 7}, [5]={1, 6}, [6]={2, 4, 5}, [7]={1, 3}}
local function _keys_revoice()
  local vs = _keys_chord_voicing[state.keys_coach_chord]
  if not vs or #vs == 0 then state.keys_coach_voicing = nil; return end
  local base = vs[math.random(1, #vs)]
  local prev = state.keys_coach_voicing
  local n = #base
  local nv = {}
  for i = 1, n do nv[i] = base[i] end
  if prev then
    for i = 1, n do
      local nn = _keys_note[nv[i]]
      if nn then
        local npc = (nn - 60) % 12
        for j = 1, #prev do
          local pc = prev[j]
          local pn = _keys_note[pc]
          if pn and (pn - 60) % 12 == npc then
            nv[i] = pc
            break
          end
        end
      end
    end
  end
  state.keys_coach_voicing = nv
end
local function handle_keys(x, y, z)
  local note = _keys_note[x + y*W]
  if not note then return end
  if z == 1 then
    midi_note_on(note, 100, 1)
    state.keys_held[x + y*W] = true
  else
    midi_note_off(note, 0, 1)
    state.keys_held[x + y*W] = nil
    if next(state.keys_held) == nil then
      -- All keys released — user has finished this chord. Walk.
      local opts = _keys_next_chord[state.keys_coach_chord]
      if opts then
        state.keys_coach_chord = opts[math.random(1, #opts)]
      end
      _keys_revoice()
    end
  end
end
local function _keys_pixel(k)
  if state.keys_held[k] then return 12 end
  local cv = state.keys_coach_voicing
  if cv and (cv[1] == k or cv[2] == k or cv[3] == k) then
    return state.keys_coach_blink == 0 and 13 or 6
  end
  local note = _keys_note[k]
  if not note then return 0 end
  local pc = (note - 60) % 12
  if pc == 0 then return 6 end
  local in_scale = {[0]=true, [2]=true, [4]=true, [5]=true, [7]=true, [9]=true, [11]=true}
  return in_scale[pc] and 3 or 0
end

local function _keys_blink_tick()
  state.keys_coach_blink = 1 - state.keys_coach_blink
  redraw()
end
local _keys_blink_metro = metro.init(_keys_blink_tick, 0.25)
_keys_blink_metro:start()

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: keys
  grid_led(1, 5, _keys_pixel(1 + 5*W))
  grid_led(2, 5, _keys_pixel(2 + 5*W))
  grid_led(3, 5, _keys_pixel(3 + 5*W))
  grid_led(4, 5, _keys_pixel(4 + 5*W))
  grid_led(1, 6, _keys_pixel(1 + 6*W))
  grid_led(2, 6, _keys_pixel(2 + 6*W))
  grid_led(3, 6, _keys_pixel(3 + 6*W))
  grid_led(4, 6, _keys_pixel(4 + 6*W))
  grid_led(1, 7, _keys_pixel(1 + 7*W))
  grid_led(2, 7, _keys_pixel(2 + 7*W))
  grid_led(3, 7, _keys_pixel(3 + 7*W))
  grid_led(4, 7, _keys_pixel(4 + 7*W))
  grid_led(1, 8, _keys_pixel(1 + 8*W))
  grid_led(2, 8, _keys_pixel(2 + 8*W))
  grid_led(3, 8, _keys_pixel(3 + 8*W))
  grid_led(4, 8, _keys_pixel(4 + 8*W))
end

-- ---- master redraw ----
redraw = function()
  _draw_p0()
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}

local _route_p0 = {}
_route_p0[1 + 5*W] = handle_keys
_route_p0[2 + 5*W] = handle_keys
_route_p0[3 + 5*W] = handle_keys
_route_p0[4 + 5*W] = handle_keys
_route_p0[1 + 6*W] = handle_keys
_route_p0[2 + 6*W] = handle_keys
_route_p0[3 + 6*W] = handle_keys
_route_p0[4 + 6*W] = handle_keys
_route_p0[1 + 7*W] = handle_keys
_route_p0[2 + 7*W] = handle_keys
_route_p0[3 + 7*W] = handle_keys
_route_p0[4 + 7*W] = handle_keys
_route_p0[1 + 8*W] = handle_keys
_route_p0[2 + 8*W] = handle_keys
_route_p0[3 + 8*W] = handle_keys
_route_p0[4 + 8*W] = handle_keys

local _routes = {[0]=_route_p0}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- init ----
grid_led_all(0)
math.randomseed(math.floor(get_time() * 1000))
_keys_revoice()
redraw()
