-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "keys" (40 cells, note keyboard per_cell, ch1 root MIDI 60 (row=5, col=1, major))
-- Upload: diii  →  first("test-nk-live-scale.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  keys_held = {},
  keys_scale_idx = 2,
  keys_coach_chord = 1,
  keys_coach_blink = 0,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: keys ----
local _keys_note = {}
for y = 1, 8 do
  for x = 1, 4 do
    _keys_note[x + y*W] = 60 + (8-y)*5 + (x-1)
  end
end
local _keys_scale_member = {
  {[0]=true,[1]=true,[2]=true,[3]=true,[4]=true,[5]=true,[6]=true,[7]=true,[8]=true,[9]=true,[10]=true,[11]=true},
  {[0]=true,[2]=true,[4]=true,[5]=true,[7]=true,[9]=true,[11]=true},
  {[0]=true,[2]=true,[3]=true,[5]=true,[7]=true,[8]=true,[10]=true},
  {[0]=true,[2]=true,[3]=true,[5]=true,[7]=true,[9]=true,[10]=true},
  {[0]=true,[1]=true,[3]=true,[5]=true,[7]=true,[8]=true,[10]=true},
  {[0]=true,[2]=true,[4]=true,[6]=true,[7]=true,[9]=true,[11]=true},
  {[0]=true,[2]=true,[4]=true,[5]=true,[7]=true,[9]=true,[10]=true},
  {[0]=true,[1]=true,[3]=true,[5]=true,[6]=true,[8]=true,[10]=true},
}
local _keys_picker = {}
for y = 1, 8 do
  _keys_picker[5 + y*W] = y
end
local _keys_chord_voicing = {
  {{},{},{},{},{},{},{}},
  {
    {{99,82,115},{18,52,34}},
    {{50,83,66}},
    {{82,115,98},{52,34,68},{52,34,17}},
    {{83,66,99}},
    {{115,98,131},{34,68,50},{34,17,50},{34,17,20}},
    {{66,99,82},{36,18,52}},
    {{98,131,113},{68,50,83}},
  },
  {
    {{129,132,115},{99,132,115},{99,81,115},{18,51,34}},
    {{131,113,116},{50,83,65}},
    {{132,115,97},{81,115,97},{51,34,67}},
    {{113,116,129},{113,116,99},{83,116,99},{83,65,99}},
    {{115,97,131},{34,67,50}},
    {{116,129,132},{116,99,132},{116,99,81},{65,99,81},{35,18,51}},
    {{97,131,113},{67,50,83}},
  },
  {
    {{129,132,115},{99,132,115},{99,81,115},{18,51,34}},
    {{50,83,66}},
    {{132,115,97},{81,115,97},{51,34,67}},
    {{83,66,99}},
    {{115,97,131},{34,67,50}},
    {{66,99,81},{36,18,51}},
    {{97,131,113},{67,50,83}},
  },
  {
    {{129,132,115},{99,132,115},{99,81,115},{18,51,34}},
    {{130,113,116},{100,113,116},{100,83,116},{100,83,65},{49,83,65}},
    {{132,115,97},{81,115,97},{51,34,67}},
    {{113,116,129},{113,116,99},{83,116,99},{83,65,99}},
    {{115,97,130},{115,97,100},{34,67,49}},
    {{116,129,132},{116,99,132},{116,99,81},{65,99,81},{35,18,51}},
    {{97,130,113},{97,100,113},{97,100,83},{67,100,83},{67,49,83}},
  },
  {
    {{99,82,115},{18,52,34}},
    {{50,84,66},{50,33,66},{50,33,36},{20,33,36}},
    {{82,115,98},{52,34,68},{52,34,17}},
    {{84,66,99},{33,36,18}},
    {{115,98,131},{34,68,50},{34,17,50},{34,17,20}},
    {{66,99,82},{36,18,52}},
    {{98,131,114},{68,50,84},{68,50,33},{17,50,33},{17,20,33}},
  },
  {
    {{99,82,115},{18,52,34}},
    {{50,83,66}},
    {{82,115,97},{52,34,67}},
    {{83,66,99}},
    {{115,97,131},{34,67,50}},
    {{66,99,82},{36,18,52}},
    {{97,131,113},{67,50,83}},
  },
  {
    {{129,132,114},{99,132,114},{99,81,114},{99,81,84},{18,51,33}},
    {{130,113,116},{100,113,116},{100,83,116},{100,83,65},{49,83,65}},
    {{132,114,97},{81,114,97},{81,84,97},{81,84,67},{51,33,67}},
    {{113,116,129},{113,116,99},{83,116,99},{83,65,99}},
    {{114,97,130},{114,97,100},{84,97,100},{84,67,100},{33,67,49}},
    {{116,129,132},{116,99,132},{116,99,81},{65,99,81},{35,18,51}},
    {{97,130,113},{97,100,113},{97,100,83},{67,100,83},{67,49,83}},
  },
}
local _keys_next_chord = {[1]={2,3,4,5,6,7},[2]={5,7},[3]={4,6},[4]={1,5,7},[5]={1,6},[6]={2,4,5},[7]={1,3}}
local function _keys_revoice()
  local vs = _keys_chord_voicing[state.keys_scale_idx][state.keys_coach_chord]
  if not vs or #vs == 0 then state.keys_coach_voicing = nil; return end
  local base = vs[math.random(1, #vs)]
  local prev = state.keys_coach_voicing
  local n = #base
  local nv = {}
  for i = 1, n do nv[i] = base[i] end
  if prev then
    for i = 1, n do
      local nn = _keys_note[nv[i]]
      if nn then
        local npc = (nn - 60) % 12
        for j = 1, #prev do
          local pc = prev[j]
          local pn = _keys_note[pc]
          if pn and (pn - 60) % 12 == npc then
            nv[i] = pc
            break
          end
        end
      end
    end
  end
  state.keys_coach_voicing = nv
end
local function handle_keys(x, y, z)
  local note = _keys_note[x + y*W]
  if not note then return end
  if z == 1 then
    midi_note_on(note, 100, 1)
    state.keys_held[x + y*W] = true
  else
    midi_note_off(note, 0, 1)
    state.keys_held[x + y*W] = nil
    if next(state.keys_held) == nil then
      -- All keys released — user has finished this chord. Walk.
      if state.keys_scale_idx ~= 1 then
        local opts = _keys_next_chord[state.keys_coach_chord]
        if opts then
          state.keys_coach_chord = opts[math.random(1, #opts)]
        end
        _keys_revoice()
      end
    end
  end
end
local function handle_keys_picker(x, y, z)
  if z ~= 1 then return end
  local target = _keys_picker[x + y*W]
  if not target then return end
  if target == state.keys_scale_idx then return end
  state.keys_scale_idx = target
  state.keys_coach_chord = 1
  state.keys_coach_voicing = nil
  _keys_revoice()
end
local function _keys_pixel(k)
  if state.keys_held[k] then return 12 end
  local cv = state.keys_coach_voicing
  if cv and (cv[1] == k or cv[2] == k or cv[3] == k) then
    return state.keys_coach_blink == 0 and 13 or 6
  end
  local note = _keys_note[k]
  if not note then return 0 end
  local pc = (note - 60) % 12
  if pc == 0 then return 9 end
  if state.keys_scale_idx == 1 then return 4 end
  local member = _keys_scale_member[state.keys_scale_idx]
  return (member and member[pc]) and 4 or 0
end

local function _keys_blink_tick()
  state.keys_coach_blink = 1 - state.keys_coach_blink
  redraw()
end
local _keys_blink_metro = metro.init(_keys_blink_tick, 0.25)
_keys_blink_metro:start()

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: keys
  for y = 1, 8 do
    for x = 1, 4 do
      grid_led(x, y, _keys_pixel(x + y*W))
    end
  end
  for y = 1, 8 do
    grid_led(5, y, state.keys_scale_idx == y and 12 or 4)
  end
end

-- ---- master redraw ----
redraw = function()
  _draw_p0()
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}

local _route_p0 = {}
for y = 1, 8 do
  for x = 1, 4 do
    _route_p0[x + y*W] = handle_keys
  end
end
for y = 1, 8 do
  _route_p0[5 + y*W] = handle_keys_picker
end

local _routes = {[0]=_route_p0}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- init ----
grid_led_all(0)
math.randomseed(math.floor(get_time() * 1000))
_keys_revoice()
redraw()
