-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "keys" (16 cells, note keyboard per_cell, ch1 root MIDI 36 (row=5, col=1))
-- Upload: diii  →  first("test-nk-fourths-4x4.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  keys_held = {},
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: keys ----
local _keys_note = {}
_keys_note[1 + 5*W] = 51
_keys_note[2 + 5*W] = 52
_keys_note[3 + 5*W] = 53
_keys_note[4 + 5*W] = 54
_keys_note[1 + 6*W] = 46
_keys_note[2 + 6*W] = 47
_keys_note[3 + 6*W] = 48
_keys_note[4 + 6*W] = 49
_keys_note[1 + 7*W] = 41
_keys_note[2 + 7*W] = 42
_keys_note[3 + 7*W] = 43
_keys_note[4 + 7*W] = 44
_keys_note[1 + 8*W] = 36
_keys_note[2 + 8*W] = 37
_keys_note[3 + 8*W] = 38
_keys_note[4 + 8*W] = 39

local function handle_keys(x, y, z)
  local note = _keys_note[x + y*W]
  if not note then return end
  if z == 1 then
    midi_note_on(note, 100, 1)
    state.keys_held[x + y*W] = true
  else
    midi_note_off(note, 0, 1)
    state.keys_held[x + y*W] = nil
  end
end

-- ---- LED draw ----
redraw = function()
  -- region: keys
  grid_led(1, 5, state.keys_held[1 + 5*W] and 12 or 3)
  grid_led(2, 5, state.keys_held[2 + 5*W] and 12 or 3)
  grid_led(3, 5, state.keys_held[3 + 5*W] and 12 or 3)
  grid_led(4, 5, state.keys_held[4 + 5*W] and 12 or 3)
  grid_led(1, 6, state.keys_held[1 + 6*W] and 12 or 3)
  grid_led(2, 6, state.keys_held[2 + 6*W] and 12 or 3)
  grid_led(3, 6, state.keys_held[3 + 6*W] and 12 or 6)
  grid_led(4, 6, state.keys_held[4 + 6*W] and 12 or 3)
  grid_led(1, 7, state.keys_held[1 + 7*W] and 12 or 3)
  grid_led(2, 7, state.keys_held[2 + 7*W] and 12 or 3)
  grid_led(3, 7, state.keys_held[3 + 7*W] and 12 or 3)
  grid_led(4, 7, state.keys_held[4 + 7*W] and 12 or 3)
  grid_led(1, 8, state.keys_held[1 + 8*W] and 12 or 6)
  grid_led(2, 8, state.keys_held[2 + 8*W] and 12 or 3)
  grid_led(3, 8, state.keys_held[3 + 8*W] and 12 or 3)
  grid_led(4, 8, state.keys_held[4 + 8*W] and 12 or 3)
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 5*W] = handle_keys
_route[2 + 5*W] = handle_keys
_route[3 + 5*W] = handle_keys
_route[4 + 5*W] = handle_keys
_route[1 + 6*W] = handle_keys
_route[2 + 6*W] = handle_keys
_route[3 + 6*W] = handle_keys
_route[4 + 6*W] = handle_keys
_route[1 + 7*W] = handle_keys
_route[2 + 7*W] = handle_keys
_route[3 + 7*W] = handle_keys
_route[4 + 7*W] = handle_keys
_route[1 + 8*W] = handle_keys
_route[2 + 8*W] = handle_keys
_route[3 + 8*W] = handle_keys
_route[4 + 8*W] = handle_keys

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
