-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "keys" (128 cells, note keyboard per_cell, ch1 root MIDI 36 (row=5, col=1, major))
-- Upload: diii  →  first("test-nk-full16x8.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  keys_held = {},
  keys_scale_idx = 2,
  keys_coach_chord = 1,
  keys_coach_blink = 0,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: keys ----
local _keys_note = {}
for y = 1, 8 do
  for x = 1, 15 do
    _keys_note[x + y*W] = 36 + (8-y)*5 + (x-1)
  end
end
local _keys_scale_member = {
  {[0]=true,[1]=true,[2]=true,[3]=true,[4]=true,[5]=true,[6]=true,[7]=true,[8]=true,[9]=true,[10]=true,[11]=true},
  {[0]=true,[2]=true,[4]=true,[5]=true,[7]=true,[9]=true,[11]=true},
  {[0]=true,[2]=true,[3]=true,[5]=true,[7]=true,[8]=true,[10]=true},
  {[0]=true,[2]=true,[3]=true,[5]=true,[7]=true,[9]=true,[10]=true},
  {[0]=true,[1]=true,[3]=true,[5]=true,[7]=true,[8]=true,[10]=true},
  {[0]=true,[2]=true,[4]=true,[6]=true,[7]=true,[9]=true,[11]=true},
  {[0]=true,[2]=true,[4]=true,[5]=true,[7]=true,[9]=true,[10]=true},
  {[0]=true,[1]=true,[3]=true,[5]=true,[6]=true,[8]=true,[10]=true},
}
local _keys_picker = {}
for y = 1, 8 do
  _keys_picker[16 + y*W] = y
end
local _keys_chord_voicing = {
  {{},{},{},{},{},{},{}},
  {
    {{129,133,115},{141,82,85},{69,94,106},{60,52,76},{30,22,46}},
    {{131,134,117},{101,125,87},{71,74,108},{62,95,78},{62,23,27}},
    {{133,136,119},{82,127,98},{94,85,68},{94,55,59},{22,46,29}},
    {{113,117,129},{104,108,99},{74,66,69},{53,57,39},{23,27,30}},
    {{115,98,131},{106,89,122},{127,110,50},{34,17,92},{46,29,20}},
    {{117,129,133},{66,99,124},{108,69,73},{57,39,52},{27,30,22}},
    {{98,131,113},{89,122,104},{110,50,125},{17,50,95},{29,20,44}},
  },
  {
    {{129,132,115},{141,81,127},{90,51,127},{18,93,34},{30,21,46}},
    {{131,113,116},{122,83,107},{92,53,86},{41,74,77},{20,44,47}},
    {{132,115,118},{123,106,109},{51,127,109},{51,34,79},{21,46,28}},
    {{113,116,129},{104,86,141},{95,86,90},{74,77,39},{23,47,30}},
    {{115,97,131},{85,88,101},{127,109,50},{34,79,50},{46,28,20}},
    {{116,129,132},{65,141,123},{65,111,93},{35,18,93},{47,30,21}},
    {{97,131,113},{88,101,104},{109,50,125},{58,50,95},{28,62,23}},
  },
  {
    {{129,132,115},{141,81,127},{90,51,127},{18,93,34},{30,21,46}},
    {{131,134,117},{101,125,87},{71,74,108},{62,95,78},{62,23,27}},
    {{132,115,118},{123,106,109},{51,127,109},{51,34,79},{21,46,28}},
    {{113,117,129},{104,108,99},{74,66,69},{53,57,39},{23,27,30}},
    {{115,97,131},{85,88,101},{127,109,50},{34,79,50},{46,28,20}},
    {{117,129,132},{66,141,123},{66,90,93},{36,60,72},{27,30,21}},
    {{97,131,113},{88,101,104},{109,50,125},{58,50,95},{28,62,23}},
  },
  {
    {{129,132,115},{141,81,127},{90,51,127},{18,93,34},{30,21,46}},
    {{130,113,116},{121,83,65},{91,95,86},{61,53,56},{31,23,47}},
    {{132,115,118},{123,106,109},{51,127,109},{51,34,79},{21,46,28}},
    {{113,116,129},{104,86,141},{95,86,90},{74,77,39},{23,47,30}},
    {{115,97,130},{106,88,121},{34,67,49},{34,79,91},{25,28,31}},
    {{116,129,132},{65,141,123},{65,111,93},{35,18,93},{47,30,21}},
    {{97,130,113},{88,121,104},{67,70,53},{37,49,95},{28,31,23}},
  },
  {
    {{129,133,115},{141,82,85},{69,94,106},{60,52,76},{30,22,46}},
    {{131,114,117},{122,84,108},{71,75,108},{41,54,57},{20,45,27}},
    {{133,136,119},{82,127,98},{94,85,68},{94,55,59},{22,46,29}},
    {{114,117,129},{84,108,99},{54,108,90},{75,57,60},{24,27,30}},
    {{115,98,131},{106,89,122},{127,110,50},{34,17,92},{46,29,20}},
    {{117,129,133},{66,99,124},{108,69,73},{57,39,52},{27,30,22}},
    {{98,131,114},{89,122,105},{110,50,126},{17,92,33},{29,20,45}},
  },
  {
    {{129,133,115},{141,82,85},{69,94,106},{60,52,76},{30,22,46}},
    {{131,134,117},{101,125,87},{71,74,108},{62,95,78},{62,23,27}},
    {{133,115,118},{124,127,97},{52,85,109},{73,55,79},{22,46,28}},
    {{113,117,129},{104,108,99},{74,66,69},{53,57,39},{23,27,30}},
    {{115,97,131},{85,88,101},{127,109,50},{34,79,50},{46,28,20}},
    {{117,129,133},{66,99,124},{108,69,73},{57,39,52},{27,30,22}},
    {{97,131,113},{88,101,104},{109,50,125},{58,50,95},{28,62,23}},
  },
  {
    {{129,132,114},{141,81,126},{111,51,105},{39,93,33},{30,21,45}},
    {{130,113,116},{121,83,65},{91,95,86},{61,53,56},{31,23,47}},
    {{132,135,118},{102,105,88},{51,126,109},{51,33,79},{63,24,28}},
    {{113,116,129},{104,86,141},{95,86,90},{74,77,39},{23,47,30}},
    {{114,97,130},{105,88,121},{33,67,49},{33,79,91},{24,28,31}},
    {{116,129,132},{65,141,123},{65,111,93},{35,18,93},{47,30,21}},
    {{97,130,113},{88,121,104},{67,70,53},{37,49,95},{28,31,23}},
  },
}
local _keys_next_chord = {[1]={2,3,4,5,6,7},[2]={5,7},[3]={4,6},[4]={1,5,7},[5]={1,6},[6]={2,4,5},[7]={1,3}}
local function _keys_revoice()
  local vs = _keys_chord_voicing[state.keys_scale_idx][state.keys_coach_chord]
  if not vs or #vs == 0 then state.keys_coach_voicing = nil; return end
  local base = vs[math.random(1, #vs)]
  local prev = state.keys_coach_voicing
  local n = #base
  local nv = {}
  for i = 1, n do nv[i] = base[i] end
  if prev then
    for i = 1, n do
      local nn = _keys_note[nv[i]]
      if nn then
        local npc = (nn - 36) % 12
        for j = 1, #prev do
          local pc = prev[j]
          local pn = _keys_note[pc]
          if pn and (pn - 36) % 12 == npc then
            nv[i] = pc
            break
          end
        end
      end
    end
  end
  state.keys_coach_voicing = nv
end
local function handle_keys(x, y, z)
  local note = _keys_note[x + y*W]
  if not note then return end
  if z == 1 then
    midi_note_on(note, 100, 1)
    state.keys_held[x + y*W] = true
  else
    midi_note_off(note, 0, 1)
    state.keys_held[x + y*W] = nil
    if next(state.keys_held) == nil then
      -- All keys released — user has finished this chord. Walk.
      if state.keys_scale_idx ~= 1 then
        local opts = _keys_next_chord[state.keys_coach_chord]
        if opts then
          state.keys_coach_chord = opts[math.random(1, #opts)]
        end
        _keys_revoice()
      end
    end
  end
end
local function handle_keys_picker(x, y, z)
  if z ~= 1 then return end
  local target = _keys_picker[x + y*W]
  if not target then return end
  if target == state.keys_scale_idx then return end
  state.keys_scale_idx = target
  state.keys_coach_chord = 1
  state.keys_coach_voicing = nil
  _keys_revoice()
end
local function _keys_pixel(k)
  if state.keys_held[k] then return 12 end
  local cv = state.keys_coach_voicing
  if cv and (cv[1] == k or cv[2] == k or cv[3] == k) then
    return state.keys_coach_blink == 0 and 13 or 6
  end
  local note = _keys_note[k]
  if not note then return 0 end
  local pc = (note - 36) % 12
  if pc == 0 then return 9 end
  if state.keys_scale_idx == 1 then return 4 end
  local member = _keys_scale_member[state.keys_scale_idx]
  return (member and member[pc]) and 4 or 0
end

local function _keys_blink_tick()
  state.keys_coach_blink = 1 - state.keys_coach_blink
  redraw()
end
local _keys_blink_metro = metro.init(_keys_blink_tick, 0.25)
_keys_blink_metro:start()

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: keys
  for y = 1, 8 do
    for x = 1, 15 do
      grid_led(x, y, _keys_pixel(x + y*W))
    end
  end
  for y = 1, 8 do
    grid_led(16, y, state.keys_scale_idx == y and 12 or 4)
  end
end

-- ---- master redraw ----
redraw = function()
  _draw_p0()
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}

local _route_p0 = {}
for y = 1, 8 do
  for x = 1, 15 do
    _route_p0[x + y*W] = handle_keys
  end
end
for y = 1, 8 do
  _route_p0[16 + y*W] = handle_keys_picker
end

local _routes = {[0]=_route_p0}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- init ----
grid_led_all(0)
math.randomseed(math.floor(get_time() * 1000))
_keys_revoice()
redraw()
