-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "monitor" (12 cells, note monitor group, ch1 notes 60..71)
-- Upload: diii  →  first("test-note-monitor.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  monitor_held = {[1]=0, [2]=0, [3]=0, [4]=0, [5]=0, [6]=0, [7]=0, [8]=0, [9]=0, [10]=0, [11]=0, [12]=0},
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: monitor (note_monitor) ----
local _monitor_note_map = {}
_monitor_note_map[60] = 1
_monitor_note_map[61] = 2
_monitor_note_map[62] = 3
_monitor_note_map[63] = 4
_monitor_note_map[64] = 5
_monitor_note_map[65] = 6
_monitor_note_map[66] = 7
_monitor_note_map[67] = 8
_monitor_note_map[68] = 9
_monitor_note_map[69] = 10
_monitor_note_map[70] = 11
_monitor_note_map[71] = 12

local function handle_midi_monitor(d1, d2, d3)
  if (d1 & 0x0f) ~= 0 then return end
  local status = d1 & 0xf0
  if status ~= 0x90 and status ~= 0x80 then return end
  local idx = _monitor_note_map[d2]
  if not idx then return end
  -- note_on with velocity 0 is a note-off in MIDI 1.0 wire
  -- protocol; treat it as such.
  if status == 0x80 or d3 == 0 then
    state.monitor_held[idx] = 0
  else
    state.monitor_held[idx] = d3
  end
end

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: monitor
  grid_led(1, 1, state.monitor_held[1] > 0 and 12 or 3)
  grid_led(2, 1, state.monitor_held[2] > 0 and 12 or 3)
  grid_led(3, 1, state.monitor_held[3] > 0 and 12 or 3)
  grid_led(4, 1, state.monitor_held[4] > 0 and 12 or 3)
  grid_led(5, 1, state.monitor_held[5] > 0 and 12 or 3)
  grid_led(6, 1, state.monitor_held[6] > 0 and 12 or 3)
  grid_led(7, 1, state.monitor_held[7] > 0 and 12 or 3)
  grid_led(8, 1, state.monitor_held[8] > 0 and 12 or 3)
  grid_led(9, 1, state.monitor_held[9] > 0 and 12 or 3)
  grid_led(10, 1, state.monitor_held[10] > 0 and 12 or 3)
  grid_led(11, 1, state.monitor_held[11] > 0 and 12 or 3)
  grid_led(12, 1, state.monitor_held[12] > 0 and 12 or 3)
end

-- ---- master redraw ----
redraw = function()
  _draw_p0()
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}

local _route_p0 = {}

local _routes = {[0]=_route_p0}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- MIDI input dispatch ----
-- iii calls event_midi(d1, d2, d3) on every incoming MIDI byte
-- triple. Fan out to each region that registered a handler;
-- redraw afterwards so any LED state mutations show up.
function event_midi(d1, d2, d3)
  handle_midi_monitor(d1, d2, d3)
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
