-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "keys" (8 cells, note keyboard per_cell, ch1 root MIDI 36 (row=1, col=1))
-- Upload: diii  →  first("test-nk-chromatic-row.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  keys_held = {},
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- region: keys ----
local _keys_note = {}
_keys_note[1 + 8*W] = 36
_keys_note[2 + 8*W] = 37
_keys_note[3 + 8*W] = 38
_keys_note[4 + 8*W] = 39
_keys_note[5 + 8*W] = 40
_keys_note[6 + 8*W] = 41
_keys_note[7 + 8*W] = 42
_keys_note[8 + 8*W] = 43

local function handle_keys(x, y, z)
  local note = _keys_note[x + y*W]
  if not note then return end
  if z == 1 then
    midi_note_on(note, 100, 1)
    state.keys_held[x + y*W] = true
  else
    midi_note_off(note, 0, 1)
    state.keys_held[x + y*W] = nil
  end
end

-- ---- LED draw ----
local function redraw()
  -- region: keys
  grid_led(1, 8, state.keys_held[1 + 8*W] and 12 or 6)
  grid_led(2, 8, state.keys_held[2 + 8*W] and 12 or 3)
  grid_led(3, 8, state.keys_held[3 + 8*W] and 12 or 3)
  grid_led(4, 8, state.keys_held[4 + 8*W] and 12 or 3)
  grid_led(5, 8, state.keys_held[5 + 8*W] and 12 or 3)
  grid_led(6, 8, state.keys_held[6 + 8*W] and 12 or 3)
  grid_led(7, 8, state.keys_held[7 + 8*W] and 12 or 3)
  grid_led(8, 8, state.keys_held[8 + 8*W] and 12 or 3)
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 8*W] = handle_keys
_route[2 + 8*W] = handle_keys
_route[3 + 8*W] = handle_keys
_route[4 + 8*W] = handle_keys
_route[5 + 8*W] = handle_keys
_route[6 + 8*W] = handle_keys
_route[7 + 8*W] = handle_keys
_route[8 + 8*W] = handle_keys

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
