-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 2 regions
--   page 1 "main":
--     - "selector" (4 cells, radio group, ch1 cc 30 → 0..127)
--     - "master" (8 cells, toggle group, ch1 cc 80)
-- Upload: diii  →  first("test-radio-mixed.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  selector_index = 2,
  master_on = false,
}

-- ---- region: selector ----
local _selector_idx = {}
_selector_idx[0 + 7*W] = 0
_selector_idx[1 + 7*W] = 1
_selector_idx[2 + 7*W] = 2
_selector_idx[3 + 7*W] = 3
local _selector_values = {[0]=0, [1]=42, [2]=84, [3]=127}

local function handle_selector(x, y, z)
  if z ~= 1 then return end
  state.selector_index = _selector_idx[x + y*W]
  midi_cc(30, _selector_values[state.selector_index], 1)
end

-- ---- region: master ----
local function handle_master(x, y, z)
  if z ~= 1 then return end
  state.master_on = not state.master_on
  midi_cc(80, state.master_on and 127 or 0, 1)
end

-- ---- LED draw ----
local function redraw()
  grid_led_all(0)
  -- region: selector
  grid_led(0, 7, state.selector_index == 0 and 15 or 3)
  grid_led(1, 7, state.selector_index == 1 and 15 or 3)
  grid_led(2, 7, state.selector_index == 2 and 15 or 3)
  grid_led(3, 7, state.selector_index == 3 and 15 or 3)
  -- region: master
  do
    local lit = state.master_on and 15 or 3
    grid_led(0, 0, lit)
    grid_led(1, 0, lit)
    grid_led(2, 0, lit)
    grid_led(3, 0, lit)
    grid_led(4, 0, lit)
    grid_led(5, 0, lit)
    grid_led(6, 0, lit)
    grid_led(7, 0, lit)
  end
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[0 + 7*W] = handle_selector
_route[1 + 7*W] = handle_selector
_route[2 + 7*W] = handle_selector
_route[3 + 7*W] = handle_selector
_route[0 + 0*W] = handle_master
_route[1 + 0*W] = handle_master
_route[2 + 0*W] = handle_master
_route[3 + 0*W] = handle_master
_route[4 + 0*W] = handle_master
_route[5 + 0*W] = handle_master
_route[6 + 0*W] = handle_master
_route[7 + 0*W] = handle_master

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
redraw()
