-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 2 regions
--   page 1 "main":
--     - "selector" (4 cells, radio group, ch1 cc 30 → 0..127)
--     - "master" (8 cells, toggle group, ch1 cc 80)
-- Upload: diii  →  first("test-radio-mixed.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  selector_index = 2,
  master_on = false,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: selector ----
local _selector_idx = {}
_selector_idx[1 + 8*W] = 0
_selector_idx[2 + 8*W] = 1
_selector_idx[3 + 8*W] = 2
_selector_idx[4 + 8*W] = 3
local _selector_values = {[0]=0, [1]=42, [2]=84, [3]=127}

local function handle_selector(x, y, z)
  if z ~= 1 then return end
  state.selector_index = _selector_idx[x + y*W]
  midi_cc(30, _selector_values[state.selector_index], 1)
end

-- ---- region: master ----
local function handle_master(x, y, z)
  if z ~= 1 then return end
  state.master_on = not state.master_on
  midi_cc(80, state.master_on and 127 or 0, 1)
end

-- ---- LED draw ----
redraw = function()
  -- region: selector
  grid_led(1, 8, state.selector_index == 0 and 15 or 3)
  grid_led(2, 8, state.selector_index == 1 and 15 or 3)
  grid_led(3, 8, state.selector_index == 2 and 15 or 3)
  grid_led(4, 8, state.selector_index == 3 and 15 or 3)
  -- region: master
  do
    local lit = state.master_on and 15 or 3
    grid_led(1, 1, lit)
    grid_led(2, 1, lit)
    grid_led(3, 1, lit)
    grid_led(4, 1, lit)
    grid_led(5, 1, lit)
    grid_led(6, 1, lit)
    grid_led(7, 1, lit)
    grid_led(8, 1, lit)
  end
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 8*W] = handle_selector
_route[2 + 8*W] = handle_selector
_route[3 + 8*W] = handle_selector
_route[4 + 8*W] = handle_selector
_route[1 + 1*W] = handle_master
_route[2 + 1*W] = handle_master
_route[3 + 1*W] = handle_master
_route[4 + 1*W] = handle_master
_route[5 + 1*W] = handle_master
_route[6 + 1*W] = handle_master
_route[7 + 1*W] = handle_master
_route[8 + 1*W] = handle_master

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
