-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 1 region
--   page 1 "main":
--     - "selector" (4 cells, radio group, ch1 cc 30 → 0..127)
-- Upload: diii  →  first("test-radio-4.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  selector_index = 0,
}

-- ---- region: selector ----
local _selector_idx = {}
_selector_idx[0 + 0*W] = 0
_selector_idx[1 + 0*W] = 1
_selector_idx[2 + 0*W] = 2
_selector_idx[3 + 0*W] = 3
local _selector_values = {[0]=0, [1]=42, [2]=84, [3]=127}

local function handle_selector(x, y, z)
  if z ~= 1 then return end
  state.selector_index = _selector_idx[x + y*W]
  midi_cc(30, _selector_values[state.selector_index], 1)
end

-- ---- LED draw ----
local function redraw()
  grid_led_all(0)
  -- region: selector
  grid_led(0, 0, state.selector_index == 0 and 15 or 3)
  grid_led(1, 0, state.selector_index == 1 and 15 or 3)
  grid_led(2, 0, state.selector_index == 2 and 15 or 3)
  grid_led(3, 0, state.selector_index == 3 and 15 or 3)
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[0 + 0*W] = handle_selector
_route[1 + 0*W] = handle_selector
_route[2 + 0*W] = handle_selector
_route[3 + 0*W] = handle_selector

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
redraw()
