-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 1 region
--   page 1 "main":
--     - "selector" (4 cells, radio group, ch1 cc 30 → 0..127)
-- Upload: diii  →  first("test-radio-4.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  selector_index = 0,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- region: selector ----
local _selector_idx = {}
_selector_idx[1 + 1*W] = 0
_selector_idx[2 + 1*W] = 1
_selector_idx[3 + 1*W] = 2
_selector_idx[4 + 1*W] = 3
local _selector_values = {[0]=0, [1]=42, [2]=84, [3]=127}

local function handle_selector(x, y, z)
  if z ~= 1 then return end
  state.selector_index = _selector_idx[x + y*W]
  midi_cc(30, _selector_values[state.selector_index], 1)
end

-- ---- LED draw ----
local function redraw()
  -- region: selector
  grid_led(1, 1, state.selector_index == 0 and 15 or 3)
  grid_led(2, 1, state.selector_index == 1 and 15 or 3)
  grid_led(3, 1, state.selector_index == 2 and 15 or 3)
  grid_led(4, 1, state.selector_index == 3 and 15 or 3)
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 1*W] = handle_selector
_route[2 + 1*W] = handle_selector
_route[3 + 1*W] = handle_selector
_route[4 + 1*W] = handle_selector

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
