-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 1 region
--   page 1 "main":
--     - "fader" (4 cells, range group, ch1 cc 40/41 → 0..127)
-- Upload: diii  →  first("test-range-4.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  fader_held = {},
  fader_count = 0,
  fader_lo = 0,
  fader_hi = 0,
  fader_set = false,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- region: fader ----
local _fader_idx = {}
_fader_idx[1 + 1*W] = 0
_fader_idx[2 + 1*W] = 1
_fader_idx[3 + 1*W] = 2
_fader_idx[4 + 1*W] = 3
local _fader_values = {[0]=0, [1]=42, [2]=84, [3]=127}

local function handle_fader(x, y, z)
  local idx = _fader_idx[x + y*W]
  if z == 1 then
    state.fader_held[idx] = true
    state.fader_count = state.fader_count + 1
    local lo, hi
    for i, _ in pairs(state.fader_held) do
      if not lo or i < lo then lo = i end
      if not hi or i > hi then hi = i end
    end
    state.fader_lo = lo
    state.fader_hi = hi
    state.fader_set = true
    midi_cc(40, _fader_values[lo], 1)
    midi_cc(41, _fader_values[hi], 1)
  else
    state.fader_held[idx] = nil
    state.fader_count = state.fader_count - 1
  end
end

-- ---- LED draw ----
local function redraw()
  -- region: fader
  do
    local set = state.fader_set
    local lo, hi = state.fader_lo, state.fader_hi
    grid_led(1, 1, set and lo <= 0 and 0 <= hi and 12 or 3)
    grid_led(2, 1, set and lo <= 1 and 1 <= hi and 12 or 3)
    grid_led(3, 1, set and lo <= 2 and 2 <= hi and 12 or 3)
    grid_led(4, 1, set and lo <= 3 and 3 <= hi and 12 or 3)
  end
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 1*W] = handle_fader
_route[2 + 1*W] = handle_fader
_route[3 + 1*W] = handle_fader
_route[4 + 1*W] = handle_fader

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
