-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 2 regions
--   page 1 "main":
--     - "notes" (8 cells, momentary per_cell, ch1 note from MIDI 36)
--     - "fader" (4 cells, range group, ch1 cc 40/41 → 0..127)
-- Upload: diii  →  first("test-range-mixed.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  notes_held = {},
  fader_held = {},
  fader_count = 0,
  fader_lo = 0,
  fader_hi = 0,
  fader_set = false,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: notes ----
local _notes_idx = {}
_notes_idx[1 + 8*W] = 0
_notes_idx[2 + 8*W] = 1
_notes_idx[3 + 8*W] = 2
_notes_idx[4 + 8*W] = 3
_notes_idx[5 + 8*W] = 4
_notes_idx[6 + 8*W] = 5
_notes_idx[7 + 8*W] = 6
_notes_idx[8 + 8*W] = 7

local function handle_notes(x, y, z)
  local idx = _notes_idx[x + y*W]
  if z == 1 then
    midi_note_on(36 + idx, 100, 1)
    state.notes_held[x + y*W] = true
  else
    midi_note_off(36 + idx, 0, 1)
    state.notes_held[x + y*W] = nil
  end
end

-- ---- region: fader ----
local _fader_idx = {}
_fader_idx[1 + 1*W] = 0
_fader_idx[2 + 1*W] = 1
_fader_idx[3 + 1*W] = 2
_fader_idx[4 + 1*W] = 3
local _fader_values = {[0]=0, [1]=42, [2]=84, [3]=127}

local function handle_fader(x, y, z)
  local idx = _fader_idx[x + y*W]
  if z == 1 then
    state.fader_held[idx] = true
    state.fader_count = state.fader_count + 1
    local lo, hi
    for i, _ in pairs(state.fader_held) do
      if not lo or i < lo then lo = i end
      if not hi or i > hi then hi = i end
    end
    state.fader_lo = lo
    state.fader_hi = hi
    state.fader_set = true
    midi_cc(40, _fader_values[lo], 1)
    midi_cc(41, _fader_values[hi], 1)
  else
    state.fader_held[idx] = nil
    state.fader_count = state.fader_count - 1
  end
end

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: notes
  grid_led(1, 8, state.notes_held[1 + 8*W] and 12 or 3)
  grid_led(2, 8, state.notes_held[2 + 8*W] and 12 or 3)
  grid_led(3, 8, state.notes_held[3 + 8*W] and 12 or 3)
  grid_led(4, 8, state.notes_held[4 + 8*W] and 12 or 3)
  grid_led(5, 8, state.notes_held[5 + 8*W] and 12 or 3)
  grid_led(6, 8, state.notes_held[6 + 8*W] and 12 or 3)
  grid_led(7, 8, state.notes_held[7 + 8*W] and 12 or 3)
  grid_led(8, 8, state.notes_held[8 + 8*W] and 12 or 3)
  -- region: fader
  do
    local set = state.fader_set
    local lo, hi = state.fader_lo, state.fader_hi
    grid_led(1, 1, set and lo <= 0 and 0 <= hi and 12 or 3)
    grid_led(2, 1, set and lo <= 1 and 1 <= hi and 12 or 3)
    grid_led(3, 1, set and lo <= 2 and 2 <= hi and 12 or 3)
    grid_led(4, 1, set and lo <= 3 and 3 <= hi and 12 or 3)
  end
end

-- ---- master redraw ----
redraw = function()
  _draw_p0()
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}

local _route_p0 = {}
_route_p0[1 + 8*W] = handle_notes
_route_p0[2 + 8*W] = handle_notes
_route_p0[3 + 8*W] = handle_notes
_route_p0[4 + 8*W] = handle_notes
_route_p0[5 + 8*W] = handle_notes
_route_p0[6 + 8*W] = handle_notes
_route_p0[7 + 8*W] = handle_notes
_route_p0[8 + 8*W] = handle_notes
_route_p0[1 + 1*W] = handle_fader
_route_p0[2 + 1*W] = handle_fader
_route_p0[3 + 1*W] = handle_fader
_route_p0[4 + 1*W] = handle_fader

local _routes = {[0]=_route_p0}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
