-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 2 regions
--   page 1 "main":
--     - "notes" (8 cells, momentary per_cell, ch1 note from MIDI 36)
--     - "fader" (4 cells, range group, ch1 cc 40/41 → 0..127)
-- Upload: diii  →  first("test-range-mixed.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  notes_held = {},
  fader_held = {},
  fader_count = 0,
  fader_lo = 0,
  fader_hi = 0,
  fader_set = false,
}

-- ---- region: notes ----
local _notes_idx = {}
_notes_idx[0 + 7*W] = 0
_notes_idx[1 + 7*W] = 1
_notes_idx[2 + 7*W] = 2
_notes_idx[3 + 7*W] = 3
_notes_idx[4 + 7*W] = 4
_notes_idx[5 + 7*W] = 5
_notes_idx[6 + 7*W] = 6
_notes_idx[7 + 7*W] = 7

local function handle_notes(x, y, z)
  local idx = _notes_idx[x + y*W]
  if z == 1 then
    midi_note_on(36 + idx, 100, 1)
    state.notes_held[x + y*W] = true
  else
    midi_note_off(36 + idx, 0, 1)
    state.notes_held[x + y*W] = nil
  end
end

-- ---- region: fader ----
local _fader_idx = {}
_fader_idx[0 + 0*W] = 0
_fader_idx[1 + 0*W] = 1
_fader_idx[2 + 0*W] = 2
_fader_idx[3 + 0*W] = 3
local _fader_values = {[0]=0, [1]=42, [2]=84, [3]=127}

local function handle_fader(x, y, z)
  local idx = _fader_idx[x + y*W]
  if z == 1 then
    state.fader_held[idx] = true
    state.fader_count = state.fader_count + 1
    local lo, hi
    for i, _ in pairs(state.fader_held) do
      if not lo or i < lo then lo = i end
      if not hi or i > hi then hi = i end
    end
    state.fader_lo = lo
    state.fader_hi = hi
    state.fader_set = true
    midi_cc(40, _fader_values[lo], 1)
    midi_cc(41, _fader_values[hi], 1)
  else
    state.fader_held[idx] = nil
    state.fader_count = state.fader_count - 1
  end
end

-- ---- LED draw ----
local function redraw()
  grid_led_all(0)
  -- region: notes
  grid_led(0, 7, state.notes_held[0 + 7*W] and 12 or 3)
  grid_led(1, 7, state.notes_held[1 + 7*W] and 12 or 3)
  grid_led(2, 7, state.notes_held[2 + 7*W] and 12 or 3)
  grid_led(3, 7, state.notes_held[3 + 7*W] and 12 or 3)
  grid_led(4, 7, state.notes_held[4 + 7*W] and 12 or 3)
  grid_led(5, 7, state.notes_held[5 + 7*W] and 12 or 3)
  grid_led(6, 7, state.notes_held[6 + 7*W] and 12 or 3)
  grid_led(7, 7, state.notes_held[7 + 7*W] and 12 or 3)
  -- region: fader
  do
    local set = state.fader_set
    local lo, hi = state.fader_lo, state.fader_hi
    grid_led(0, 0, set and lo <= 0 and 0 <= hi and 12 or 3)
    grid_led(1, 0, set and lo <= 1 and 1 <= hi and 12 or 3)
    grid_led(2, 0, set and lo <= 2 and 2 <= hi and 12 or 3)
    grid_led(3, 0, set and lo <= 3 and 3 <= hi and 12 or 3)
  end
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[0 + 7*W] = handle_notes
_route[1 + 7*W] = handle_notes
_route[2 + 7*W] = handle_notes
_route[3 + 7*W] = handle_notes
_route[4 + 7*W] = handle_notes
_route[5 + 7*W] = handle_notes
_route[6 + 7*W] = handle_notes
_route[7 + 7*W] = handle_notes
_route[0 + 0*W] = handle_fader
_route[1 + 0*W] = handle_fader
_route[2 + 0*W] = handle_fader
_route[3 + 0*W] = handle_fader

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
redraw()
