-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "drum" (8 cells, step seq group, 1×8, ch1 note from 36, 120 BPM @ 1/4)
-- Upload: diii  →  first("test-stepseq-drum-row.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  drum_step = {[0]=-1},
  drum_on = {[0]={}},
  drum_gate = {[0]=0},
  drum_dir = {[0]=1},
  drum_tick = {[0]=1},
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: drum ----
local _drum_row = {}
_drum_row[1 + 8*W] = 0
_drum_row[2 + 8*W] = 0
_drum_row[3 + 8*W] = 0
_drum_row[4 + 8*W] = 0
_drum_row[5 + 8*W] = 0
_drum_row[6 + 8*W] = 0
_drum_row[7 + 8*W] = 0
_drum_row[8 + 8*W] = 0
local _drum_col = {}
_drum_col[1 + 8*W] = 0
_drum_col[2 + 8*W] = 1
_drum_col[3 + 8*W] = 2
_drum_col[4 + 8*W] = 3
_drum_col[5 + 8*W] = 4
_drum_col[6 + 8*W] = 5
_drum_col[7 + 8*W] = 6
_drum_col[8 + 8*W] = 7
local _drum_notes = {[0]=36}
local _drum_divs = {[0]=1}

local function _drum_tick()
  -- master tick: each row independently checks gate + advances on its own div
  for r = 0, 0 do
    -- 1. tick the row's gate (open notes); close any that just expired
    if state.drum_gate[r] > 0 then
      state.drum_gate[r] = state.drum_gate[r] - 1
      if state.drum_gate[r] == 0 then
        midi_note_off(_drum_notes[r], 0, 1)
      end
    end
    -- 2. tick the row's div countdown; advance + fire only when it hits 0
    state.drum_tick[r] = state.drum_tick[r] - 1
    if state.drum_tick[r] <= 0 then
      state.drum_tick[r] = _drum_divs[r]
      state.drum_step[r] = (state.drum_step[r] + 1) % 8
      if state.drum_on[r][state.drum_step[r]] then
        if state.drum_gate[r] > 0 then
          midi_note_off(_drum_notes[r], 0, 1)
        end
        midi_note_on(_drum_notes[r], 100, 1)
        state.drum_gate[r] = 1
      end
    end
  end
  -- repaint so each row's playhead is visible
  redraw()
end

local function handle_drum(x, y, z)
  if z ~= 1 then return end
  local r = _drum_row[x + y*W]
  local c = _drum_col[x + y*W]
  state.drum_on[r][c] = not state.drum_on[r][c]
end

local function _drum_pixel(row, col)
  local is_step = col == state.drum_step[row]
  local is_on = state.drum_on[row][col]
  if is_step then
    return is_on and 15 or 8
  else
    return is_on and 5 or 2
  end
end

local _drum_metro = metro.init(_drum_tick, 0.125)
_drum_metro:start()

-- ---- LED draw ----
redraw = function()
  -- region: drum
  grid_led(1, 8, _drum_pixel(0, 0))
  grid_led(2, 8, _drum_pixel(0, 1))
  grid_led(3, 8, _drum_pixel(0, 2))
  grid_led(4, 8, _drum_pixel(0, 3))
  grid_led(5, 8, _drum_pixel(0, 4))
  grid_led(6, 8, _drum_pixel(0, 5))
  grid_led(7, 8, _drum_pixel(0, 6))
  grid_led(8, 8, _drum_pixel(0, 7))
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 8*W] = handle_drum
_route[2 + 8*W] = handle_drum
_route[3 + 8*W] = handle_drum
_route[4 + 8*W] = handle_drum
_route[5 + 8*W] = handle_drum
_route[6 + 8*W] = handle_drum
_route[7 + 8*W] = handle_drum
_route[8 + 8*W] = handle_drum

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
