-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "mono" (32 cells, step seq group, 4×8, ch1 note from 60 major, 120 BPM @ 1/4, mono)
-- Upload: diii  →  first("test-stepseq-mono.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  mono_step = {[0]=-1, [1]=-1, [2]=-1, [3]=-1},
  mono_on = {[0]={}, [1]={}, [2]={}, [3]={}},
  mono_dir = {[0]=1, [1]=1, [2]=1, [3]=1},
  mono_tick = {[0]=1, [1]=1, [2]=1, [3]=1},
  mono_active_row = -1,
  mono_active_gate = 0,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: mono ----
local _mono_row = {}
_mono_row[1 + 5*W] = 0
_mono_row[2 + 5*W] = 0
_mono_row[3 + 5*W] = 0
_mono_row[4 + 5*W] = 0
_mono_row[5 + 5*W] = 0
_mono_row[6 + 5*W] = 0
_mono_row[7 + 5*W] = 0
_mono_row[8 + 5*W] = 0
_mono_row[1 + 6*W] = 1
_mono_row[2 + 6*W] = 1
_mono_row[3 + 6*W] = 1
_mono_row[4 + 6*W] = 1
_mono_row[5 + 6*W] = 1
_mono_row[6 + 6*W] = 1
_mono_row[7 + 6*W] = 1
_mono_row[8 + 6*W] = 1
_mono_row[1 + 7*W] = 2
_mono_row[2 + 7*W] = 2
_mono_row[3 + 7*W] = 2
_mono_row[4 + 7*W] = 2
_mono_row[5 + 7*W] = 2
_mono_row[6 + 7*W] = 2
_mono_row[7 + 7*W] = 2
_mono_row[8 + 7*W] = 2
_mono_row[1 + 8*W] = 3
_mono_row[2 + 8*W] = 3
_mono_row[3 + 8*W] = 3
_mono_row[4 + 8*W] = 3
_mono_row[5 + 8*W] = 3
_mono_row[6 + 8*W] = 3
_mono_row[7 + 8*W] = 3
_mono_row[8 + 8*W] = 3
local _mono_col = {}
_mono_col[1 + 5*W] = 0
_mono_col[2 + 5*W] = 1
_mono_col[3 + 5*W] = 2
_mono_col[4 + 5*W] = 3
_mono_col[5 + 5*W] = 4
_mono_col[6 + 5*W] = 5
_mono_col[7 + 5*W] = 6
_mono_col[8 + 5*W] = 7
_mono_col[1 + 6*W] = 0
_mono_col[2 + 6*W] = 1
_mono_col[3 + 6*W] = 2
_mono_col[4 + 6*W] = 3
_mono_col[5 + 6*W] = 4
_mono_col[6 + 6*W] = 5
_mono_col[7 + 6*W] = 6
_mono_col[8 + 6*W] = 7
_mono_col[1 + 7*W] = 0
_mono_col[2 + 7*W] = 1
_mono_col[3 + 7*W] = 2
_mono_col[4 + 7*W] = 3
_mono_col[5 + 7*W] = 4
_mono_col[6 + 7*W] = 5
_mono_col[7 + 7*W] = 6
_mono_col[8 + 7*W] = 7
_mono_col[1 + 8*W] = 0
_mono_col[2 + 8*W] = 1
_mono_col[3 + 8*W] = 2
_mono_col[4 + 8*W] = 3
_mono_col[5 + 8*W] = 4
_mono_col[6 + 8*W] = 5
_mono_col[7 + 8*W] = 6
_mono_col[8 + 8*W] = 7
local _mono_notes = {[0]=65, [1]=64, [2]=62, [3]=60}
local _mono_divs = {[0]=1, [1]=1, [2]=1, [3]=1}

local function _mono_tick()
  -- master tick (mono): one active voice; later firings steal it
  -- 1. tick the shared active gate; close the voice when it expires
  if state.mono_active_gate > 0 then
    state.mono_active_gate = state.mono_active_gate - 1
    if state.mono_active_gate == 0 then
      midi_note_off(_mono_notes[state.mono_active_row], 0, 1)
      state.mono_active_row = -1
    end
  end
  -- 2. each row checks its div countdown; whichever row hits last in this tick wins the voice
  for r = 0, 3 do
    state.mono_tick[r] = state.mono_tick[r] - 1
    if state.mono_tick[r] <= 0 then
      state.mono_tick[r] = _mono_divs[r]
      state.mono_step[r] = (state.mono_step[r] + 1) % 8
      if state.mono_on[r][state.mono_step[r]] then
        if state.mono_active_row >= 0 then
          midi_note_off(_mono_notes[state.mono_active_row], 0, 1)
        end
        midi_note_on(_mono_notes[r], 100, 1)
        state.mono_active_row = r
        state.mono_active_gate = 1
      end
    end
  end
  redraw()
end

local function handle_mono(x, y, z)
  if z ~= 1 then return end
  local r = _mono_row[x + y*W]
  local c = _mono_col[x + y*W]
  state.mono_on[r][c] = not state.mono_on[r][c]
end

local function _mono_pixel(row, col)
  local is_step = col == state.mono_step[row]
  local is_on = state.mono_on[row][col]
  if is_step then
    return is_on and 15 or 8
  else
    return is_on and 5 or 2
  end
end

local _mono_metro = metro.init(_mono_tick, 0.125)
_mono_metro:start()

-- ---- LED draw ----
redraw = function()
  -- region: mono
  grid_led(1, 5, _mono_pixel(0, 0))
  grid_led(2, 5, _mono_pixel(0, 1))
  grid_led(3, 5, _mono_pixel(0, 2))
  grid_led(4, 5, _mono_pixel(0, 3))
  grid_led(5, 5, _mono_pixel(0, 4))
  grid_led(6, 5, _mono_pixel(0, 5))
  grid_led(7, 5, _mono_pixel(0, 6))
  grid_led(8, 5, _mono_pixel(0, 7))
  grid_led(1, 6, _mono_pixel(1, 0))
  grid_led(2, 6, _mono_pixel(1, 1))
  grid_led(3, 6, _mono_pixel(1, 2))
  grid_led(4, 6, _mono_pixel(1, 3))
  grid_led(5, 6, _mono_pixel(1, 4))
  grid_led(6, 6, _mono_pixel(1, 5))
  grid_led(7, 6, _mono_pixel(1, 6))
  grid_led(8, 6, _mono_pixel(1, 7))
  grid_led(1, 7, _mono_pixel(2, 0))
  grid_led(2, 7, _mono_pixel(2, 1))
  grid_led(3, 7, _mono_pixel(2, 2))
  grid_led(4, 7, _mono_pixel(2, 3))
  grid_led(5, 7, _mono_pixel(2, 4))
  grid_led(6, 7, _mono_pixel(2, 5))
  grid_led(7, 7, _mono_pixel(2, 6))
  grid_led(8, 7, _mono_pixel(2, 7))
  grid_led(1, 8, _mono_pixel(3, 0))
  grid_led(2, 8, _mono_pixel(3, 1))
  grid_led(3, 8, _mono_pixel(3, 2))
  grid_led(4, 8, _mono_pixel(3, 3))
  grid_led(5, 8, _mono_pixel(3, 4))
  grid_led(6, 8, _mono_pixel(3, 5))
  grid_led(7, 8, _mono_pixel(3, 6))
  grid_led(8, 8, _mono_pixel(3, 7))
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 5*W] = handle_mono
_route[2 + 5*W] = handle_mono
_route[3 + 5*W] = handle_mono
_route[4 + 5*W] = handle_mono
_route[5 + 5*W] = handle_mono
_route[6 + 5*W] = handle_mono
_route[7 + 5*W] = handle_mono
_route[8 + 5*W] = handle_mono
_route[1 + 6*W] = handle_mono
_route[2 + 6*W] = handle_mono
_route[3 + 6*W] = handle_mono
_route[4 + 6*W] = handle_mono
_route[5 + 6*W] = handle_mono
_route[6 + 6*W] = handle_mono
_route[7 + 6*W] = handle_mono
_route[8 + 6*W] = handle_mono
_route[1 + 7*W] = handle_mono
_route[2 + 7*W] = handle_mono
_route[3 + 7*W] = handle_mono
_route[4 + 7*W] = handle_mono
_route[5 + 7*W] = handle_mono
_route[6 + 7*W] = handle_mono
_route[7 + 7*W] = handle_mono
_route[8 + 7*W] = handle_mono
_route[1 + 8*W] = handle_mono
_route[2 + 8*W] = handle_mono
_route[3 + 8*W] = handle_mono
_route[4 + 8*W] = handle_mono
_route[5 + 8*W] = handle_mono
_route[6 + 8*W] = handle_mono
_route[7 + 8*W] = handle_mono
_route[8 + 8*W] = handle_mono

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
