-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "drum" (8 cells, step seq group, 1×8, ch1 note from 36, 120 BPM @ 1/4)
-- Upload: diii  →  first("test-stepseq-drum-row.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  drum_step = -1,
  drum_on = {[0]={}},
}

-- ---- region: drum ----
local _drum_row = {}
_drum_row[1 + 8*W] = 0
_drum_row[2 + 8*W] = 0
_drum_row[3 + 8*W] = 0
_drum_row[4 + 8*W] = 0
_drum_row[5 + 8*W] = 0
_drum_row[6 + 8*W] = 0
_drum_row[7 + 8*W] = 0
_drum_row[8 + 8*W] = 0
local _drum_col = {}
_drum_col[1 + 8*W] = 0
_drum_col[2 + 8*W] = 1
_drum_col[3 + 8*W] = 2
_drum_col[4 + 8*W] = 3
_drum_col[5 + 8*W] = 4
_drum_col[6 + 8*W] = 5
_drum_col[7 + 8*W] = 6
_drum_col[8 + 8*W] = 7
local _drum_notes = {[0]=36}

local function _drum_tick()
  -- close out the step we are leaving (gate-style)
  local leaving = state.drum_step
  if leaving >= 0 then
    for r = 0, 0 do
      if state.drum_on[r][leaving] then
        midi_note_off(_drum_notes[r], 0, 1)
      end
    end
  end
  -- advance playhead
  state.drum_step = (state.drum_step + 1) % 8
  -- open up the new step
  for r = 0, 0 do
    if state.drum_on[r][state.drum_step] then
      midi_note_on(_drum_notes[r], 100, 1)
    end
  end
end

local function handle_drum(x, y, z)
  if z ~= 1 then return end
  local r = _drum_row[x + y*W]
  local c = _drum_col[x + y*W]
  state.drum_on[r][c] = not state.drum_on[r][c]
end

local function _drum_pixel(row, col)
  local is_step = col == state.drum_step
  local is_on = state.drum_on[row][col]
  if is_step then
    return is_on and 15 or 8
  else
    return is_on and 5 or 2
  end
end

local _drum_metro = metro.init(_drum_tick, 0.125)
_drum_metro:start()

-- ---- LED draw ----
local function redraw()
  grid_led_all(0)
  -- region: drum
  grid_led(1, 8, _drum_pixel(0, 0))
  grid_led(2, 8, _drum_pixel(0, 1))
  grid_led(3, 8, _drum_pixel(0, 2))
  grid_led(4, 8, _drum_pixel(0, 3))
  grid_led(5, 8, _drum_pixel(0, 4))
  grid_led(6, 8, _drum_pixel(0, 5))
  grid_led(7, 8, _drum_pixel(0, 6))
  grid_led(8, 8, _drum_pixel(0, 7))
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 8*W] = handle_drum
_route[2 + 8*W] = handle_drum
_route[3 + 8*W] = handle_drum
_route[4 + 8*W] = handle_drum
_route[5 + 8*W] = handle_drum
_route[6 + 8*W] = handle_drum
_route[7 + 8*W] = handle_drum
_route[8 + 8*W] = handle_drum

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
redraw()
