-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "tracks" (32 cells, step seq group, 4×8, ch1 note from 36, 120 BPM @ 1/4)
-- Upload: diii  →  first("test-stepseq-4tracks.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  tracks_step = {[0]=-1, [1]=-1, [2]=-1, [3]=-1},
  tracks_on = {[0]={}, [1]={}, [2]={}, [3]={}},
  tracks_gate = {[0]=0, [1]=0, [2]=0, [3]=0},
  tracks_dir = {[0]=1, [1]=1, [2]=1, [3]=1},
  tracks_tick = {[0]=1, [1]=1, [2]=1, [3]=1},
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: tracks ----
local _tracks_row = {}
_tracks_row[1 + 5*W] = 0
_tracks_row[2 + 5*W] = 0
_tracks_row[3 + 5*W] = 0
_tracks_row[4 + 5*W] = 0
_tracks_row[5 + 5*W] = 0
_tracks_row[6 + 5*W] = 0
_tracks_row[7 + 5*W] = 0
_tracks_row[8 + 5*W] = 0
_tracks_row[1 + 6*W] = 1
_tracks_row[2 + 6*W] = 1
_tracks_row[3 + 6*W] = 1
_tracks_row[4 + 6*W] = 1
_tracks_row[5 + 6*W] = 1
_tracks_row[6 + 6*W] = 1
_tracks_row[7 + 6*W] = 1
_tracks_row[8 + 6*W] = 1
_tracks_row[1 + 7*W] = 2
_tracks_row[2 + 7*W] = 2
_tracks_row[3 + 7*W] = 2
_tracks_row[4 + 7*W] = 2
_tracks_row[5 + 7*W] = 2
_tracks_row[6 + 7*W] = 2
_tracks_row[7 + 7*W] = 2
_tracks_row[8 + 7*W] = 2
_tracks_row[1 + 8*W] = 3
_tracks_row[2 + 8*W] = 3
_tracks_row[3 + 8*W] = 3
_tracks_row[4 + 8*W] = 3
_tracks_row[5 + 8*W] = 3
_tracks_row[6 + 8*W] = 3
_tracks_row[7 + 8*W] = 3
_tracks_row[8 + 8*W] = 3
local _tracks_col = {}
_tracks_col[1 + 5*W] = 0
_tracks_col[2 + 5*W] = 1
_tracks_col[3 + 5*W] = 2
_tracks_col[4 + 5*W] = 3
_tracks_col[5 + 5*W] = 4
_tracks_col[6 + 5*W] = 5
_tracks_col[7 + 5*W] = 6
_tracks_col[8 + 5*W] = 7
_tracks_col[1 + 6*W] = 0
_tracks_col[2 + 6*W] = 1
_tracks_col[3 + 6*W] = 2
_tracks_col[4 + 6*W] = 3
_tracks_col[5 + 6*W] = 4
_tracks_col[6 + 6*W] = 5
_tracks_col[7 + 6*W] = 6
_tracks_col[8 + 6*W] = 7
_tracks_col[1 + 7*W] = 0
_tracks_col[2 + 7*W] = 1
_tracks_col[3 + 7*W] = 2
_tracks_col[4 + 7*W] = 3
_tracks_col[5 + 7*W] = 4
_tracks_col[6 + 7*W] = 5
_tracks_col[7 + 7*W] = 6
_tracks_col[8 + 7*W] = 7
_tracks_col[1 + 8*W] = 0
_tracks_col[2 + 8*W] = 1
_tracks_col[3 + 8*W] = 2
_tracks_col[4 + 8*W] = 3
_tracks_col[5 + 8*W] = 4
_tracks_col[6 + 8*W] = 5
_tracks_col[7 + 8*W] = 6
_tracks_col[8 + 8*W] = 7
local _tracks_notes = {[0]=39, [1]=38, [2]=37, [3]=36}
local _tracks_divs = {[0]=1, [1]=1, [2]=1, [3]=1}

local function _tracks_tick()
  -- master tick: each row independently checks gate + advances on its own div
  for r = 0, 3 do
    -- 1. tick the row's gate (open notes); close any that just expired
    if state.tracks_gate[r] > 0 then
      state.tracks_gate[r] = state.tracks_gate[r] - 1
      if state.tracks_gate[r] == 0 then
        midi_note_off(_tracks_notes[r], 0, 1)
      end
    end
    -- 2. tick the row's div countdown; advance + fire only when it hits 0
    state.tracks_tick[r] = state.tracks_tick[r] - 1
    if state.tracks_tick[r] <= 0 then
      state.tracks_tick[r] = _tracks_divs[r]
      state.tracks_step[r] = (state.tracks_step[r] + 1) % 8
      if state.tracks_on[r][state.tracks_step[r]] then
        if state.tracks_gate[r] > 0 then
          midi_note_off(_tracks_notes[r], 0, 1)
        end
        midi_note_on(_tracks_notes[r], 100, 1)
        state.tracks_gate[r] = 1
      end
    end
  end
  -- repaint so each row's playhead is visible
  redraw()
end

local function handle_tracks(x, y, z)
  if z ~= 1 then return end
  local r = _tracks_row[x + y*W]
  local c = _tracks_col[x + y*W]
  state.tracks_on[r][c] = not state.tracks_on[r][c]
end

local function _tracks_pixel(row, col)
  local is_step = col == state.tracks_step[row]
  local is_on = state.tracks_on[row][col]
  if is_step then
    return is_on and 15 or 8
  else
    return is_on and 5 or 2
  end
end

local _tracks_metro = metro.init(_tracks_tick, 0.125)
_tracks_metro:start()

-- ---- LED draw ----
redraw = function()
  -- region: tracks
  grid_led(1, 5, _tracks_pixel(0, 0))
  grid_led(2, 5, _tracks_pixel(0, 1))
  grid_led(3, 5, _tracks_pixel(0, 2))
  grid_led(4, 5, _tracks_pixel(0, 3))
  grid_led(5, 5, _tracks_pixel(0, 4))
  grid_led(6, 5, _tracks_pixel(0, 5))
  grid_led(7, 5, _tracks_pixel(0, 6))
  grid_led(8, 5, _tracks_pixel(0, 7))
  grid_led(1, 6, _tracks_pixel(1, 0))
  grid_led(2, 6, _tracks_pixel(1, 1))
  grid_led(3, 6, _tracks_pixel(1, 2))
  grid_led(4, 6, _tracks_pixel(1, 3))
  grid_led(5, 6, _tracks_pixel(1, 4))
  grid_led(6, 6, _tracks_pixel(1, 5))
  grid_led(7, 6, _tracks_pixel(1, 6))
  grid_led(8, 6, _tracks_pixel(1, 7))
  grid_led(1, 7, _tracks_pixel(2, 0))
  grid_led(2, 7, _tracks_pixel(2, 1))
  grid_led(3, 7, _tracks_pixel(2, 2))
  grid_led(4, 7, _tracks_pixel(2, 3))
  grid_led(5, 7, _tracks_pixel(2, 4))
  grid_led(6, 7, _tracks_pixel(2, 5))
  grid_led(7, 7, _tracks_pixel(2, 6))
  grid_led(8, 7, _tracks_pixel(2, 7))
  grid_led(1, 8, _tracks_pixel(3, 0))
  grid_led(2, 8, _tracks_pixel(3, 1))
  grid_led(3, 8, _tracks_pixel(3, 2))
  grid_led(4, 8, _tracks_pixel(3, 3))
  grid_led(5, 8, _tracks_pixel(3, 4))
  grid_led(6, 8, _tracks_pixel(3, 5))
  grid_led(7, 8, _tracks_pixel(3, 6))
  grid_led(8, 8, _tracks_pixel(3, 7))
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 5*W] = handle_tracks
_route[2 + 5*W] = handle_tracks
_route[3 + 5*W] = handle_tracks
_route[4 + 5*W] = handle_tracks
_route[5 + 5*W] = handle_tracks
_route[6 + 5*W] = handle_tracks
_route[7 + 5*W] = handle_tracks
_route[8 + 5*W] = handle_tracks
_route[1 + 6*W] = handle_tracks
_route[2 + 6*W] = handle_tracks
_route[3 + 6*W] = handle_tracks
_route[4 + 6*W] = handle_tracks
_route[5 + 6*W] = handle_tracks
_route[6 + 6*W] = handle_tracks
_route[7 + 6*W] = handle_tracks
_route[8 + 6*W] = handle_tracks
_route[1 + 7*W] = handle_tracks
_route[2 + 7*W] = handle_tracks
_route[3 + 7*W] = handle_tracks
_route[4 + 7*W] = handle_tracks
_route[5 + 7*W] = handle_tracks
_route[6 + 7*W] = handle_tracks
_route[7 + 7*W] = handle_tracks
_route[8 + 7*W] = handle_tracks
_route[1 + 8*W] = handle_tracks
_route[2 + 8*W] = handle_tracks
_route[3 + 8*W] = handle_tracks
_route[4 + 8*W] = handle_tracks
_route[5 + 8*W] = handle_tracks
_route[6 + 8*W] = handle_tracks
_route[7 + 8*W] = handle_tracks
_route[8 + 8*W] = handle_tracks

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
