-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "major" (32 cells, step seq group, 4×8, ch1 note from 60 major, 120 BPM @ 1/4)
-- Upload: diii  →  first("test-stepseq-major.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  page = 0,
  major_step = {[0]=-1, [1]=-1, [2]=-1, [3]=-1},
  major_on = {[0]={}, [1]={}, [2]={}, [3]={}},
  major_dir = {[0]=1, [1]=1, [2]=1, [3]=1},
  major_tick = {[0]=1, [1]=1, [2]=1, [3]=1},
  major_gate = {[0]=0, [1]=0, [2]=0, [3]=0},
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: major ----
local _major_row = {}
_major_row[1 + 5*W] = 0
_major_row[2 + 5*W] = 0
_major_row[3 + 5*W] = 0
_major_row[4 + 5*W] = 0
_major_row[5 + 5*W] = 0
_major_row[6 + 5*W] = 0
_major_row[7 + 5*W] = 0
_major_row[8 + 5*W] = 0
_major_row[1 + 6*W] = 1
_major_row[2 + 6*W] = 1
_major_row[3 + 6*W] = 1
_major_row[4 + 6*W] = 1
_major_row[5 + 6*W] = 1
_major_row[6 + 6*W] = 1
_major_row[7 + 6*W] = 1
_major_row[8 + 6*W] = 1
_major_row[1 + 7*W] = 2
_major_row[2 + 7*W] = 2
_major_row[3 + 7*W] = 2
_major_row[4 + 7*W] = 2
_major_row[5 + 7*W] = 2
_major_row[6 + 7*W] = 2
_major_row[7 + 7*W] = 2
_major_row[8 + 7*W] = 2
_major_row[1 + 8*W] = 3
_major_row[2 + 8*W] = 3
_major_row[3 + 8*W] = 3
_major_row[4 + 8*W] = 3
_major_row[5 + 8*W] = 3
_major_row[6 + 8*W] = 3
_major_row[7 + 8*W] = 3
_major_row[8 + 8*W] = 3
local _major_col = {}
_major_col[1 + 5*W] = 0
_major_col[2 + 5*W] = 1
_major_col[3 + 5*W] = 2
_major_col[4 + 5*W] = 3
_major_col[5 + 5*W] = 4
_major_col[6 + 5*W] = 5
_major_col[7 + 5*W] = 6
_major_col[8 + 5*W] = 7
_major_col[1 + 6*W] = 0
_major_col[2 + 6*W] = 1
_major_col[3 + 6*W] = 2
_major_col[4 + 6*W] = 3
_major_col[5 + 6*W] = 4
_major_col[6 + 6*W] = 5
_major_col[7 + 6*W] = 6
_major_col[8 + 6*W] = 7
_major_col[1 + 7*W] = 0
_major_col[2 + 7*W] = 1
_major_col[3 + 7*W] = 2
_major_col[4 + 7*W] = 3
_major_col[5 + 7*W] = 4
_major_col[6 + 7*W] = 5
_major_col[7 + 7*W] = 6
_major_col[8 + 7*W] = 7
_major_col[1 + 8*W] = 0
_major_col[2 + 8*W] = 1
_major_col[3 + 8*W] = 2
_major_col[4 + 8*W] = 3
_major_col[5 + 8*W] = 4
_major_col[6 + 8*W] = 5
_major_col[7 + 8*W] = 6
_major_col[8 + 8*W] = 7
local _major_notes = {[0]=65, [1]=64, [2]=62, [3]=60}
local _major_divs = {[0]=1, [1]=1, [2]=1, [3]=1}

local function _major_tick()
  -- master tick (poly): each row independently gates + fires; voices overlap
  for r = 0, 3 do
    -- 1. tick the row's gate (open notes); close any that just expired
    if state.major_gate[r] > 0 then
      state.major_gate[r] = state.major_gate[r] - 1
      if state.major_gate[r] == 0 then
        midi_note_off(_major_notes[r], 0, 1)
      end
    end
    -- 2. tick the row's div countdown; advance + fire only when it hits 0
    state.major_tick[r] = state.major_tick[r] - 1
    if state.major_tick[r] <= 0 then
      state.major_tick[r] = _major_divs[r]
      state.major_step[r] = (state.major_step[r] + 1) % 8
      if state.major_on[r][state.major_step[r]] then
        if state.major_gate[r] > 0 then
          midi_note_off(_major_notes[r], 0, 1)
        end
        midi_note_on(_major_notes[r], 100, 1)
        state.major_gate[r] = 1
      end
    end
  end
  -- repaint so each row's playhead is visible
  redraw()
end

local function handle_major(x, y, z)
  if z ~= 1 then return end
  local r = _major_row[x + y*W]
  local c = _major_col[x + y*W]
  state.major_on[r][c] = not state.major_on[r][c]
end

local function _major_pixel(row, col)
  local is_step = col == state.major_step[row]
  local is_on = state.major_on[row][col]
  if is_step then
    return is_on and 15 or 8
  else
    return is_on and 5 or 2
  end
end

local _major_metro = metro.init(_major_tick, 0.125)
_major_metro:start()

-- ---- per-page LED draw ----
local function _draw_p0()
  -- region: major
  grid_led(1, 5, _major_pixel(0, 0))
  grid_led(2, 5, _major_pixel(0, 1))
  grid_led(3, 5, _major_pixel(0, 2))
  grid_led(4, 5, _major_pixel(0, 3))
  grid_led(5, 5, _major_pixel(0, 4))
  grid_led(6, 5, _major_pixel(0, 5))
  grid_led(7, 5, _major_pixel(0, 6))
  grid_led(8, 5, _major_pixel(0, 7))
  grid_led(1, 6, _major_pixel(1, 0))
  grid_led(2, 6, _major_pixel(1, 1))
  grid_led(3, 6, _major_pixel(1, 2))
  grid_led(4, 6, _major_pixel(1, 3))
  grid_led(5, 6, _major_pixel(1, 4))
  grid_led(6, 6, _major_pixel(1, 5))
  grid_led(7, 6, _major_pixel(1, 6))
  grid_led(8, 6, _major_pixel(1, 7))
  grid_led(1, 7, _major_pixel(2, 0))
  grid_led(2, 7, _major_pixel(2, 1))
  grid_led(3, 7, _major_pixel(2, 2))
  grid_led(4, 7, _major_pixel(2, 3))
  grid_led(5, 7, _major_pixel(2, 4))
  grid_led(6, 7, _major_pixel(2, 5))
  grid_led(7, 7, _major_pixel(2, 6))
  grid_led(8, 7, _major_pixel(2, 7))
  grid_led(1, 8, _major_pixel(3, 0))
  grid_led(2, 8, _major_pixel(3, 1))
  grid_led(3, 8, _major_pixel(3, 2))
  grid_led(4, 8, _major_pixel(3, 3))
  grid_led(5, 8, _major_pixel(3, 4))
  grid_led(6, 8, _major_pixel(3, 5))
  grid_led(7, 8, _major_pixel(3, 6))
  grid_led(8, 8, _major_pixel(3, 7))
end

-- ---- master redraw ----
redraw = function()
  _draw_p0()
  grid_refresh()
end

-- ---- dispatch ----
local _route_global = {}

local _route_p0 = {}
_route_p0[1 + 5*W] = handle_major
_route_p0[2 + 5*W] = handle_major
_route_p0[3 + 5*W] = handle_major
_route_p0[4 + 5*W] = handle_major
_route_p0[5 + 5*W] = handle_major
_route_p0[6 + 5*W] = handle_major
_route_p0[7 + 5*W] = handle_major
_route_p0[8 + 5*W] = handle_major
_route_p0[1 + 6*W] = handle_major
_route_p0[2 + 6*W] = handle_major
_route_p0[3 + 6*W] = handle_major
_route_p0[4 + 6*W] = handle_major
_route_p0[5 + 6*W] = handle_major
_route_p0[6 + 6*W] = handle_major
_route_p0[7 + 6*W] = handle_major
_route_p0[8 + 6*W] = handle_major
_route_p0[1 + 7*W] = handle_major
_route_p0[2 + 7*W] = handle_major
_route_p0[3 + 7*W] = handle_major
_route_p0[4 + 7*W] = handle_major
_route_p0[5 + 7*W] = handle_major
_route_p0[6 + 7*W] = handle_major
_route_p0[7 + 7*W] = handle_major
_route_p0[8 + 7*W] = handle_major
_route_p0[1 + 8*W] = handle_major
_route_p0[2 + 8*W] = handle_major
_route_p0[3 + 8*W] = handle_major
_route_p0[4 + 8*W] = handle_major
_route_p0[5 + 8*W] = handle_major
_route_p0[6 + 8*W] = handle_major
_route_p0[7 + 8*W] = handle_major
_route_p0[8 + 8*W] = handle_major

local _routes = {[0]=_route_p0}

function event_grid(x, y, z)
  local k = x + y*W
  -- global (page_select) handlers run first; they may switch state.page
  local h = _route_global[k]
  if h then
    h(x, y, z)
    redraw()
    return
  end
  -- per-page dispatch
  local route = _routes[state.page]
  if route then
    h = route[k]
    if h then h(x, y, z) end
  end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
