-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "mods" (32 cells, step seq group, 2×16, ch1 cc from 20, 100 BPM @ 1/2)
-- Upload: diii  →  first("test-stepseq-cc-mod.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  mods_step = -1,
  mods_on = {[0]={}, [1]={}},
}

-- ---- region: mods ----
local _mods_row = {}
_mods_row[1 + 1*W] = 0
_mods_row[2 + 1*W] = 0
_mods_row[3 + 1*W] = 0
_mods_row[4 + 1*W] = 0
_mods_row[5 + 1*W] = 0
_mods_row[6 + 1*W] = 0
_mods_row[7 + 1*W] = 0
_mods_row[8 + 1*W] = 0
_mods_row[9 + 1*W] = 0
_mods_row[10 + 1*W] = 0
_mods_row[11 + 1*W] = 0
_mods_row[12 + 1*W] = 0
_mods_row[13 + 1*W] = 0
_mods_row[14 + 1*W] = 0
_mods_row[15 + 1*W] = 0
_mods_row[16 + 1*W] = 0
_mods_row[1 + 2*W] = 1
_mods_row[2 + 2*W] = 1
_mods_row[3 + 2*W] = 1
_mods_row[4 + 2*W] = 1
_mods_row[5 + 2*W] = 1
_mods_row[6 + 2*W] = 1
_mods_row[7 + 2*W] = 1
_mods_row[8 + 2*W] = 1
_mods_row[9 + 2*W] = 1
_mods_row[10 + 2*W] = 1
_mods_row[11 + 2*W] = 1
_mods_row[12 + 2*W] = 1
_mods_row[13 + 2*W] = 1
_mods_row[14 + 2*W] = 1
_mods_row[15 + 2*W] = 1
_mods_row[16 + 2*W] = 1
local _mods_col = {}
_mods_col[1 + 1*W] = 0
_mods_col[2 + 1*W] = 1
_mods_col[3 + 1*W] = 2
_mods_col[4 + 1*W] = 3
_mods_col[5 + 1*W] = 4
_mods_col[6 + 1*W] = 5
_mods_col[7 + 1*W] = 6
_mods_col[8 + 1*W] = 7
_mods_col[9 + 1*W] = 8
_mods_col[10 + 1*W] = 9
_mods_col[11 + 1*W] = 10
_mods_col[12 + 1*W] = 11
_mods_col[13 + 1*W] = 12
_mods_col[14 + 1*W] = 13
_mods_col[15 + 1*W] = 14
_mods_col[16 + 1*W] = 15
_mods_col[1 + 2*W] = 0
_mods_col[2 + 2*W] = 1
_mods_col[3 + 2*W] = 2
_mods_col[4 + 2*W] = 3
_mods_col[5 + 2*W] = 4
_mods_col[6 + 2*W] = 5
_mods_col[7 + 2*W] = 6
_mods_col[8 + 2*W] = 7
_mods_col[9 + 2*W] = 8
_mods_col[10 + 2*W] = 9
_mods_col[11 + 2*W] = 10
_mods_col[12 + 2*W] = 11
_mods_col[13 + 2*W] = 12
_mods_col[14 + 2*W] = 13
_mods_col[15 + 2*W] = 14
_mods_col[16 + 2*W] = 15
local _mods_ccs = {[0]=20, [1]=21}

local function _mods_tick()
  -- close out the step we are leaving (gate-style)
  local leaving = state.mods_step
  if leaving >= 0 then
    for r = 0, 1 do
      if state.mods_on[r][leaving] then
        midi_cc(_mods_ccs[r], 0, 1)
      end
    end
  end
  -- advance playhead
  state.mods_step = (state.mods_step + 1) % 16
  -- open up the new step
  for r = 0, 1 do
    if state.mods_on[r][state.mods_step] then
      midi_cc(_mods_ccs[r], 127, 1)
    end
  end
end

local function handle_mods(x, y, z)
  if z ~= 1 then return end
  local r = _mods_row[x + y*W]
  local c = _mods_col[x + y*W]
  state.mods_on[r][c] = not state.mods_on[r][c]
end

local function _mods_pixel(row, col)
  local is_step = col == state.mods_step
  local is_on = state.mods_on[row][col]
  if is_step then
    return is_on and 15 or 8
  else
    return is_on and 5 or 2
  end
end

local _mods_metro = metro.init(_mods_tick, 0.3)
_mods_metro:start()

-- ---- LED draw ----
local function redraw()
  grid_led_all(0)
  -- region: mods
  grid_led(1, 1, _mods_pixel(0, 0))
  grid_led(2, 1, _mods_pixel(0, 1))
  grid_led(3, 1, _mods_pixel(0, 2))
  grid_led(4, 1, _mods_pixel(0, 3))
  grid_led(5, 1, _mods_pixel(0, 4))
  grid_led(6, 1, _mods_pixel(0, 5))
  grid_led(7, 1, _mods_pixel(0, 6))
  grid_led(8, 1, _mods_pixel(0, 7))
  grid_led(9, 1, _mods_pixel(0, 8))
  grid_led(10, 1, _mods_pixel(0, 9))
  grid_led(11, 1, _mods_pixel(0, 10))
  grid_led(12, 1, _mods_pixel(0, 11))
  grid_led(13, 1, _mods_pixel(0, 12))
  grid_led(14, 1, _mods_pixel(0, 13))
  grid_led(15, 1, _mods_pixel(0, 14))
  grid_led(16, 1, _mods_pixel(0, 15))
  grid_led(1, 2, _mods_pixel(1, 0))
  grid_led(2, 2, _mods_pixel(1, 1))
  grid_led(3, 2, _mods_pixel(1, 2))
  grid_led(4, 2, _mods_pixel(1, 3))
  grid_led(5, 2, _mods_pixel(1, 4))
  grid_led(6, 2, _mods_pixel(1, 5))
  grid_led(7, 2, _mods_pixel(1, 6))
  grid_led(8, 2, _mods_pixel(1, 7))
  grid_led(9, 2, _mods_pixel(1, 8))
  grid_led(10, 2, _mods_pixel(1, 9))
  grid_led(11, 2, _mods_pixel(1, 10))
  grid_led(12, 2, _mods_pixel(1, 11))
  grid_led(13, 2, _mods_pixel(1, 12))
  grid_led(14, 2, _mods_pixel(1, 13))
  grid_led(15, 2, _mods_pixel(1, 14))
  grid_led(16, 2, _mods_pixel(1, 15))
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 1*W] = handle_mods
_route[2 + 1*W] = handle_mods
_route[3 + 1*W] = handle_mods
_route[4 + 1*W] = handle_mods
_route[5 + 1*W] = handle_mods
_route[6 + 1*W] = handle_mods
_route[7 + 1*W] = handle_mods
_route[8 + 1*W] = handle_mods
_route[9 + 1*W] = handle_mods
_route[10 + 1*W] = handle_mods
_route[11 + 1*W] = handle_mods
_route[12 + 1*W] = handle_mods
_route[13 + 1*W] = handle_mods
_route[14 + 1*W] = handle_mods
_route[15 + 1*W] = handle_mods
_route[16 + 1*W] = handle_mods
_route[1 + 2*W] = handle_mods
_route[2 + 2*W] = handle_mods
_route[3 + 2*W] = handle_mods
_route[4 + 2*W] = handle_mods
_route[5 + 2*W] = handle_mods
_route[6 + 2*W] = handle_mods
_route[7 + 2*W] = handle_mods
_route[8 + 2*W] = handle_mods
_route[9 + 2*W] = handle_mods
_route[10 + 2*W] = handle_mods
_route[11 + 2*W] = handle_mods
_route[12 + 2*W] = handle_mods
_route[13 + 2*W] = handle_mods
_route[14 + 2*W] = handle_mods
_route[15 + 2*W] = handle_mods
_route[16 + 2*W] = handle_mods

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
redraw()
