-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 1 region
--   page 1 "main":
--     - "switches" (8 cells, toggle per_cell, ch1 cc from 20)
-- Upload: diii  →  first("test-toggle-per-cell-cc.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  switches_on = {},
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- region: switches ----
local _switches_idx = {}
_switches_idx[1 + 1*W] = 0
_switches_idx[2 + 1*W] = 1
_switches_idx[3 + 1*W] = 2
_switches_idx[4 + 1*W] = 3
_switches_idx[5 + 1*W] = 4
_switches_idx[6 + 1*W] = 5
_switches_idx[7 + 1*W] = 6
_switches_idx[8 + 1*W] = 7

local function handle_switches(x, y, z)
  if z ~= 1 then return end
  local idx = _switches_idx[x + y*W]
  state.switches_on[x + y*W] = not state.switches_on[x + y*W]
  midi_cc(20 + idx, state.switches_on[x + y*W] and 127 or 0, 1)
end

-- ---- LED draw ----
local function redraw()
  -- region: switches
  grid_led(1, 1, state.switches_on[1 + 1*W] and 15 or 3)
  grid_led(2, 1, state.switches_on[2 + 1*W] and 15 or 3)
  grid_led(3, 1, state.switches_on[3 + 1*W] and 15 or 3)
  grid_led(4, 1, state.switches_on[4 + 1*W] and 15 or 3)
  grid_led(5, 1, state.switches_on[5 + 1*W] and 15 or 3)
  grid_led(6, 1, state.switches_on[6 + 1*W] and 15 or 3)
  grid_led(7, 1, state.switches_on[7 + 1*W] and 15 or 3)
  grid_led(8, 1, state.switches_on[8 + 1*W] and 15 or 3)
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 1*W] = handle_switches
_route[2 + 1*W] = handle_switches
_route[3 + 1*W] = handle_switches
_route[4 + 1*W] = handle_switches
_route[5 + 1*W] = handle_switches
_route[6 + 1*W] = handle_switches
_route[7 + 1*W] = handle_switches
_route[8 + 1*W] = handle_switches

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
