-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 8x8, 1 page, 1 region
--   page 1 "main":
--     - "switches" (8 cells, toggle per_cell, ch1 cc from 20)
-- Upload: diii  →  first("test-toggle-per-cell-cc.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  switches_on = {},
}

-- ---- region: switches ----
local _switches_idx = {}
_switches_idx[0 + 0*W] = 0
_switches_idx[1 + 0*W] = 1
_switches_idx[2 + 0*W] = 2
_switches_idx[3 + 0*W] = 3
_switches_idx[4 + 0*W] = 4
_switches_idx[5 + 0*W] = 5
_switches_idx[6 + 0*W] = 6
_switches_idx[7 + 0*W] = 7

local function handle_switches(x, y, z)
  if z ~= 1 then return end
  local idx = _switches_idx[x + y*W]
  state.switches_on[x + y*W] = not state.switches_on[x + y*W]
  midi_cc(20 + idx, state.switches_on[x + y*W] and 127 or 0, 1)
end

-- ---- LED draw ----
local function redraw()
  grid_led_all(0)
  -- region: switches
  grid_led(0, 0, state.switches_on[0 + 0*W] and 15 or 3)
  grid_led(1, 0, state.switches_on[1 + 0*W] and 15 or 3)
  grid_led(2, 0, state.switches_on[2 + 0*W] and 15 or 3)
  grid_led(3, 0, state.switches_on[3 + 0*W] and 15 or 3)
  grid_led(4, 0, state.switches_on[4 + 0*W] and 15 or 3)
  grid_led(5, 0, state.switches_on[5 + 0*W] and 15 or 3)
  grid_led(6, 0, state.switches_on[6 + 0*W] and 15 or 3)
  grid_led(7, 0, state.switches_on[7 + 0*W] and 15 or 3)
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[0 + 0*W] = handle_switches
_route[1 + 0*W] = handle_switches
_route[2 + 0*W] = handle_switches
_route[3 + 0*W] = handle_switches
_route[4 + 0*W] = handle_switches
_route[5 + 0*W] = handle_switches
_route[6 + 0*W] = handle_switches
_route[7 + 0*W] = handle_switches

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
redraw()
