-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "wake" (16 cells, wake seq, 4×4 (1 fn + 3 body), ch1 root MIDI 60 major, 120 BPM @ 1/4)
-- Upload: diii  →  first("test-wakeseq-4x4.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  wake_step = -1,
  wake_page = 0,
  wake_data = {[0]={[0]=0, [1]=0, [2]=0, [3]=0}, [1]={[0]=0, [1]=0, [2]=0, [3]=0}, [2]={[0]=0, [1]=0, [2]=0, [3]=0}, [3]={[0]=0, [1]=0, [2]=0, [3]=0}},
  wake_active_note = -1,
  wake_active_gate = 0,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: wake ----
local _wake_col = {}
_wake_col[1 + 1*W] = 0
_wake_col[2 + 1*W] = 1
_wake_col[3 + 1*W] = 2
_wake_col[4 + 1*W] = 3
_wake_col[1 + 2*W] = 0
_wake_col[2 + 2*W] = 1
_wake_col[3 + 2*W] = 2
_wake_col[4 + 2*W] = 3
_wake_col[1 + 3*W] = 0
_wake_col[2 + 3*W] = 1
_wake_col[3 + 3*W] = 2
_wake_col[4 + 3*W] = 3
_wake_col[1 + 4*W] = 0
_wake_col[2 + 4*W] = 1
_wake_col[3 + 4*W] = 2
_wake_col[4 + 4*W] = 3
local _wake_rr = {}
_wake_rr[1 + 1*W] = 0
_wake_rr[2 + 1*W] = 0
_wake_rr[3 + 1*W] = 0
_wake_rr[4 + 1*W] = 0
_wake_rr[1 + 2*W] = 1
_wake_rr[2 + 2*W] = 1
_wake_rr[3 + 2*W] = 1
_wake_rr[4 + 2*W] = 1
_wake_rr[1 + 3*W] = 2
_wake_rr[2 + 3*W] = 2
_wake_rr[3 + 3*W] = 2
_wake_rr[4 + 3*W] = 2
_wake_rr[1 + 4*W] = 3
_wake_rr[2 + 4*W] = 3
_wake_rr[3 + 4*W] = 3
_wake_rr[4 + 4*W] = 3
local _wake_scale = {[1]=0, [2]=2, [3]=4}
local _wake_vel = {[0]=0, [1]=42, [2]=84, [3]=127}

local function _wake_tick()
  -- 1. tick down active gate; close any voice that just expired
  if state.wake_active_gate > 0 then
    state.wake_active_gate = state.wake_active_gate - 1
    if state.wake_active_gate == 0 and state.wake_active_note >= 0 then
      midi_note_off(state.wake_active_note, 0, 1)
      state.wake_active_note = -1
    end
  end
  -- 2. advance the playhead
  state.wake_step = (state.wake_step + 1) % 4
  -- 3. compute and fire the new step's note (if it has one)
  local pitch = state.wake_data[0][state.wake_step]
  local oct = state.wake_data[1][state.wake_step]
  local v = state.wake_data[2][state.wake_step]
  local g = state.wake_data[3][state.wake_step]
  -- pitch>0 and v>0 are both required for the step to sound
  if pitch > 0 and v > 0 then
    if state.wake_active_note >= 0 then
      midi_note_off(state.wake_active_note, 0, 1)
    end
    local note = 60 + _wake_scale[pitch] + 12 * oct
    midi_note_on(note, _wake_vel[v], 1)
    state.wake_active_note = note
    -- gate value of 0 still gets a 1-tick blip; 1..body_height = held ticks
    state.wake_active_gate = (g == 0) and 1 or g
  end
  redraw()
end

local function handle_wake(x, y, z)
  if z ~= 1 then return end
  local c = _wake_col[x + y*W]
  local rr = _wake_rr[x + y*W]
  if rr == 0 then
    -- function row: page select (extra cells beyond NUM_PAGES are ignored)
    if c < 4 then
      state.wake_page = c
    end
  else
    -- body cell: set / clear data[page][col]
    local body_row = rr - 1
    local value = 3 - body_row
    local cur = state.wake_data[state.wake_page][c]
    if cur == value then
      state.wake_data[state.wake_page][c] = 0
    else
      state.wake_data[state.wake_page][c] = value
    end
  end
end

local function _wake_pixel(col, rr)
  if rr == 0 then
    -- function row
    if col >= 4 then return 1 end
    return (state.wake_page == col) and 12 or 6
  end
  -- body row
  local body_row = rr - 1
  local target = 3 - body_row
  local v = state.wake_data[state.wake_page][col]
  local on_step = (col == state.wake_step)
  if v == target then
    return on_step and 15 or 12
  end
  return on_step and 4 or 0
end

local _wake_metro = metro.init(_wake_tick, 0.125)
_wake_metro:start()

-- ---- LED draw ----
redraw = function()
  -- region: wake
  grid_led(1, 1, _wake_pixel(0, 0))
  grid_led(2, 1, _wake_pixel(1, 0))
  grid_led(3, 1, _wake_pixel(2, 0))
  grid_led(4, 1, _wake_pixel(3, 0))
  grid_led(1, 2, _wake_pixel(0, 1))
  grid_led(2, 2, _wake_pixel(1, 1))
  grid_led(3, 2, _wake_pixel(2, 1))
  grid_led(4, 2, _wake_pixel(3, 1))
  grid_led(1, 3, _wake_pixel(0, 2))
  grid_led(2, 3, _wake_pixel(1, 2))
  grid_led(3, 3, _wake_pixel(2, 2))
  grid_led(4, 3, _wake_pixel(3, 2))
  grid_led(1, 4, _wake_pixel(0, 3))
  grid_led(2, 4, _wake_pixel(1, 3))
  grid_led(3, 4, _wake_pixel(2, 3))
  grid_led(4, 4, _wake_pixel(3, 3))
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 1*W] = handle_wake
_route[2 + 1*W] = handle_wake
_route[3 + 1*W] = handle_wake
_route[4 + 1*W] = handle_wake
_route[1 + 2*W] = handle_wake
_route[2 + 2*W] = handle_wake
_route[3 + 2*W] = handle_wake
_route[4 + 2*W] = handle_wake
_route[1 + 3*W] = handle_wake
_route[2 + 3*W] = handle_wake
_route[3 + 3*W] = handle_wake
_route[4 + 3*W] = handle_wake
_route[1 + 4*W] = handle_wake
_route[2 + 4*W] = handle_wake
_route[3 + 4*W] = handle_wake
_route[4 + 4*W] = handle_wake

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
