-- =========================================================
-- Generated by monome-iii-studio v0.0.0
-- Layout: 16x8, 1 page, 1 region
--   page 1 "main":
--     - "wake" (64 cells, wake seq, 8×8 (1 fn + 7 body), ch1 root MIDI 60 major, 120 BPM @ 1/4)
-- Upload: diii  →  first("test-wakeseq-8x8.lua")
-- =========================================================

local W, H = grid_size_x(), grid_size_y()

-- ---- state ----
local state = {
  wake_step = -1,
  wake_page = 0,
  wake_data = {[0]={[0]=0, [1]=0, [2]=0, [3]=0, [4]=0, [5]=0, [6]=0, [7]=0}, [1]={[0]=4, [1]=4, [2]=4, [3]=4, [4]=4, [5]=4, [6]=4, [7]=4}, [2]={[0]=7, [1]=7, [2]=7, [3]=7, [4]=7, [5]=7, [6]=7, [7]=7}, [3]={[0]=7, [1]=7, [2]=7, [3]=7, [4]=7, [5]=7, [6]=7, [7]=7}},
  wake_active_note = -1,
  wake_active_dur = 0,
  wake_sub = 0,
}

-- ---- differential LED writes ----
-- Wrap iii's grid_led so unchanged brightness is skipped. Calling
-- grid_led_all(0) on every redraw makes the whole grid flicker dark
-- when several keys are pressed in quick succession; instead we
-- clear once at init and only push deltas after that. _prev_led is
-- keyed the same way as our route table (1-indexed x + y*W). nil
-- entries are treated as 0 so the first redraw skips zero-fills.
local _real_grid_led = grid_led
local _prev_led = {}
local function grid_led(x, y, v)
  local k = x + y*W
  if (_prev_led[k] or 0) ~= v then
    _real_grid_led(x, y, v)
    _prev_led[k] = v
  end
end

-- ---- forward declaration ----
-- `redraw` is defined further down but is referenced from metro tick
-- callbacks inside the region declarations below. Forward-declaring it
-- here as a local makes each tick closure capture it as an upvalue, so
-- the tick resolves the reference via the upvalue (which holds the
-- assigned function once the script finishes loading) instead of
-- falling through to a non-existent global.
local redraw

-- ---- region: wake ----
local _wake_col = {}
_wake_col[1 + 1*W] = 0
_wake_col[2 + 1*W] = 1
_wake_col[3 + 1*W] = 2
_wake_col[4 + 1*W] = 3
_wake_col[5 + 1*W] = 4
_wake_col[6 + 1*W] = 5
_wake_col[7 + 1*W] = 6
_wake_col[8 + 1*W] = 7
_wake_col[1 + 2*W] = 0
_wake_col[2 + 2*W] = 1
_wake_col[3 + 2*W] = 2
_wake_col[4 + 2*W] = 3
_wake_col[5 + 2*W] = 4
_wake_col[6 + 2*W] = 5
_wake_col[7 + 2*W] = 6
_wake_col[8 + 2*W] = 7
_wake_col[1 + 3*W] = 0
_wake_col[2 + 3*W] = 1
_wake_col[3 + 3*W] = 2
_wake_col[4 + 3*W] = 3
_wake_col[5 + 3*W] = 4
_wake_col[6 + 3*W] = 5
_wake_col[7 + 3*W] = 6
_wake_col[8 + 3*W] = 7
_wake_col[1 + 4*W] = 0
_wake_col[2 + 4*W] = 1
_wake_col[3 + 4*W] = 2
_wake_col[4 + 4*W] = 3
_wake_col[5 + 4*W] = 4
_wake_col[6 + 4*W] = 5
_wake_col[7 + 4*W] = 6
_wake_col[8 + 4*W] = 7
_wake_col[1 + 5*W] = 0
_wake_col[2 + 5*W] = 1
_wake_col[3 + 5*W] = 2
_wake_col[4 + 5*W] = 3
_wake_col[5 + 5*W] = 4
_wake_col[6 + 5*W] = 5
_wake_col[7 + 5*W] = 6
_wake_col[8 + 5*W] = 7
_wake_col[1 + 6*W] = 0
_wake_col[2 + 6*W] = 1
_wake_col[3 + 6*W] = 2
_wake_col[4 + 6*W] = 3
_wake_col[5 + 6*W] = 4
_wake_col[6 + 6*W] = 5
_wake_col[7 + 6*W] = 6
_wake_col[8 + 6*W] = 7
_wake_col[1 + 7*W] = 0
_wake_col[2 + 7*W] = 1
_wake_col[3 + 7*W] = 2
_wake_col[4 + 7*W] = 3
_wake_col[5 + 7*W] = 4
_wake_col[6 + 7*W] = 5
_wake_col[7 + 7*W] = 6
_wake_col[8 + 7*W] = 7
_wake_col[1 + 8*W] = 0
_wake_col[2 + 8*W] = 1
_wake_col[3 + 8*W] = 2
_wake_col[4 + 8*W] = 3
_wake_col[5 + 8*W] = 4
_wake_col[6 + 8*W] = 5
_wake_col[7 + 8*W] = 6
_wake_col[8 + 8*W] = 7
local _wake_rr = {}
_wake_rr[1 + 1*W] = 0
_wake_rr[2 + 1*W] = 0
_wake_rr[3 + 1*W] = 0
_wake_rr[4 + 1*W] = 0
_wake_rr[5 + 1*W] = 0
_wake_rr[6 + 1*W] = 0
_wake_rr[7 + 1*W] = 0
_wake_rr[8 + 1*W] = 0
_wake_rr[1 + 2*W] = 1
_wake_rr[2 + 2*W] = 1
_wake_rr[3 + 2*W] = 1
_wake_rr[4 + 2*W] = 1
_wake_rr[5 + 2*W] = 1
_wake_rr[6 + 2*W] = 1
_wake_rr[7 + 2*W] = 1
_wake_rr[8 + 2*W] = 1
_wake_rr[1 + 3*W] = 2
_wake_rr[2 + 3*W] = 2
_wake_rr[3 + 3*W] = 2
_wake_rr[4 + 3*W] = 2
_wake_rr[5 + 3*W] = 2
_wake_rr[6 + 3*W] = 2
_wake_rr[7 + 3*W] = 2
_wake_rr[8 + 3*W] = 2
_wake_rr[1 + 4*W] = 3
_wake_rr[2 + 4*W] = 3
_wake_rr[3 + 4*W] = 3
_wake_rr[4 + 4*W] = 3
_wake_rr[5 + 4*W] = 3
_wake_rr[6 + 4*W] = 3
_wake_rr[7 + 4*W] = 3
_wake_rr[8 + 4*W] = 3
_wake_rr[1 + 5*W] = 4
_wake_rr[2 + 5*W] = 4
_wake_rr[3 + 5*W] = 4
_wake_rr[4 + 5*W] = 4
_wake_rr[5 + 5*W] = 4
_wake_rr[6 + 5*W] = 4
_wake_rr[7 + 5*W] = 4
_wake_rr[8 + 5*W] = 4
_wake_rr[1 + 6*W] = 5
_wake_rr[2 + 6*W] = 5
_wake_rr[3 + 6*W] = 5
_wake_rr[4 + 6*W] = 5
_wake_rr[5 + 6*W] = 5
_wake_rr[6 + 6*W] = 5
_wake_rr[7 + 6*W] = 5
_wake_rr[8 + 6*W] = 5
_wake_rr[1 + 7*W] = 6
_wake_rr[2 + 7*W] = 6
_wake_rr[3 + 7*W] = 6
_wake_rr[4 + 7*W] = 6
_wake_rr[5 + 7*W] = 6
_wake_rr[6 + 7*W] = 6
_wake_rr[7 + 7*W] = 6
_wake_rr[8 + 7*W] = 6
_wake_rr[1 + 8*W] = 7
_wake_rr[2 + 8*W] = 7
_wake_rr[3 + 8*W] = 7
_wake_rr[4 + 8*W] = 7
_wake_rr[5 + 8*W] = 7
_wake_rr[6 + 8*W] = 7
_wake_rr[7 + 8*W] = 7
_wake_rr[8 + 8*W] = 7
local _wake_scale = {[1]=0, [2]=2, [3]=4, [4]=5, [5]=7, [6]=9, [7]=11}
local _wake_vel = {[0]=0, [1]=18, [2]=36, [3]=54, [4]=72, [5]=90, [6]=108, [7]=127}
local _wake_dur = {[0]=0, [1]=1, [2]=2, [3]=5, [4]=11, [5]=25, [6]=57, [7]=128}

local function _wake_tick()
  -- 1. tick down active note duration; close any voice that just expired
  if state.wake_active_dur > 0 then
    state.wake_active_dur = state.wake_active_dur - 1
    if state.wake_active_dur == 0 and state.wake_active_note >= 0 then
      midi_note_off(state.wake_active_note, 0, 1)
      state.wake_active_note = -1
    end
  end
  -- 2. only advance the playhead every 8 master ticks
  state.wake_sub = state.wake_sub + 1
  if state.wake_sub < 8 then return end
  state.wake_sub = 0
  state.wake_step = (state.wake_step + 1) % 8
  -- 3. compute and fire the new step's note (if it has one)
  local pitch = state.wake_data[0][state.wake_step]
  local oct = state.wake_data[1][state.wake_step]
  local v = state.wake_data[2][state.wake_step]
  local d = state.wake_data[3][state.wake_step]
  -- pitch / v / d all > 0 required for the step to sound. v=0
  -- (cleared on VEL page) and d=0 (cleared on DURATION page)
  -- both silence the step the same way pitch=0 does.
  if pitch > 0 and v > 0 and d > 0 then
    if state.wake_active_note >= 0 then
      midi_note_off(state.wake_active_note, 0, 1)
    end
    local note = 60 + _wake_scale[pitch] + 12 * (oct - 4)
    midi_note_on(note, _wake_vel[v], 1)
    state.wake_active_note = note
    state.wake_active_dur = _wake_dur[d]
  end
  redraw()
end

local function handle_wake(x, y, z)
  if z ~= 1 then return end
  local c = _wake_col[x + y*W]
  local rr = _wake_rr[x + y*W]
  if rr == 0 then
    -- function row: page select (extra cells beyond NUM_PAGES are ignored)
    if c < 4 then
      state.wake_page = c
    end
  else
    -- body cell: set / clear data[page][col]
    local body_row = rr - 1
    local value = 7 - body_row
    local cur = state.wake_data[state.wake_page][c]
    -- OCT (page 1) is centred and must always show one cell lit;
    -- pressing the lit cell is a no-op rather than a toggle-off.
    if state.wake_page == 1 then
      state.wake_data[1][c] = value
    elseif cur == value then
      state.wake_data[state.wake_page][c] = 0
    else
      state.wake_data[state.wake_page][c] = value
    end
  end
end

local function _wake_pixel(col, rr)
  if rr == 0 then
    -- function row
    if col >= 4 then return 1 end
    return (state.wake_page == col) and 12 or 6
  end
  -- body row
  local body_row = rr - 1
  local target = 7 - body_row
  local v = state.wake_data[state.wake_page][col]
  local on_step = (col == state.wake_step)
  if v == target then
    return on_step and 15 or 12
  end
  return on_step and 4 or 0
end

local _wake_metro = metro.init(_wake_tick, 0.015625)
_wake_metro:start()

-- ---- LED draw ----
redraw = function()
  -- region: wake
  grid_led(1, 1, _wake_pixel(0, 0))
  grid_led(2, 1, _wake_pixel(1, 0))
  grid_led(3, 1, _wake_pixel(2, 0))
  grid_led(4, 1, _wake_pixel(3, 0))
  grid_led(5, 1, _wake_pixel(4, 0))
  grid_led(6, 1, _wake_pixel(5, 0))
  grid_led(7, 1, _wake_pixel(6, 0))
  grid_led(8, 1, _wake_pixel(7, 0))
  grid_led(1, 2, _wake_pixel(0, 1))
  grid_led(2, 2, _wake_pixel(1, 1))
  grid_led(3, 2, _wake_pixel(2, 1))
  grid_led(4, 2, _wake_pixel(3, 1))
  grid_led(5, 2, _wake_pixel(4, 1))
  grid_led(6, 2, _wake_pixel(5, 1))
  grid_led(7, 2, _wake_pixel(6, 1))
  grid_led(8, 2, _wake_pixel(7, 1))
  grid_led(1, 3, _wake_pixel(0, 2))
  grid_led(2, 3, _wake_pixel(1, 2))
  grid_led(3, 3, _wake_pixel(2, 2))
  grid_led(4, 3, _wake_pixel(3, 2))
  grid_led(5, 3, _wake_pixel(4, 2))
  grid_led(6, 3, _wake_pixel(5, 2))
  grid_led(7, 3, _wake_pixel(6, 2))
  grid_led(8, 3, _wake_pixel(7, 2))
  grid_led(1, 4, _wake_pixel(0, 3))
  grid_led(2, 4, _wake_pixel(1, 3))
  grid_led(3, 4, _wake_pixel(2, 3))
  grid_led(4, 4, _wake_pixel(3, 3))
  grid_led(5, 4, _wake_pixel(4, 3))
  grid_led(6, 4, _wake_pixel(5, 3))
  grid_led(7, 4, _wake_pixel(6, 3))
  grid_led(8, 4, _wake_pixel(7, 3))
  grid_led(1, 5, _wake_pixel(0, 4))
  grid_led(2, 5, _wake_pixel(1, 4))
  grid_led(3, 5, _wake_pixel(2, 4))
  grid_led(4, 5, _wake_pixel(3, 4))
  grid_led(5, 5, _wake_pixel(4, 4))
  grid_led(6, 5, _wake_pixel(5, 4))
  grid_led(7, 5, _wake_pixel(6, 4))
  grid_led(8, 5, _wake_pixel(7, 4))
  grid_led(1, 6, _wake_pixel(0, 5))
  grid_led(2, 6, _wake_pixel(1, 5))
  grid_led(3, 6, _wake_pixel(2, 5))
  grid_led(4, 6, _wake_pixel(3, 5))
  grid_led(5, 6, _wake_pixel(4, 5))
  grid_led(6, 6, _wake_pixel(5, 5))
  grid_led(7, 6, _wake_pixel(6, 5))
  grid_led(8, 6, _wake_pixel(7, 5))
  grid_led(1, 7, _wake_pixel(0, 6))
  grid_led(2, 7, _wake_pixel(1, 6))
  grid_led(3, 7, _wake_pixel(2, 6))
  grid_led(4, 7, _wake_pixel(3, 6))
  grid_led(5, 7, _wake_pixel(4, 6))
  grid_led(6, 7, _wake_pixel(5, 6))
  grid_led(7, 7, _wake_pixel(6, 6))
  grid_led(8, 7, _wake_pixel(7, 6))
  grid_led(1, 8, _wake_pixel(0, 7))
  grid_led(2, 8, _wake_pixel(1, 7))
  grid_led(3, 8, _wake_pixel(2, 7))
  grid_led(4, 8, _wake_pixel(3, 7))
  grid_led(5, 8, _wake_pixel(4, 7))
  grid_led(6, 8, _wake_pixel(5, 7))
  grid_led(7, 8, _wake_pixel(6, 7))
  grid_led(8, 8, _wake_pixel(7, 7))
  grid_refresh()
end

-- ---- dispatch ----
local _route = {}
_route[1 + 1*W] = handle_wake
_route[2 + 1*W] = handle_wake
_route[3 + 1*W] = handle_wake
_route[4 + 1*W] = handle_wake
_route[5 + 1*W] = handle_wake
_route[6 + 1*W] = handle_wake
_route[7 + 1*W] = handle_wake
_route[8 + 1*W] = handle_wake
_route[1 + 2*W] = handle_wake
_route[2 + 2*W] = handle_wake
_route[3 + 2*W] = handle_wake
_route[4 + 2*W] = handle_wake
_route[5 + 2*W] = handle_wake
_route[6 + 2*W] = handle_wake
_route[7 + 2*W] = handle_wake
_route[8 + 2*W] = handle_wake
_route[1 + 3*W] = handle_wake
_route[2 + 3*W] = handle_wake
_route[3 + 3*W] = handle_wake
_route[4 + 3*W] = handle_wake
_route[5 + 3*W] = handle_wake
_route[6 + 3*W] = handle_wake
_route[7 + 3*W] = handle_wake
_route[8 + 3*W] = handle_wake
_route[1 + 4*W] = handle_wake
_route[2 + 4*W] = handle_wake
_route[3 + 4*W] = handle_wake
_route[4 + 4*W] = handle_wake
_route[5 + 4*W] = handle_wake
_route[6 + 4*W] = handle_wake
_route[7 + 4*W] = handle_wake
_route[8 + 4*W] = handle_wake
_route[1 + 5*W] = handle_wake
_route[2 + 5*W] = handle_wake
_route[3 + 5*W] = handle_wake
_route[4 + 5*W] = handle_wake
_route[5 + 5*W] = handle_wake
_route[6 + 5*W] = handle_wake
_route[7 + 5*W] = handle_wake
_route[8 + 5*W] = handle_wake
_route[1 + 6*W] = handle_wake
_route[2 + 6*W] = handle_wake
_route[3 + 6*W] = handle_wake
_route[4 + 6*W] = handle_wake
_route[5 + 6*W] = handle_wake
_route[6 + 6*W] = handle_wake
_route[7 + 6*W] = handle_wake
_route[8 + 6*W] = handle_wake
_route[1 + 7*W] = handle_wake
_route[2 + 7*W] = handle_wake
_route[3 + 7*W] = handle_wake
_route[4 + 7*W] = handle_wake
_route[5 + 7*W] = handle_wake
_route[6 + 7*W] = handle_wake
_route[7 + 7*W] = handle_wake
_route[8 + 7*W] = handle_wake
_route[1 + 8*W] = handle_wake
_route[2 + 8*W] = handle_wake
_route[3 + 8*W] = handle_wake
_route[4 + 8*W] = handle_wake
_route[5 + 8*W] = handle_wake
_route[6 + 8*W] = handle_wake
_route[7 + 8*W] = handle_wake
_route[8 + 8*W] = handle_wake

function event_grid(x, y, z)
  local h = _route[x + y*W]
  if h then h(x, y, z) end
  redraw()
end

-- ---- init ----
grid_led_all(0)
redraw()
