/**
 * Conway's Game of Life — easter egg for monome iii grid.
 *
 * Self-contained Lua, ~180 lines, fits well under iii's 32 KB
 * script buffer and 512-byte per-line limit. Uses only the
 * standard iii Lua API (no codegen dependency).
 *
 * Layout:
 *   columns 1..15, rows 1..8  → canvas (toroidal wrap)
 *   column 16                  → control strip
 *
 * Right-column controls:
 *   (16,1) play / pause
 *   (16,2) step (single tick when paused)
 *   (16,3) speed cycle  — 10 Hz / 5 Hz / 2.5 Hz / 1.25 Hz
 *   (16,5) clear all
 *   (16,6) random sparse (~25% density)
 *   (16,7) random dense  (~50% density)
 *   (16,4) and (16,8) unused — dim glow marks the strip
 *
 * Canvas LED brightness:
 *   just born this tick   = 15 (flash)
 *   alive ≥ 1 tick        = 12
 *   just died this tick   = 5 (dim afterglow)
 *   dead                  = 0
 *
 * Triggered from the web UI by typing "life" anywhere outside an
 * input field.
 */

export function golLua(): string {
  return `-- conway's game of life — generated by monome-iii-studio
-- type "life" in the web UI to regenerate.

local W, H = grid_size_x(), grid_size_y()  -- 16, 8 on iii

-- Canvas occupies columns 1..(W-1); rightmost column is the
-- control strip. Sim wraps toroidally on the canvas only.
local CW = W - 1
local CTRL_X = W

-- ---- Control cell coords (right column) ----
local CTRL_PAUSE  = 1
local CTRL_STEP   = 2
local CTRL_SPEED  = 3
local CTRL_CLEAR  = 5
local CTRL_RAND_S = 6
local CTRL_RAND_D = 7

local function ctrl_at(x, y)
  if x ~= CTRL_X then return nil end
  if y == CTRL_PAUSE  then return 'pause'  end
  if y == CTRL_STEP   then return 'step'   end
  if y == CTRL_SPEED  then return 'speed'  end
  if y == CTRL_CLEAR  then return 'clear'  end
  if y == CTRL_RAND_S then return 'rand_s' end
  if y == CTRL_RAND_D then return 'rand_d' end
  return 'unused'  -- y=4 or y=8: dim spacer
end

-- ---- LED brightness ----
local LED_LIVE     = 12
local LED_BORN     = 15
local LED_DYING    = 5
local LED_DEAD     = 0
local LED_UNUSED   = 1   -- dim spacer in control strip
local LED_CTRL     = 4   -- idle control button
local LED_PAUSED   = 14  -- pause button when sim is paused
local LED_RUNNING  = 5   -- pause button when sim is running

-- ---- State ----
-- alive[y][x] uses 4 values:
--   0  = dead (long)
--   1  = just born this tick (LED 15)
--   2  = alive (LED 12)
--  -1  = just died this tick (LED 5 afterglow)
local alive = {}
for y = 1, H do
  alive[y] = {}
  for x = 1, CW do
    alive[y][x] = 0
  end
end

local paused = true  -- start paused so user can draw an initial pattern

-- Speed cycle: tick period in seconds. Indices 1..4.
local SPEEDS = { 0.1, 0.2, 0.4, 0.8 }
local speed_idx = 2  -- 5 Hz default
local tick_period = SPEEDS[speed_idx]

local _metro  -- forward decl so event_grid can adjust _metro.time

-- ---- Helpers ----
local function is_alive(y, x)
  -- True if cell counts as alive THIS tick (states 1 or 2).
  local v = alive[y][x]
  return v == 1 or v == 2
end

local function neighbors(x, y)
  -- Toroidal Moore neighborhood on the CW × H canvas.
  local n = 0
  for dy = -1, 1 do
    for dx = -1, 1 do
      if not (dx == 0 and dy == 0) then
        local nx = ((x - 1 + dx) % CW) + 1
        local ny = ((y - 1 + dy) % H) + 1
        if is_alive(ny, nx) then n = n + 1 end
      end
    end
  end
  return n
end

local function step()
  -- Apply Conway B3/S23 rules. Build into a fresh table so the
  -- update is simultaneous (no in-place corruption mid-pass).
  local new = {}
  for y = 1, H do
    new[y] = {}
    for x = 1, CW do
      local was = is_alive(y, x)
      local n = neighbors(x, y)
      local will
      if was then
        will = (n == 2 or n == 3)
      else
        will = (n == 3)
      end
      if will and not was then
        new[y][x] = 1   -- birth
      elseif will then
        new[y][x] = 2   -- survival
      elseif was then
        new[y][x] = -1  -- death
      else
        new[y][x] = 0   -- still dead
      end
    end
  end
  alive = new
end

-- ---- LED render ----
local function redraw()
  -- Canvas
  for y = 1, H do
    for x = 1, CW do
      local v = alive[y][x]
      local b = LED_DEAD
      if     v == 1  then b = LED_BORN
      elseif v == 2  then b = LED_LIVE
      elseif v == -1 then b = LED_DYING
      end
      grid_led(x, y, b)
    end
  end
  -- Control strip
  for y = 1, H do
    local kind = ctrl_at(CTRL_X, y)
    local b = LED_UNUSED
    if kind == 'pause' then
      b = paused and LED_PAUSED or LED_RUNNING
    elseif kind == 'step' then
      b = paused and LED_CTRL or 1  -- only meaningful while paused
    elseif kind == 'speed' then
      -- Brightness scales with speed: faster = brighter.
      b = 2 + (5 - speed_idx) * 2  -- speeds 1..4 → 10, 8, 6, 4
    elseif kind == 'clear' or kind == 'rand_s' or kind == 'rand_d' then
      b = LED_CTRL
    end
    grid_led(CTRL_X, y, b)
  end
  grid_refresh()
end

-- ---- Helpers for control actions ----
local function fill_random(density)
  for y = 1, H do
    for x = 1, CW do
      if math.random() < density then
        alive[y][x] = 1
      else
        alive[y][x] = 0
      end
    end
  end
end

local function clear_all()
  for y = 1, H do
    for x = 1, CW do
      alive[y][x] = 0
    end
  end
end

-- ---- Input ----
function event_grid(x, y, z)
  if z ~= 1 then return end  -- only react on press, not release
  local kind = ctrl_at(x, y)
  if kind == 'pause' then
    paused = not paused
  elseif kind == 'step' then
    if paused then step() end
  elseif kind == 'speed' then
    speed_idx = (speed_idx % #SPEEDS) + 1
    tick_period = SPEEDS[speed_idx]
    if _metro then _metro.time = tick_period end
  elseif kind == 'clear' then
    clear_all()
  elseif kind == 'rand_s' then
    fill_random(0.25)
  elseif kind == 'rand_d' then
    fill_random(0.5)
  elseif kind == 'unused' then
    -- spacer cells: do nothing
  else
    -- canvas cell: toggle alive/dead
    if is_alive(y, x) then
      alive[y][x] = -1  -- mark "just died" so it shows the afterglow
    else
      alive[y][x] = 1   -- mark "just born" so it shows the bright flash
    end
  end
  redraw()
end

-- ---- Tick metro ----
local function tick_fn()
  if not paused then
    step()
    redraw()
  end
end

-- ---- Init ----
math.randomseed(math.floor(get_time() * 1000))
grid_led_all(0)

_metro = metro.init(tick_fn, tick_period)
_metro:start()

redraw()
`;
}
