/**
 * Conway's Game of Life — easter egg for monome iii grid.
 *
 * Self-contained Lua, fits well under iii's 32 KB script buffer
 * and 512-byte per-line limit. Uses only the standard iii Lua
 * API (no codegen dependency).
 *
 * Layout:
 *   columns 1..15, rows 1..8  → canvas (toroidal wrap)
 *   column 16                  → control strip
 *
 * Right-column controls:
 *   (16,1) play / pause
 *   (16,2) step (single tick when paused)
 *   (16,3) speed cycle      — column-scan rate (4 levels)
 *   (16,4) scale cycle      — D Dorian / Aeolian / Phrygian / Major
 *   (16,5) clear all
 *   (16,6) random sparse (~25% density)
 *   (16,7) random dense  (~50% density)
 *   (16,8) sim-rate cycle   — advance sim every 1 / 2 / 4 full scans
 *
 * Music — column scan ("piano roll"):
 *   Each tick scans one column, left → right, wrapping. Alive
 *   cells in the current column trigger note-on (staccato), with
 *   y → pitch via the active scale. Notes are STACKED IN THIRDS —
 *   adjacent y values are a 3rd apart in the scale, so vertically
 *   connected cells sound as diatonic chord tones:
 *     · 3 cells touching → a triad (C-E-G, A-C-E, etc.)
 *     · 4 cells → a 7th chord
 *     · 5+ cells → 9th / 11th extensions
 *   GoL patterns naturally cluster vertically; this layout turns
 *   clumps into proper chords instead of dissonant 2nd-stacks.
 *   Notes from the previous column release before the new ones
 *   fire, giving a clean stepped-arpeggio feel.
 *
 * Sim is INCREMENTAL across the scan to avoid a scan-wrap stutter.
 *   The naive version ran a full Conway step on the wrap tick,
 *   which made that single tick heavier than the others (≈120
 *   cells × 8 neighbour reads + redraw). The metro then fired
 *   the next tick late, audibly stretching col 15's notes.
 *   Instead we double-buffer the grid (alive_a / alive_b),
 *   compute one row of the next state per tick over the first
 *   8 ticks of each scan, and commit the swap atomically at the
 *   next wrap. Per-tick work is now constant; wrap is a pointer
 *   assignment.
 *
 * Canvas LED:
 *   just born this tick      = 15 (flash)
 *   alive ≥ 1 tick           = 12
 *   just died this tick      = 5  (afterglow)
 *   dead                     = 0
 *   current scan column overrides:
 *     alive cell             = 15 (brightest)
 *     dead cell              = 2  (dim scan trail)
 *
 * Triggered from the web UI by typing "life" anywhere outside
 * an input field.
 */

export function golLua(): string {
  return `-- conway's game of life — generated by monome-iii-studio
-- type "life" in the web UI to regenerate.

local W, H = grid_size_x(), grid_size_y()  -- 16, 8 on iii

-- Canvas occupies columns 1..(W-1); rightmost column is the
-- control strip. Sim wraps toroidally on the canvas only.
local CW = W - 1
local CTRL_X = W

-- ---- Control cell coords (right column) ----
local CTRL_PAUSE  = 1
local CTRL_STEP   = 2
local CTRL_SPEED  = 3
local CTRL_SCALE  = 4
local CTRL_CLEAR  = 5
local CTRL_RAND_S = 6
local CTRL_RAND_D = 7
local CTRL_SIMR   = 8

local function ctrl_at(x, y)
  if x ~= CTRL_X then return nil end
  if y == CTRL_PAUSE  then return 'pause'  end
  if y == CTRL_STEP   then return 'step'   end
  if y == CTRL_SPEED  then return 'speed'  end
  if y == CTRL_SCALE  then return 'scale'  end
  if y == CTRL_CLEAR  then return 'clear'  end
  if y == CTRL_RAND_S then return 'rand_s' end
  if y == CTRL_RAND_D then return 'rand_d' end
  if y == CTRL_SIMR   then return 'simr'   end
  return nil
end

-- ---- LED brightness ----
local LED_LIVE     = 12
local LED_BORN     = 15
local LED_DYING    = 5
local LED_DEAD     = 0
local LED_SCAN_DIM = 2   -- dead cell at current scan column
local LED_CTRL     = 4
local LED_PAUSED   = 14
local LED_RUNNING  = 5

-- ---- Sim state (double-buffered) ----
-- Each cell uses 4 values:
--   0  = dead (long)
--   1  = just born this tick (LED 15)
--   2  = alive (LED 12)
--  -1  = just died this tick (LED 5 afterglow)
local alive_a, alive_b = {}, {}
for y = 1, H do
  alive_a[y] = {}
  alive_b[y] = {}
  for x = 1, CW do
    alive_a[y][x] = 0
    alive_b[y][x] = 0
  end
end
local alive = alive_a

-- Incremental step state. step_dst is the buffer being filled by
-- the next-state computation; step_row is the row to compute on
-- the next tick. nil / 0 means no step in progress.
local step_dst = nil
local step_row = 0

local paused = true  -- start paused so user can draw an initial pattern

-- Speed cycle: column-scan period in seconds.
local SPEEDS = { 0.08, 0.15, 0.25, 0.5 }
local speed_idx = 2

-- Sim-rate cycle: advance sim every N full scans.
local SIM_RATES = { 1, 2, 4 }
local sim_rate_idx = 1

-- ---- Music ----
local MIDI_CH = 1
local NOTE_VEL = 60

-- Pitch tables, indexed by y (1 = top of grid → highest pitch).
-- Notes are STACKED IN THIRDS: y → 1, 3, 5, 7, 9, 11, 13, 15 of the
-- scale. Vertically-connected cells therefore sound as diatonic
-- chord tones, e.g. 3 cells touching = a triad (C-E-G), 4 cells = a
-- 7th chord, 5+ cells = 9th / 11th. GoL patterns naturally cluster
-- vertically, so this turns clumps into proper chords instead of
-- the 2nd-stacks the prior consecutive-scale layout produced.
--
-- Order (top = highest): root+2oct, 13th, 11th, 9th, 7th, 5th, 3rd, root.
local SCALES = {
  { 62, 59, 55, 52, 48, 45, 41, 38 },  -- 1 dorian
  { 62, 58, 55, 52, 48, 45, 41, 38 },  -- 2 aeolian (Bb instead of B)
  { 62, 58, 55, 51, 48, 45, 41, 38 },  -- 3 phrygian (Eb + Bb)
  { 62, 59, 55, 52, 49, 45, 42, 38 },  -- 4 major (F#, C#)
}
local scale_idx = 1

-- ---- Scan state ----
local scan_col = 1
local sim_counter = 0  -- counts full scans since last sim trigger

-- Notes triggered last tick — released before the next column
-- fires so each step is a clean staccato chord.
local pending_notes = {}

local _metro

-- ---- Helpers ----
local function is_alive_now(y, x)
  -- Reads from current state (alive); state values 1 or 2 = alive.
  local v = alive[y][x]
  return v == 1 or v == 2
end

-- ---- Incremental step ----
-- Compute a single row of the next state from src into dst, with
-- toroidal wrap and standard B3/S23 rules. Inlined neighbour
-- check + cached row references = ~5x faster than a per-cell
-- function call would be.
local function compute_row(y, src, dst)
  local r_above = src[((y - 2) % H) + 1]
  local r_curr  = src[y]
  local r_below = src[(y % H) + 1]
  local r_new   = dst[y]
  for x = 1, CW do
    local xl = ((x - 2) % CW) + 1
    local xr = (x % CW) + 1
    -- Inline neighbour count. State 1 (born) and 2 (alive) count.
    local n = 0
    local v
    v = r_above[xl]; if v == 1 or v == 2 then n = n + 1 end
    v = r_above[x];  if v == 1 or v == 2 then n = n + 1 end
    v = r_above[xr]; if v == 1 or v == 2 then n = n + 1 end
    v = r_curr[xl];  if v == 1 or v == 2 then n = n + 1 end
    v = r_curr[xr];  if v == 1 or v == 2 then n = n + 1 end
    v = r_below[xl]; if v == 1 or v == 2 then n = n + 1 end
    v = r_below[x];  if v == 1 or v == 2 then n = n + 1 end
    v = r_below[xr]; if v == 1 or v == 2 then n = n + 1 end
    v = r_curr[x]
    local was = (v == 1 or v == 2)
    local will
    if was then will = (n == 2 or n == 3) else will = (n == 3) end
    if will then
      r_new[x] = was and 2 or 1
    else
      r_new[x] = was and -1 or 0
    end
  end
end

local function start_step()
  step_dst = (alive == alive_a) and alive_b or alive_a
  step_row = 1
end

local function abort_step()
  step_dst = nil
  step_row = 0
end

local function commit_step()
  -- Atomic-ish: just retarget the 'alive' pointer. The just-
  -- finished buffer becomes current; the previously current
  -- buffer is now eligible to be the next step_dst.
  if step_dst and step_row > H then
    alive = step_dst
    step_dst = nil
    step_row = 0
    return true
  end
  return false
end

-- Run synchronously: a paused single-step. Cheap because it's
-- only invoked manually; we don't care about per-tick latency
-- here (it's between two ticks, not inside one).
local function step_now()
  local dst = (alive == alive_a) and alive_b or alive_a
  for y = 1, H do
    compute_row(y, alive, dst)
  end
  alive = dst
  -- Cancel any pending incremental step — its source is now stale.
  abort_step()
end

-- ---- Music plumbing ----
local function release_pending()
  for i = 1, #pending_notes do
    midi_note_off(pending_notes[i], 0, MIDI_CH)
  end
  pending_notes = {}
end

local function trigger_column(col)
  local pitch = SCALES[scale_idx]
  for y = 1, H do
    if is_alive_now(y, col) then
      local note = pitch[y]
      midi_note_on(note, NOTE_VEL, MIDI_CH)
      pending_notes[#pending_notes + 1] = note
    end
  end
end

-- ---- LED render ----
local function redraw()
  local show_scan = not paused
  for y = 1, H do
    for x = 1, CW do
      local b
      if show_scan and x == scan_col then
        b = is_alive_now(y, x) and LED_BORN or LED_SCAN_DIM
      else
        local v = alive[y][x]
        if     v == 1  then b = LED_BORN
        elseif v == 2  then b = LED_LIVE
        elseif v == -1 then b = LED_DYING
        else                b = LED_DEAD
        end
      end
      grid_led(x, y, b)
    end
  end
  for y = 1, H do
    local kind = ctrl_at(CTRL_X, y)
    local b = 1
    if kind == 'pause' then
      b = paused and LED_PAUSED or LED_RUNNING
    elseif kind == 'step' then
      b = paused and LED_CTRL or 1
    elseif kind == 'speed' then
      b = 2 + (5 - speed_idx) * 2
    elseif kind == 'scale' then
      local SCALE_LED = { 7, 5, 3, 11 }
      b = SCALE_LED[scale_idx]
    elseif kind == 'clear' then
      b = 3
    elseif kind == 'rand_s' then
      b = 5
    elseif kind == 'rand_d' then
      b = 8
    elseif kind == 'simr' then
      local SIMR_LED = { 11, 6, 3 }
      b = SIMR_LED[sim_rate_idx]
    end
    grid_led(CTRL_X, y, b)
  end
  grid_refresh()
end

-- ---- Control actions ----
local function fill_random(density)
  release_pending()
  abort_step()
  for y = 1, H do
    for x = 1, CW do
      if math.random() < density then
        alive[y][x] = 1
      else
        alive[y][x] = 0
      end
    end
  end
end

local function clear_all()
  release_pending()
  abort_step()
  for y = 1, H do
    for x = 1, CW do
      alive[y][x] = 0
    end
  end
end

-- ---- Input ----
function event_grid(x, y, z)
  if z ~= 1 then return end
  local kind = ctrl_at(x, y)
  if kind == 'pause' then
    paused = not paused
    if paused then release_pending() end
  elseif kind == 'step' then
    if paused then step_now() end
  elseif kind == 'speed' then
    speed_idx = (speed_idx % #SPEEDS) + 1
    if _metro then _metro.time = SPEEDS[speed_idx] end
  elseif kind == 'scale' then
    release_pending()
    scale_idx = (scale_idx % #SCALES) + 1
  elseif kind == 'clear' then
    clear_all()
  elseif kind == 'rand_s' then
    fill_random(0.25)
  elseif kind == 'rand_d' then
    fill_random(0.5)
  elseif kind == 'simr' then
    sim_rate_idx = (sim_rate_idx % #SIM_RATES) + 1
    sim_counter = 0
  elseif kind == nil then
    -- canvas cell: toggle alive/dead. Abort any in-flight step,
    -- since its source state is now stale.
    abort_step()
    if is_alive_now(y, x) then
      alive[y][x] = -1
    else
      alive[y][x] = 1
    end
  end
  redraw()
end

-- ---- Tick ----
local function tick_fn()
  -- 1. Always release notes from the previous tick. Constant cost.
  release_pending()

  if paused then
    redraw()
    return
  end

  -- 2. Trigger note-ons for current column. Cost ≤ 8 MIDI calls.
  trigger_column(scan_col)

  -- 3. Advance scan column. On wrap, possibly commit the
  --    finished step and possibly schedule a new one. These are
  --    all O(1).
  scan_col = scan_col + 1
  if scan_col > CW then
    scan_col = 1
    commit_step()
    sim_counter = sim_counter + 1
    if sim_counter >= SIM_RATES[sim_rate_idx] then
      sim_counter = 0
      start_step()
    end
  end

  -- 4. Compute one row of the in-flight next-state buffer, if any.
  --    This is the "expensive" work, now spread evenly across the
  --    next 8 ticks of the scan instead of dumped onto the wrap.
  if step_dst and step_row <= H then
    compute_row(step_row, alive, step_dst)
    step_row = step_row + 1
  end

  redraw()
end

-- ---- Init ----
math.randomseed(math.floor(get_time() * 1000))
grid_led_all(0)

_metro = metro.init(tick_fn, SPEEDS[speed_idx])
_metro:start()

redraw()
`;
}
