/**
 * snake — easter egg game for monome iii grid.
 *
 * Self-contained Lua, ~200 lines, fits in flash, uses only the
 * standard iii Lua API (no dependency on our recipe codegen
 * infrastructure). The game lives on the full 16×8 grid; D-pad in
 * the bottom-right corner uses 4 cells in a classic + cross:
 *
 *      . . . . . . . . . . . . . . ↑ .
 *      . . . . . . . . . . . . . ← . →
 *      . . . . . . . . . . . . . . ↓ .
 *
 * Music: each apple eaten plays the next chord in a random walk over
 * a D-minor harmonic-progression graph (so the sequence sounds like
 * an actual sad piano piece, not a static scale). Death plays a
 * sustained tonic Dm. The metro running at 50 Hz schedules snake
 * movement, apple blink, d-pad press feedback, and chord note-off.
 *
 * Triggered from the web UI by typing "snake" anywhere outside an
 * input field.
 */

export function snakeLua(): string {
  return `-- snake easter egg — generated by monome-iii-studio
-- type "snake" in the web UI to regenerate.

local W, H = grid_size_x(), grid_size_y()

-- ---- D-pad (1-indexed) -------------------------------------------
-- Classic + cross in the bottom-right corner of the grid.
local DPAD = {
  up    = {x=15, y=6},
  left  = {x=14, y=7},
  right = {x=16, y=7},
  down  = {x=15, y=8},
}

-- ---- LED brightness levels ---------------------------------------
local LED_HEAD       = 15
local LED_BODY_MAX   = 13
local LED_BODY_MIN   = 5
local LED_APPLE_HI   = 15
local LED_APPLE_LO   = 7
local LED_DPAD_IDLE  = 4
local LED_DPAD_DIR   = 8
local LED_DPAD_PRESS = 12
local LED_DEATH      = 9
local LED_OFF        = 0

-- ---- Music: D-minor harmonic progression ----------------------
-- Each chord is voiced as bass note + triad in the next octave so it
-- reads as a real chord stab, not a thin triad. Notes are MIDI #s.
local MIDI_CH = 1

local CHORDS = {
  -- name      bass  triad
  i      = { 50, 62, 65, 69 },  -- Dm   (i, tonic — saddest, home)
  ii_dim = { 52, 64, 67, 70 },  -- E°   (ii°, tense)
  III    = { 53, 65, 69, 72 },  -- F    (III, relative major — wistful)
  iv     = { 55, 67, 70, 74 },  -- Gm   (iv, plaintive subdominant)
  v      = { 57, 69, 72, 76 },  -- Am   (v, modal/Aeolian dominant)
  V      = { 57, 69, 73, 76 },  -- A    (V, harmonic-minor dominant)
  VI     = { 58, 70, 74, 77 },  -- Bb   (VI, mournful submediant)
  VII    = { 60, 72, 76, 79 },  -- C    (VII, hopeful relative)
}

-- Transition graph: from each chord, which chords can plausibly come
-- next. The walker picks one at random, so the progression varies on
-- every play but always sounds like a coherent minor-key piece.
local NEXT_CHORD = {
  i      = { 'iv', 'v', 'V', 'VI', 'VII', 'III', 'ii_dim' },
  ii_dim = { 'V', 'v', 'i' },
  III    = { 'VI', 'VII', 'iv', 'i' },
  iv     = { 'i', 'VII', 'v', 'V', 'III' },
  v      = { 'i', 'iv', 'VI' },
  V      = { 'i', 'VI', 'iv' },
  VI     = { 'III', 'iv', 'VII', 'i', 'ii_dim' },
  VII    = { 'III', 'VI', 'i' },
}

-- ---- Direction helpers ------------------------------------------
local DIR_VEC = {
  up    = {0, -1},
  down  = {0,  1},
  left  = {-1, 0},
  right = {1,  0},
}
local OPP = { up='down', down='up', left='right', right='left' }

-- ---- Tunables (in master ticks of TICK_S each) -----------------
local TICK_S            = 0.05
local SNAKE_MOVE_TICKS  = 4   -- 0.20 s/move (5 moves/sec)
local APPLE_BLINK_TICKS = 8   -- 0.40 s
local DPAD_PRESS_TICKS  = 4   -- 0.20 s
local CHORD_HOLD_TICKS  = 8   -- 0.40 s — let each chord ring
local DEATH_HOLD_TICKS  = 16  -- 0.80 s — sustained tonic on death
local DEATH_TICKS       = 24  -- 1.20 s of flashing before reset

-- ---- Game state -------------------------------------------------
local snake          -- list of {x, y}, head first
local dir
local next_dir
local apple
local length
local alive
local death_frame
local pressed_dir
local pressed_at_tick
local active_notes      -- list of MIDI #s currently held (full chord)
local note_off_tick
local apple_phase
local tick_count
local current_chord     -- name of last-played chord (graph walker state)

-- ---- Helpers ----------------------------------------------------
local function is_dpad(x, y)
  for _, c in pairs(DPAD) do
    if c.x == x and c.y == y then return true end
  end
  return false
end

-- The D-pad is a + cross, so its empty centre cell at (15, 7) is
-- surrounded by D-pad cells on all four sides — any snake trying to
-- enter it dies first. To avoid spawning unreachable apples there,
-- and to give the player's thumb some breathing room around the
-- controls, the whole bottom-right 4×4 block is an apple-spawn no-go
-- zone (the snake can still WALK through the non-D-pad cells inside
-- it; we only restrict where apples appear).
local function is_apple_excluded(x, y)
  return x >= W - 3 and y >= H - 3
end

local function snake_occupies(x, y)
  for _, s in ipairs(snake) do
    if s.x == x and s.y == y then return true end
  end
  return false
end

local function spawn_apple()
  for _ = 1, 300 do
    local x = math.random(1, W)
    local y = math.random(1, H)
    if not is_apple_excluded(x, y) and not snake_occupies(x, y) then
      apple = {x=x, y=y}
      return
    end
  end
  apple = nil
end

local function notes_off()
  if active_notes then
    for _, n in ipairs(active_notes) do
      midi_note_off(n, 0, MIDI_CH)
    end
  end
  active_notes = {}
end

local function play_chord(notes, hold, vel)
  notes_off()
  vel = vel or 100
  active_notes = {}
  for _, n in ipairs(notes) do
    midi_note_on(n, vel, MIDI_CH)
    table.insert(active_notes, n)
  end
  note_off_tick = tick_count + hold
end

-- Pick the next chord by random walk through the transition graph.
local function next_progression_chord()
  local options = NEXT_CHORD[current_chord] or NEXT_CHORD.i
  return options[math.random(1, #options)]
end

local function reset_game()
  snake = {}
  for i = 1, 4 do
    table.insert(snake, {x = 5 - i, y = 4})  -- head (4,4) facing right
  end
  dir = 'right'
  next_dir = 'right'
  alive = true
  length = 4
  death_frame = 0
  spawn_apple()
  apple_phase = 0
  -- Reset progression to the tonic so each new game starts on home.
  current_chord = 'i'
  play_chord(CHORDS.i, CHORD_HOLD_TICKS, 80)
end

local function die()
  alive = false
  death_frame = 0
  -- Sustained tonic Dm on death — soft + long, the saddest landing.
  play_chord(CHORDS.i, DEATH_HOLD_TICKS, 70)
  current_chord = 'i'
end

local function move_snake()
  if next_dir ~= OPP[dir] then dir = next_dir end

  local d = DIR_VEC[dir]
  local head = snake[1]
  local nx, ny = head.x + d[1], head.y + d[2]

  if nx < 1 or nx > W or ny < 1 or ny > H then return die() end
  if is_dpad(nx, ny) then return die() end
  for i = 1, #snake - 1 do
    if snake[i].x == nx and snake[i].y == ny then return die() end
  end

  table.insert(snake, 1, {x = nx, y = ny})

  if apple and nx == apple.x and ny == apple.y then
    length = length + 1
    -- Walk one step in the progression graph and play that chord.
    current_chord = next_progression_chord()
    play_chord(CHORDS[current_chord], CHORD_HOLD_TICKS)
    spawn_apple()
  else
    table.remove(snake)
  end
end

-- ---- Render -----------------------------------------------------
local function redraw()
  for x = 1, W do
    for y = 1, H do
      grid_led(x, y, LED_OFF)
    end
  end

  for d_name, c in pairs(DPAD) do
    local v = LED_DPAD_IDLE
    if alive and dir == d_name then v = LED_DPAD_DIR end
    if pressed_dir == d_name and (tick_count - pressed_at_tick) < DPAD_PRESS_TICKS then
      v = LED_DPAD_PRESS
    end
    grid_led(c.x, c.y, v)
  end

  if alive then
    local n = #snake
    for i, s in ipairs(snake) do
      local v
      if i == 1 then
        v = LED_HEAD
      else
        local fade = (i - 1) / math.max(1, n - 1)
        v = math.floor(LED_BODY_MAX - fade * (LED_BODY_MAX - LED_BODY_MIN))
      end
      grid_led(s.x, s.y, v)
    end
    if apple then
      local v = (apple_phase == 0) and LED_APPLE_HI or LED_APPLE_LO
      grid_led(apple.x, apple.y, v)
    end
  else
    -- death flash: snake blinks at LED_DEATH for DEATH_TICKS ticks
    local on = (math.floor(death_frame / 4) % 2) == 0
    for _, s in ipairs(snake) do
      grid_led(s.x, s.y, on and LED_DEATH or LED_OFF)
    end
  end

  grid_refresh()
end

-- ---- Master tick ------------------------------------------------
local function tick()
  tick_count = tick_count + 1

  if active_notes and #active_notes > 0 and tick_count >= note_off_tick then
    notes_off()
  end

  if tick_count % APPLE_BLINK_TICKS == 0 then
    apple_phase = 1 - apple_phase
  end

  if alive then
    if tick_count % SNAKE_MOVE_TICKS == 0 then
      move_snake()
    end
  else
    death_frame = death_frame + 1
    if death_frame >= DEATH_TICKS then
      reset_game()
    end
  end

  redraw()
end

-- ---- Input ------------------------------------------------------
function event_grid(x, y, z)
  if z ~= 1 then return end

  local matched = nil
  for d_name, c in pairs(DPAD) do
    if c.x == x and c.y == y then matched = d_name end
  end
  if not matched then return end

  if not alive then
    reset_game()
    return
  end

  -- ignore opposite direction (would self-collide on next tick)
  if matched ~= OPP[dir] then
    next_dir = matched
  end
  pressed_dir = matched
  pressed_at_tick = tick_count
end

-- ---- Bootstrap --------------------------------------------------
math.randomseed(math.floor(get_time() * 1000))
tick_count = 0
active_notes = {}
note_off_tick = 0
pressed_dir = nil
pressed_at_tick = 0
apple_phase = 0
current_chord = 'i'
grid_led_all(0)
reset_game()

local _snake_metro = metro.init(tick, TICK_S)
_snake_metro:start()

redraw()
`;
}
