/**
 * snake — easter egg game for monome iii grid.
 *
 * Self-contained Lua, ~200 lines, fits in flash, uses only the
 * standard iii Lua API (no dependency on our recipe codegen
 * infrastructure). The game lives on the full 16×8 grid; D-pad in
 * the bottom-right corner uses 4 cells in a classic + cross:
 *
 *      . . . . . . . . . . . . . . ↑ .
 *      . . . . . . . . . . . . . ← . →
 *      . . . . . . . . . . . . . . ↓ .
 *
 * Music: each apple eaten plays the next degree of the D minor
 * pentatonic across two octaves; death plays a low D. Apple blinks
 * via a single shared metro running at 50 Hz that schedules snake
 * movement, apple blink, d-pad press feedback, and note-off.
 *
 * Triggered from the web UI by typing "snake" anywhere outside an
 * input field.
 */

export function snakeLua(): string {
  return `-- snake easter egg — generated by monome-iii-studio
-- type "snake" in the web UI to regenerate.

local W, H = grid_size_x(), grid_size_y()

-- ---- D-pad (1-indexed) -------------------------------------------
-- Classic + cross in the bottom-right corner of the grid.
local DPAD = {
  up    = {x=15, y=6},
  left  = {x=14, y=7},
  right = {x=16, y=7},
  down  = {x=15, y=8},
}

-- ---- LED brightness levels ---------------------------------------
local LED_HEAD       = 15
local LED_BODY_MAX   = 13
local LED_BODY_MIN   = 5
local LED_APPLE_HI   = 15
local LED_APPLE_LO   = 7
local LED_DPAD_IDLE  = 4
local LED_DPAD_DIR   = 8
local LED_DPAD_PRESS = 12
local LED_DEATH      = 9
local LED_OFF        = 0

-- ---- Music ------------------------------------------------------
-- D minor pentatonic, two octaves, ascends as the snake grows.
local SCALE = {62, 65, 67, 69, 72, 74, 77, 79, 81, 84, 86, 89}
local MIDI_CH = 1

-- ---- Direction helpers ------------------------------------------
local DIR_VEC = {
  up    = {0, -1},
  down  = {0,  1},
  left  = {-1, 0},
  right = {1,  0},
}
local OPP = { up='down', down='up', left='right', right='left' }

-- ---- Tunables (in master ticks of TICK_S each) -----------------
local TICK_S            = 0.05
local SNAKE_MOVE_TICKS  = 4   -- 0.20 s/move (5 moves/sec)
local APPLE_BLINK_TICKS = 8   -- 0.40 s
local DPAD_PRESS_TICKS  = 4   -- 0.20 s
local NOTE_HOLD_TICKS   = 3   -- 0.15 s
local DEATH_TICKS       = 24  -- 1.20 s of flashing before reset

-- ---- Game state -------------------------------------------------
local snake          -- list of {x, y}, head first
local dir
local next_dir
local apple
local length
local alive
local death_frame
local pressed_dir
local pressed_at_tick
local active_note
local note_off_tick
local apple_phase
local tick_count

-- ---- Helpers ----------------------------------------------------
local function is_dpad(x, y)
  for _, c in pairs(DPAD) do
    if c.x == x and c.y == y then return true end
  end
  return false
end

local function snake_occupies(x, y)
  for _, s in ipairs(snake) do
    if s.x == x and s.y == y then return true end
  end
  return false
end

local function spawn_apple()
  for _ = 1, 300 do
    local x = math.random(1, W)
    local y = math.random(1, H)
    if not is_dpad(x, y) and not snake_occupies(x, y) then
      apple = {x=x, y=y}
      return
    end
  end
  apple = nil
end

local function note_off_active()
  if active_note and active_note >= 0 then
    midi_note_off(active_note, 0, MIDI_CH)
    active_note = -1
  end
end

local function play_note(m, hold)
  note_off_active()
  midi_note_on(m, 100, MIDI_CH)
  active_note = m
  note_off_tick = tick_count + hold
end

local function reset_game()
  snake = {}
  for i = 1, 4 do
    table.insert(snake, {x = 5 - i, y = 4})  -- head (4,4) facing right
  end
  dir = 'right'
  next_dir = 'right'
  alive = true
  length = 4
  death_frame = 0
  spawn_apple()
  apple_phase = 0
  play_note(SCALE[1], 4)
end

local function die()
  alive = false
  death_frame = 0
  play_note(50, 6)  -- low D
end

local function move_snake()
  if next_dir ~= OPP[dir] then dir = next_dir end

  local d = DIR_VEC[dir]
  local head = snake[1]
  local nx, ny = head.x + d[1], head.y + d[2]

  if nx < 1 or nx > W or ny < 1 or ny > H then return die() end
  if is_dpad(nx, ny) then return die() end
  for i = 1, #snake - 1 do
    if snake[i].x == nx and snake[i].y == ny then return die() end
  end

  table.insert(snake, 1, {x = nx, y = ny})

  if apple and nx == apple.x and ny == apple.y then
    length = length + 1
    local idx = ((length - 4) % #SCALE) + 1
    play_note(SCALE[idx], NOTE_HOLD_TICKS)
    spawn_apple()
  else
    table.remove(snake)
  end
end

-- ---- Render -----------------------------------------------------
local function redraw()
  for x = 1, W do
    for y = 1, H do
      grid_led(x, y, LED_OFF)
    end
  end

  for d_name, c in pairs(DPAD) do
    local v = LED_DPAD_IDLE
    if alive and dir == d_name then v = LED_DPAD_DIR end
    if pressed_dir == d_name and (tick_count - pressed_at_tick) < DPAD_PRESS_TICKS then
      v = LED_DPAD_PRESS
    end
    grid_led(c.x, c.y, v)
  end

  if alive then
    local n = #snake
    for i, s in ipairs(snake) do
      local v
      if i == 1 then
        v = LED_HEAD
      else
        local fade = (i - 1) / math.max(1, n - 1)
        v = math.floor(LED_BODY_MAX - fade * (LED_BODY_MAX - LED_BODY_MIN))
      end
      grid_led(s.x, s.y, v)
    end
    if apple then
      local v = (apple_phase == 0) and LED_APPLE_HI or LED_APPLE_LO
      grid_led(apple.x, apple.y, v)
    end
  else
    -- death flash: snake blinks at LED_DEATH for DEATH_TICKS ticks
    local on = (math.floor(death_frame / 4) % 2) == 0
    for _, s in ipairs(snake) do
      grid_led(s.x, s.y, on and LED_DEATH or LED_OFF)
    end
  end

  grid_refresh()
end

-- ---- Master tick ------------------------------------------------
local function tick()
  tick_count = tick_count + 1

  if active_note and active_note >= 0 and tick_count >= note_off_tick then
    note_off_active()
  end

  if tick_count % APPLE_BLINK_TICKS == 0 then
    apple_phase = 1 - apple_phase
  end

  if alive then
    if tick_count % SNAKE_MOVE_TICKS == 0 then
      move_snake()
    end
  else
    death_frame = death_frame + 1
    if death_frame >= DEATH_TICKS then
      reset_game()
    end
  end

  redraw()
end

-- ---- Input ------------------------------------------------------
function event_grid(x, y, z)
  if z ~= 1 then return end

  local matched = nil
  for d_name, c in pairs(DPAD) do
    if c.x == x and c.y == y then matched = d_name end
  end
  if not matched then return end

  if not alive then
    reset_game()
    return
  end

  -- ignore opposite direction (would self-collide on next tick)
  if matched ~= OPP[dir] then
    next_dir = matched
  end
  pressed_dir = matched
  pressed_at_tick = tick_count
end

-- ---- Bootstrap --------------------------------------------------
math.randomseed(math.floor(get_time() * 1000))
tick_count = 0
active_note = -1
note_off_tick = 0
pressed_dir = nil
pressed_at_tick = 0
apple_phase = 0
grid_led_all(0)
reset_game()

local _snake_metro = metro.init(tick, TICK_S)
_snake_metro:start()

redraw()
`;
}
